### PR TITLE
Added OUIA compatibility to Select component

### PR DESCRIPTION
**Pull request by quarckster**
What: Added OUIA props to Tabs as per #2423 

Additional issues: tests failed:
```
 FAIL  packages/patternfly-4/react-core/src/components/Select/Select.test.tsx
  ● Test suite failed to run

    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    packages/patternfly-4/react-core/src/components/Select/Select.tsx:538:47 - error TS2345: Argument of type 'typeof Select' is not assignable to parameter of type 'ComponentClass<SelectProps & InjectedOuiaProps, any> | FunctionComponent<SelectProps & InjectedOuiaProps>'.
      Type 'typeof Select' is not assignable to type 'ComponentClass<SelectProps & InjectedOuiaProps, any>'.
        Types of property 'defaultProps' are incompatible.
          Type '{ "children": ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)>[]; ... 21 more ...; "onFilter": () => {}; }' is not assignable to type 'Partial<SelectProps & InjectedOuiaProps>'.
            Types of property 'onClear' are incompatible.
              Type 'Function' is not assignable to type '(event: MouseEvent<Element, MouseEvent>) => void'.
                Type 'Function' provides no match for the signature '(event: MouseEvent<Element, MouseEvent>): void'.

    538 const SelectWithOuiaContext = withOuiaContext(Select);
```
@redallen @jschuler @karelhala I would appreciate any help with this.

### CODE REVIEW

**Comment by redallen** [comment]
This was a problem with the `defaultProps`' type, I pushed a change that will hopefully fix it.

**Comment by redallen** [comment]
Fixed the type used in a test.

**Comment by quarckster** [comment]
@redallen I'm afraid I can't fix failed tests. These errors are so cryptic to me.

**Comment by karelhala** [comment]
@quarckster you gotta update snapshots in order to fix circle build, this can be done by running
`node_modules/.bin/jest -u packages/patternfly-4/react-core/src/components/Select`

**Comment by quarckster** [comment]
@khala I applied your patch but there are still some errors

**Comment by quarckster** [comment]
@redallen tests passed

**Pull request merged**
