### PR TITLE
feat(Spinner): Adding Spinner component

### PR DESCRIPTION
**Pull request by danseethaler**
**What**: Adding Spinner component from main Patternfly library.

**Why**: To include more components in the react implementation.

**How**: Adding one component file and a stories file to demo.

### CODE REVIEW

**Comment by priley86** [comment]
thanks @danseethaler . This looks pretty reasonable. 

can you deploy the storybook so @jgiardino can take a look? 

I need to update the PR template...notes are in the README on this...

**Comment by priley86** [comment]
Quick glance thought... I think the new convention is to put the actual implementation inside `Spinner.js`... with `index.js` just exporting that...

I will double check this for anything else I can think of first thing tomorrow. Thanks for opening this up!

**Comment by danseethaler** [comment]
Well, looks like I used the storybook:deploy in a most unfortunate way. I wasn't certain which remote/branch to deploy to. Can you clarify this for me @priley86?

I ran `npm run storybook:deploy -- --remote=danseethaler --branch=spinner-component` but I'm guessing I should have run this in a different way since it blew away my remote branch. I'll try to recover the remote commit and reopen this PR but I may need to create another one.

**Comment by priley86** [comment]
@danseethaler yes, you should use a different branch name. Apologies for any confusion. I will try to update the readme and the pull request template tomorrow.

**Comment by danseethaler** [comment]
@priley86 just added #100 as a replacement to this PR.

**Pull request closed without merging**
