### PR TITLE
feat(Drawer): improve cursor responsiveness

### LINKED ISSUE #5281: Resizable drawer: cursor is sluggish
Feels sluggish when dragging (doesn’t follow mouse precisely) and if you move the mouse quickly, the drawer stops resizing before it hits the limits

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #5281

- Added a transition property to smooth the drag (mouse move events are not fired every pixel so there are gaps/stutters)
- Reorganized variables so reused but not recalculated values are not recalculated every move event

Continuing to investigate improving the responsiveness further, but wanted to get some initial feedback on the current changes. What do people think? Still laggy or better?

### CODE REVIEW

**Review by tlabaj — APPROVED** [review]
Looks good.

**Review by nicolethoen — DISMISSED** [review]

**Review by mcarrano — APPROVED** [review]
That looks much better!

**Review by dlabrecq — DISMISSED** [review]

**Review by evwilkin — APPROVED** [review]
LGTM - big improvement in responsiveness!

**Review by evwilkin — APPROVED** [review]
LGTM

**Review by tlabaj — APPROVED** [review]

**Pull request merged**
