### PR TITLE
WIP feat(tables): adds react-bootstrap-table and patternfly tables

### PR DESCRIPTION
**Pull request by priley86**
**What**:
Pushing an initial PR to showcase [react-bootstrap-table](https://allenfang.github.io/react-bootstrap-table/) and some markup rendered.

Good things:
👍 API is very comprehensive and would handle most PF functionality (sort, pagination, column visibility, csv export, etc)

Bad things:
👎 Markup is not semantic. Multiple `<table>` elements rendered inside div's
👎 Table is not really accessible it seems, even with [keyboard navigation](https://allenfang.github.io/react-bootstrap-table/example.html#keyboard-navigation) mode I can't go backwards when shift-tabbing.
👎 Custom CSS added in `react-bootstrap-table-all.min.css` is not good so I removed it and added a few custom classes to get it much closer.
👎 There is always an additional div rendering in the `th` element. Any knows how to remove it? (see Data Tables example started)
👎 PF has custom carrot rendered w/ `sorting_asc` class (example [here](http://www.patternfly.org/pattern-library/widgets/#data-tables)). We need to customize the `th` using a `ref` it appears.

Link to [Storybook](https://rawgit.com/priley86/patternfly-react/tables-storybook/index.html?knob-Label=Danger%20Will%20Robinson%21&knob-Striped=true&knob-Bordered=true&knob-Hover=true&knob-Data%20Sorting=true&selectedKind=Table&selectedStory=Basic%20Table&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs)

cc: @jeff-phillips-18  @ohadlevy @yaacov @amirfefer

At this point, I am wondering if we should go ahead and consider [reactabular](https://github.com/reactabular/reactabular) as it seems to have complete customization and should help avoid these sort of things...

Would ❤️  any more thoughts when you have a chance 😄 

**Additional issues**:

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
Shift-Tab seems to be navigating OK for me.

**Comment by jgiardino** [comment]
I only just briefly looked at the two, and am happy to review further as needed.

I did notice an issue with the [cell edit example](https://allenfang.github.io/react-bootstrap-table/example.html#celledit) for react-bootstrap-table where Shift+Tab would not work. That was the only instance of this issue I could find (and I'm not sure if this feature is a requirement for us)

For [reactabular](https://reactabular.js.org/#/examples/all-features), none of the actions are keyboard accessible, like pagination or sort, because they are not implemented with semantic html.

But I'm also not familiar at all with the level of customization for any of these and if the issues we're seeing are issues we can resolve in our implementation.

**Comment by priley86** [comment]
@jeff-phillips-18 @jgiardino thanks for the inputs..

The example I was seeing shift tab problems was [here](https://allenfang.github.io/react-bootstrap-table/example.html#keyboard-navigation) where the keyboard navigation mode is enabled. Can you check this one and see what you think?

Regarding reactabular, everything is customizable so we could get much closer to our existing table/data tables (and do a11y enhancements where desired). I think I am just looking to see whether or not react-bootstrap-tables will be an option at this point. Still evaluating myself too...

**Comment by priley86** [comment]
Planning to give this a try:
https://reactabular.js.org/#/examples/all-features

And quickly compare... Will see what gives...

**Comment by jgiardino** [comment]
> The example I was seeing shift tab problems was here where the keyboard navigation mode is enabled. Can you check this one and see what you think?

Yeah, that's weird. The shift+tab behaves like the tab. I am able to use the arrow keys though so it's not totally blocking keyboard access in that case.

**Comment by priley86** [comment]
I think we can close this now in favor of the effort started in #143 . thoughts?

**Comment by priley86** [comment]
I'm closing this for now. It seems like this table is not a good option.

**Pull request closed without merging**
