### PR TITLE
(Number input): Renamed Touchspin to NumberInput

### LINKED ISSUE #5277: Touchspin updates
Update the touchspin component's <input type="text"> to type="number", and hide the default browser controls. Also want to rename this component to "Number input."

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #5277
(Number input): Renamed Touchspin to NumberInput. and changed the type of the input to `number`.  This change is needed to pump the patternfly/patternfly version.

### CODE REVIEW

**Review by kmcfaul — DISMISSED** [review]

**Review by kmcfaul — APPROVED** [review]

**Comment by kmcfaul** [comment]
Is it possible to bump the version straight up to latest/4.77.4? This will bump it to 4.75. Resizable issues will need at least v4.76.2.

**Review by mcarrano — DISMISSED** [review]
Looks good to me. @mcoker do we also need a PR to change the name of the HTML component to "Number input?" Looks like we still have an HTML Touchspin.

**Review by kmcfaul — APPROVED** [review]

**Review by mcoker — APPROVED** [review]
LGTM!

**Comment by mcoker** [comment]
@mcarrano nope, we updated the component in the previous sprint, though we haven't released changes from that sprint yet. Here is what's on core currently - https://pf4.patternfly.org/components/number-input. That will go out with this release along with the react change.

**Review by redallen — APPROVED** [review]

**Pull request merged**
