### PR TITLE
fix(GenerateId): revert default behavior change

### PR DESCRIPTION
**Pull request by wise-king-sullyman**
Followup to #10178

### CODE REVIEW

**Review by tlabaj — APPROVED** [review]

**Review by dlabaj — APPROVED** [review]

**Comment by Hyperkid123** [comment]
@wise-king-sullyman Hello. How would one turn the random IDs globally now that the option is false by default? I am asking because there is no API in components (Toolbar for example) where we can switch to the random IDs. Currently, we can't solve the original issue other than adding custom IDs.

I don't have an issue with manually adding IDs, the problem is that by default we get random ones which causes the conflicting IDs in the first place.

**Comment by wise-king-sullyman** [comment]
@tlabaj WDYT? If we're going to keep the default behavior as is I think we'll either need to set up all the components using `GeneratedId` to drill the needed props through, or wire up something with a context.

**Comment by wise-king-sullyman** [comment]
@Hyperkid123 I'm probably just not understanding something, but wasn't the original issue with the previous approach that we were trying to have `GenerateId` be a singleton?

**Comment by Hyperkid123** [comment]
Ah, I see now. I missed the static default props. NVM them. My comment is irrelevant.

**Pull request merged**
