### PR TITLE
chore(BackgroundImage/AboutModal): updated usage of bg image

### LINKED ISSUE #8452: Login/About modal - update use of background image
Placeholder for work in https://github.com/patternfly/patternfly/issues/5282

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Closes #8452 

@srambach @tlabaj  for AboutModal, the class for the AboutModalBoxHero (`.pf-c-about-modal-box__hero`) was removed in Core documentation, but still remains in the scss. Would it make sense to remove that sub-component entirely here? There may be a Core followup needed as there is still a CSS var in the scss file that isn't really being used now it seems (`--pf-c-about-modal-box__hero--sm--BackgroundImage`)

Also Titani, since I'm making updates in LoginPage, would you want me to close out https://github.com/patternfly/patternfly-react/issues/7867 as well (removing the `backgroundImgAlt` prop)?

**Additional issues**:

### CODE REVIEW

**Review by nicolethoen — APPROVED** [review]

**Comment by tlabaj** [comment]
> Also Titani, since I'm making updates in LoginPage, would you want me to close out #7867 as well (removing the `backgroundImgAlt` prop)?

Yes please.

**Comment by tlabaj** [comment]
> @srambach @tlabaj for AboutModal, the class for the AboutModalBoxHero (`.pf-c-about-modal-box__hero`) was removed in Core documentation, but still remains in the scss. Would it make sense to remove that sub-component entirely here? There may be a Core followup needed as there is still a CSS var in the scss file that isn't really being used now it seems (`--pf-c-about-modal-box__hero--sm--BackgroundImage`)

Unless `.pf-c-about-modal-box__hero` was unintentionally left out by core, I would say yes, remove the sub-component.

**Review by mcarrano — APPROVED** [review]
Looks good to me. Thanks @thatblindgeye !

**Comment by thatblindgeye** [comment]
@tlabaj made the above updates and also created codemod issues for changes made here.

**Review by kmcfaul — APPROVED** [review]

**Comment by srambach** [comment]
I'm seeing the close icon smaller than in core. Another svg icon related thing?
image

**Comment by tlabaj** [comment]
> I'm seeing the close icon smaller than in core. Another svg icon related thing?

I don't think so @srambach .  If you look in my PR that fixes the icons, it looks the same as in this PR.
https://patternfly-react-pr-8954.surge.sh/components/about-modal

**Review by srambach — APPROVED** [review]
I don't actually think the icon is related, this looks fine.

**Pull request merged**
