### PR TITLE
feat(ExpandableSection): Add event to onToggle

### LINKED ISSUE #8880: ExpandableSection: add event param to `onToggle` callback. It should be first parameter.

### PR DESCRIPTION
**Pull request by wise-king-sullyman**
**What**: Closes #8880

**Additional issues**:

### CODE REVIEW

**Review by thatblindgeye — COMMENTED** [review]
Could we also update the `onToggle` in ExpandableSectionToggle sub-component, as well as examples that use it (believe only the ExpandableSection's "Detached" example and CodeBlock's "Expandable" example)? Either that or it could be another issue for the epic.

**Comment by wise-king-sullyman** [comment]
I think I would prefer that to be a separate issue in the epic like most other subcomponents are, but I wouldn't say I'm dead set on that.

**Review by thatblindgeye — APPROVED** [review]
I have no strong preference either way so a separate issue sounds good to me 👍🏼

**Review by tlabaj — APPROVED** [review]
LGTM

**Pull request merged**
