### PR TITLE
feat(Dropdown): add dropdown groups option

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Adds dropdown groups option and example

**Refer to issue**: #1485

### CODE REVIEW

**Comment by mcoker** [comment]
Do you know where `aria-hidden="true"` on the `h1.pf-c-dropdown__group-title` element came from? We don't have that in core and I'm pretty sure you want the group titles to be read by screen readers.

**Comment by kmcfaul** [comment]
I implemented these groups after the ones in checkbox so it's possible I carried over that property. @jgiardino Should the hidden tag be removed for dropdown group titles?

**Comment by christiemolloy** [comment]
Looks like this should say Group 1 but I cant see it

Screen Shot 2019-05-07 at 3 48 05 PM

**Comment by kmcfaul** [comment]
For the example, I was matching the one in core which shows the Group label can be left out.

**Pull request merged**
