### PR TITLE
fix(SelectDeprecated): use textinput component for typeahead

### LINKED ISSUE #9313: Bug - v5 preview testing - Select
While testing Cost management with pf-v5, I noticed our Select component has odd borders around the down-arrow.

Before the selection
Screenshot 2023-06-28 at 1 23 47 PM

After the selection
Screenshot 2023-06-28 at 1 24 55 PM

Code
https://github.com/dlabrecq/koku-ui/blob/pf-v5/src/routes/components/groupBy/groupBySelect.tsx#L146

### PR DESCRIPTION
**Pull request by gitdallas**
Closes patternfly/patternfly-react#9324

### CODE REVIEW

**Comment by gitdallas** [comment]
The timestamp appears to be off by 1 second..

**Review by tlabaj — APPROVED** [review]
lgtm

**Review by mcoker — APPROVED** [review]
🥸👍

**Review by kmcfaul — APPROVED** [review]
LGTM

**Pull request merged**
