### PR TITLE
build(package.json): Upgrade react-bootstrap-typeahead to 3.4.1

### LINKED ISSUE #1366: PF3: react-bootstrap-typeahead version should be bumped to bring in bugfixes
In https://github.com/ManageIQ/manageiq-v2v/pull/876, we are seeing an issue downstream which was reported in https://github.com/ericgio/react-bootstrap-typeahead/issues/381, and fixed in their v3.2.3 release. We should update to `react-bootstrap-typeahead@^3.3.4`, their latest release which still supports bootstrap v3.

### LINKED ISSUE #1491: Typeahead warnings after version update
Getting unexpected console warnings after the library has been updated.
opened an issue to `react-bootstrap-typeahead`: [issue](https://github.com/ericgio/react-bootstrap-typeahead/issues/428)

### PR DESCRIPTION
**Pull request by mturley**
Closes #1366.
Closes #1491.

### CODE REVIEW

**Comment by mturley** [comment]
I have no idea whether it's normal for `yarn.lock` to have so many changes here... I just did `yarn add react-bootstrap-typeahead@^3.3.4`.

**Comment by Laviro** [comment]
seem to break some of the tests in Foreman, I will look more into it later today.

**Comment by Laviro** [comment]
I get this warning which i saw you already referred in the related PRs,
`react-bootstrap-typeahead` mentions that it was fixed in `v3.2.3`
```
   Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
        in input
        in div
        in HintContainer(TypeaheadInputSingle)
        in InputContainer(HintContainer(TypeaheadInputSingle))
        in div
        in Typeahead
        in WrappedTypeahead
        in TypeaheadContainer(WrappedTypeahead)
        in OnClickOutside(TypeaheadContainer(WrappedTypeahead)) (created by AutoComplete)
        in div (created by AutoComplete)
        in AutoComplete (created by SearchBar)
        in div (created by SearchBar)
        in SearchBar (created by Connect(SearchBar))
        in Connect(SearchBar)
        in Provider (created by WrapperComponent)
        in WrapperComponent
```

**Comment by mturley** [comment]
Closing this since @Laviro's PR https://github.com/patternfly/patternfly-react/pull/1493 meets the same need and also updates the Storybook stories.

**Pull request closed without merging**
