### PR TITLE
fix(Card demo): use proper token

### LINKED ISSUE #10582: Utilization 3 Card demo not pulling in the correct styles
the critical color seems to have dropped in the react demo: 
image

Here's the core demo for comparison: 
image

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #10582

Updates the demo to use the proper red-orange token as the red tokens were removed.

### CODE REVIEW

**Comment by tlabaj** [comment]
It still does not look right.  
Here is core:

Screenshot 2024-08-07 at 8 50 06 AM

Here is this PR:

Screenshot 2024-08-07 at 8 52 17 AM

**Review by tlabaj — APPROVED** [review]
LGTM
It looks like core's demo is using an image and not an actual chart.

**Comment by kmcfaul** [comment]
Core's example will have to be updated with the new color

**Comment by kmcfaul** [comment]
Updated the PR to use the red-orange 400 token based on feedback in slack

**Review by thatblindgeye — APPROVED** [review]

**Review by lboehling — APPROVED** [review]
thank you!

**Pull request merged**
