### PR TITLE
fix(Dropdown): Do not focus Dropdown if menu is not opened

### PR DESCRIPTION
**Pull request by karelhala**
**What**:
If user clicks anywhere on screen and dropdown is present it will automatically scroll to such dropdown even if it's not opened.

**Additional issues**:
https://github.com/RedHatInsights/insights-frontend-components/issues/222

### CODE REVIEW

**Comment by karelhala** [comment]
Honestly I think that this bug should have been fixed differently, but this works as a hot fix.

Proper fix would require adding domlisteners to DropdownMenu and triggering toggle from there because this menu is destroyed everytime we close it. Plus with this fix we would clean event listener (quite expensive to fire onToggle for multiple dropdowns).

**Comment by jgiardino** [comment]
Thanks for submitting a bug fix for this! I wasn't able to reproduce this issue in the workspace, but also didn't see any issues with the dropdown after these changes.

**Comment by karelhala** [comment]
@jgiardino you can reproduce it by clicking on any dropdown, scrolling a bit so this dropdown is not visible and clicking anywhere on screen.

**Comment by jgiardino** [comment]
Ah, ok. Thanks for the clarification. I was able to see this issue. 
😄👍

**Pull request merged**
