### PR TITLE
chore(a11y): update a11y config to include docs

### PR DESCRIPTION
**Pull request by nicolethoen**
Closes: #7777

### CODE REVIEW

**Review by tlabaj — CHANGES_REQUESTED** [review]
This PR seems to increase the build time rather excessively.  The build is already very long (41minutes).  The build time on this PR is 52 minutes.

**Comment by nicolethoen** [comment]
yeah - part of the reason I opened it was to test the build time - I expected it to increase a little, but I know I'll have to play with it more

**Review by tlabaj — COMMENTED** [review]
looks great!  can  you resolve conflicts so we can take this in.

**Review by tlabaj — APPROVED** [review]
LGTM

**Review by gitdallas — APPROVED** [review]

**Pull request merged**
