### PR TITLE
fix(pagination): dropdown closes on click outside of menu area

### LINKED ISSUE #1562: PF4 Pagination per page menu sticks open
The menu used to set the number of items per page does not close properly. The menu opens and closes when using the button. However, when clicking elsewhere in the page, the menu remains open unexpectedly. Users can only close the menu by clicking the button, again.

chrome-capture (1)

### PR DESCRIPTION
**Pull request by jenny-s51**
**What**: closes #1562

### CODE REVIEW

**Comment by tlabaj** [comment]
@mcoker this has been merged. But can you just take a look at it to make sure everything looks good. Thanks!

**Comment by nicolethoen** [comment]
@mcoker @tlabaj I can address any concerns about this PR in [PR #2256 ](https://github.com/patternfly/patternfly-react/pull/2256)

**Comment by mcoker** [comment]
@tlabaj @nicolethoen from reading [jenn's notes](https://github.com/patternfly/patternfly-react/issues/1562#issuecomment-499877096) in https://github.com/patternfly/patternfly-react/issues/1562, are we going to make this default functionality in the options menu? Looks like for this PR, the functionality was only added to the pagination component's options menu.

LGTM overall, but I did notice that clicking in the options menu text doesn't trigger the menu to close. Should it? I would expect it to if I'm clicking anywhere outside of the menu area.

Here's a screenshot with the text I'm referring to highlighted.

Screen Shot 2019-06-13 at 1 27 53 PM

**Comment by nicolethoen** [comment]
@mcoker I just pushed a change to [#2256](https://github.com/patternfly/patternfly-react/pull/2256) to make the options menu text click trigger a close. There is a build issue (I don't think related to my changes) so I'm not sure you can see the change in the preview yet.

**Pull request merged**
