### PR TITLE
chore(LogViewer): move to extensions

### LINKED ISSUE #6010: LogViewer: Move to extensions in docs
**Describe the issue. What is the expected and unexpected behavior?**

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

**What is your product and what release version are you targeting?**

### PR DESCRIPTION
**Pull request by nicolethoen**
**What**: Closes #6010

**Additional issues**:

### CODE REVIEW

**Review by evwilkin — DISMISSED** [review]
LGTM

**Review by tlabaj — CHANGES_REQUESTED** [review]
Can you also add Log viewer to the extensions in the table on the main repo page. `https://github.com/patternfly/patternfly-react`

**Review by kmcfaul — APPROVED** [review]

**Comment by nicolethoen** [comment]
@tlabaj made the update

**Review by evwilkin — APPROVED** [review]
LGTM

**Review by dlabrecq — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]

**Pull request merged**
