### PR TITLE
fix(Wizard): add className props and spread them when possible

### LINKED ISSUE #10665: Bug - Wizard - props not being spread in various child components
There are a few things missing from the the props in various Wizard child components

For example in WizardNavItem:

1. The props are not getting spread to the WizardNavItem's `li` element.
2. The props also don't extend `React.HTMLProps<HTMLLIElement>`
3. the className is not included in the props, so I cannot add any custom classes to the `li` element.

These issues are also present in at least:

- WizardNav
- WizardBody
- WizardFooter
- WizardHeader
- WizardToggle

This is inhibiting QuickStart's ability to style individual WizardNavItems to have success/failure/etc styles as part of https://github.com/patternfly/patternfly-quickstarts/issues/299

### PR DESCRIPTION
**Pull request by nicolethoen**
**What**: Closes #10665 

unblocks an issue in quickstarts v6 migrations

### CODE REVIEW

**Review by wise-king-sullyman — COMMENTED** [review]
Tests for these added props would be great to have IMO, but other than that and it looking like the lock file needs an update LGTM.

**Comment by nicolethoen** [comment]
I'll add tests later today 👍🏻

**Review by tlabaj — COMMENTED** [review]
Can you also make this change on main.

**Review by thatblindgeye — APPROVED** [review]

**Review by wise-king-sullyman — APPROVED** [review]
🥳

**Review by tlabaj — APPROVED** [review]

**Pull request merged**
