### PR TITLE
fix(DataList): Add dropdown and button actions to DataList

### PR DESCRIPTION
**Pull request by boaz0**
This is a follow-up to #927 
Now you can add `Dropdown` or `Button` to `DataListAction`.
Please feel free to review the API, I did it as simple as I could but if you believe it needs another abstraction or logical layer, I would like to hear.

cc @jgiardino @jschuler @christiemolloy

### CODE REVIEW

**Comment by tlabaj** [comment]
@boaz0 Please resolve conflicts.

**Comment by boaz0** [comment]
@tlabaj rebased.

**Comment by tlabaj** [comment]
@boaz0 what is the status of this PR?  Looks like there are some outstanding comments from @christiemolloy  that should be address?

**Comment by boaz0** [comment]
Thank you all for the patience and feedback. Appreciate it a lot.
:bowing_man: :pray:

**Pull request merged**
