### PR TITLE
feat(SearchInput): Autocomplete SearchInput demo

### PR DESCRIPTION
**Pull request by nicolethoen**
Closes: #6210

Adds new react-demo for autocomplete

### CODE REVIEW

**Review by mcoker — DISMISSED** [review]
LGTM!

**Review by CooperRedhat — APPROVED** [review]
LGTM

**Review by kmcfaul — APPROVED** [review]

**Review by mcarrano — DISMISSED** [review]
This looks great @nicolethoen !

**Review by CooperRedhat — APPROVED** [review]
LGTM

**Review by tlabaj — APPROVED** [review]
Looks great!   I think all the comments in the demo will help consumers implement their own.

**Pull request merged**
