### PR TITLE
chore(ExpandableSection): updated indented example for Penta disclosure variation

### LINKED ISSUE #9850: Expandable Section: Consume Penta tokens
Follow up to Core PR https://github.com/patternfly/patternfly/pull/6063

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Closes #9850

No other updates needed to consume Penta tokens

**Additional issues**:

### CODE REVIEW

**Comment by andrew-ronaldson** [comment]
The surge on this seems to be broken.

**Comment by thatblindgeye** [comment]
@andrew-ronaldson That might be worth a convo, as the Accordion component behaves the same way. If we don't want that styling on click we should be able to update styles in Core to `focus-visible` instead of just `focus`, similar to the update made to Switch

**Comment by nicolethoen** [comment]
It took me a while to figure out the difference between the large indent example, and the disclosure variation.

Could we add a sentence or be a little clearer in the example title what the purpose of the disclosure variation is? And maybe update the indent example to be called 'indent expandable content body' or something like that, to make it clearer?

**Comment by nicolethoen** [comment]
it looks like according to the core docs that the disclosure variant is the large display size variant? could that be true?

**Review by wise-king-sullyman — APPROVED** [review]

**Review by kmcfaul — APPROVED** [review]

**Review by andrew-ronaldson — APPROVED** [review]
Approved!

**Review by mcoker — APPROVED** [review]
🚀

**Pull request merged**
