### PR TITLE
improvement(Icons): Add battery icons and allow multiple paths for icons

### PR DESCRIPTION
**Pull request by karelhala**
**What**: Don't think there's an issue for this as of yet, but multiple UX folks asked for this icon

**Additional issues**: We'd like to use battery icon accross multiple projects (currently being used by cloud.redhat.com and Openshift would like to use it as well).

Because battery icon requires multiple paths this PR introduces new way how to define multiple paths per one icon.

Screenshot from 2020-05-04 18-40-09

### CODE REVIEW

**Comment by karelhala** [comment]
ping @doruskova

**Comment by karelhala** [comment]
@redallen hold on. Patternfly is dropping support for some font awesome icons and allowing only some custom icons? Those are unsettling news for me.

**Comment by redallen** [comment]
Our current plan is to officially support a subset of FontAwesome icons starting upstream from Core (which will export it's own custom font as well) rather than using a [copied version in Core](https://github.com/patternfly/patternfly/tree/v4/src/patternfly/assets/fonts/webfonts) and the [NPM packages in React.](https://github.com/patternfly/patternfly-react/blob/v4/packages/react-icons/package.json#L31) We will have plans for how to migrate off of non-whitelisted FontAwesome icons for `@patternfly/react-icons` consumers since we are currently unsure of their usage.

If you'd like the entire set that we have now to still be included in PatternFly I'd suggest talking to @mcarrano .

**Comment by karelhala** [comment]
Well the usage there is pretty high, at least on cloud.redhat.com and we were happy with it. Having a ton of icons wrapped in React with custom ones as well. Was this communicated somewhere? I'd like to know reasoning behind this.

When the icons were first created the idea was to have as much icons from as many upstream projects as possible. So we won't be limited in any way and could contribute custom ones too. If PF wants to drop the support on this can we come up with a different sollution? To have a new repository for this specific purpose where each team can submit their icons so every other project can use them.

**Comment by ryelo** [comment]
Yeah this might be a huge issue for a lot of apps on cloud.redhat.com. I know each app is using a wide set of icons (which is a number that is unknown to me). I really liked the currently implementation as well as many other devs on our platform, so dropping support for it would be a shame in my opinion. 

I'm happy to talk about other solutions if there is something we can do to help keep it alive.

**Comment by evwilkin** [comment]
@karelhala @ryelo thanks for catching us up on product needs for these icon updates!  To clarify a bit, we are planning on discussing potential changes to the icon set after getting through this major release, but one immediate call out was that we would not want to remove any icons at this point - rather add to the existing set, and if necessary create a long-term deprecation plan as needed.

I believe @mcarrano is working to better define the process of adding new supported icons (such as these battery icons), but I wanted to add that context to let you know we're not working on removing any icons at this time.

**Comment by kybaker** [comment]
@karelhala As part of the post Summit work for cloud.redhat.com (and beyond) we are re-evaluating the use of this battery symbol as a metaphor to represent levels of impact severity. This legacy icon has been on our radar for some time and has not been resolved partly because of the complication that comes from using multicolored icons in our current icon font libraries.

@mcarrano @evwilkin I would recommend closing this issue and if there is still actionable issues here opening another issue specifically related to the feedback from @ryelo and @karelhala

**Comment by karelhala** [comment]
@kybaker I might see what is the problem here. Please do not confuse react icons with font. This library was build to hold many svg icons that can be used anywhere by many apps. I don't think that closing this PR without proper reasoning sends bad message to community. We need to have a discussion about future of react-icons and whare it goes, there has been so many misunderstanding from so many parties that it makes me sad.

**Comment by redallen** [comment]
I started typing a brief reply, but it turned into the entire story of our icons, so [I just opened an issue in org to create official icon sets.](https://github.com/patternfly/patternfly-org/issues/1836)

How that will be implemented is yet to be seen, but for now it won't include these battery icons @karelhala has graciously provided unless our designers decide it should. Sorry @karelhala , @AllenBW , and @ryelo, I want to just press the merge button and allow developers to share these icons in `@patternfly/react-icons` as much as you, but it's not the right thing to do. Further discussion can take place [on the org issue.](https://github.com/patternfly/patternfly-org/issues/1836)

**Comment by karelhala** [comment]
@redallen this is not the way how to treat a submission from community!

**Comment by terezanovotna** [comment]
These battery icons are consistently used in cloud.redhat.com for a while for multiple apps and I am on board they should be included in Patternfly as it would benefit all. cc @katierik @jeperry

**Comment by LHinson** [comment]
Hey @karelhala @terezanovotna @kybaker @redallen @kybaker @evwilkin just a heads up to everyone that there is a meeting today to sync between PF designers/devs and c.rh.c designers/devs and we will get this all cleared up and identify the path forward. Figured I would mention this so that we don't continue to spin our wheels on the github issue. We will report back here on the resolution.

**Pull request closed without merging**
