### PR TITLE
chore: revert attempts to update release script

### PR DESCRIPTION
**Pull request by nicolethoen**
**What**: Closes #

**Additional issues**:

### CODE REVIEW

**Review by evwilkin — APPROVED** [review]
LGTM

**Comment by nicolethoen** [comment]
I just merged a charts PR and i noticed that it only bumped the react-charts and react-docs packages: https://github.com/patternfly/patternfly-react/pull/8035
And in the actions log it still says its looking at the latest verison of react-catalog-view, but it did bump the right packages: https://github.com/patternfly/patternfly-react/actions/runs/3105861321/jobs/5032323760

maybe I dont need to revert this?

**Comment by tlabaj** [comment]
Hi.  Is there an issue for this one?

**Comment by nicolethoen** [comment]
not yet - Its the product of some experimenting with lerna - per my last comment i'm not sure we will want to merge this yet. I need to dig into it a little more with dana i think

**Comment by nicolethoen** [comment]
reverting appears unnecessary - version bumps are working with these latest updates.

**Pull request closed without merging**
