### PR TITLE
feat(Menu): add drilldown filter demo, add flag to support demo & fix some keyboard interaction

### LINKED ISSUE #6965: Add ability to filter items in a submenu in the composable drilldown menu
I'd like the ability to filter items in a submenu in the composable drilldown menu. This requirement has come from ongoing design work for the new PF query builder. The filtering would only apply to the items in the current submenu that the user has drilled into. 
 
Including some potential placements in the mocks below. I think I'm leaning towards Option A, as I think it would be nice to have the back nav and filter box fixed at the top together.

image

FYI @mcarrano @mmenestr @nicolethoen

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #6965

Adds a new `shouldFocusOnDrillIn` property to control whether the menu will focus the first option in the list when a drilldown transition happens. This property is used in the demo to prevent re-focusing the first item in the current menu when the list contents change based on the filter state.

Also adds some robustness to the internal keyboard handler props to account for MenuInput (and maintain general menu items and checkbox menu items).

LMK if the demo should remain on the docs page or if this is better off as a codesandbox only demo.

### CODE REVIEW

**Review by mcarrano — COMMENTED** [review]
The filter behavior looks good @kmcfaul . I was a bit confused about what the new prop is intended for. This description seemed contradictory to me, but maybe I'm not understanding.

Screen Shot 2022-12-06 at 3 38 11 PM

**Comment by kmcfaul** [comment]
@thatblindgeye Updated based on our slack conversation. I ended up using the menu `id` instead of children length because I was getting some inconsistency in the focusing when the menu would drill out to the root menu and it wouldn't focus (because the length still changed). LMK what you think.

@mcarrano Ended up removing that property, but the purpose was to prevent the default behavior of focusing the first option in the list when the drilldown drilled in or out.

**Review by mcarrano — APPROVED** [review]
OK. I approve then. Thanks @kmcfaul !

**Review by nicolethoen — APPROVED** [review]

**Review by thatblindgeye — APPROVED** [review]
🎉

**Review by mmenestr — APPROVED** [review]

**Pull request merged**
