### PR TITLE
fix(Table): fix tooltips not appearing

### PR DESCRIPTION
**Pull request by kmcfaul**
Tooltips were not appearing for `Th` and `Td` because of the trigger wrapping div.

### CODE REVIEW

**Comment by kmcfaul** [comment]
The `DropdownToggleCheckbox` is unrelated the bug, it is just breaking the build atm due to a removed prop still being present.

**Comment by kmcfaul** [comment]
Debugging an issue where passing `tooltip` directly is causing two tooltips to appear (after a few mouse-ins, the passed tooltip will no longer render)

**Comment by kmcfaul** [comment]
Currently this PR fixes the tooltips not appearing at all and the cells flickering/spacing issues. But adds the issue with manual `tooltip`. 

Needs more investigation why referencing the cell separately messes up custom tooltips. Or a core issue to adjust the table styling to account for the wrapping div which seems to be causing the spacing issue.

**Review by tlabaj — APPROVED** [review]

**Comment by kmcfaul** [comment]
Traced the source of the extra tooltip: the `SortColumn` wraps the children with `TableText`, which is generating a separate tooltip if the text is truncated. This tooltip isn't exposed to the user, customizable, or removable. 

This might be a larger discussion and require a followup refactor to determine how and where custom tooltips should be implemented for Table. 

For this PR, I have updated `Popper` to allow both `trigger` and `reference` to be passed in together. If both are passed in, the wrapping div will be removed (because of `reference`) and the trigger will still be rendered by Popper instead of shifting the render to the component that is calling Popper. This is general change to make updates to other Popper consumers simpler for removing the wrapping div if it's causing issues, and still fixes the spacing issue.

**Comment by thatblindgeye** [comment]
So it looks like the default tooltip for truncation is appearing fine on hover. Would we want to open a follow up regarding discussion/refactoring for custom tooltips being passed in since there still is a bug when passing one in?

I'm also noticing that tooltips don't appear when a truncated header receives focus. That *might* tie into a possible followup discussion/refactor, but since this PR is trying to resolve tooltips not appearing correctly it would be worth trying to include it here if it's a straight forward enough fix.

**Comment by gitdallas** [comment]
Looks like this may have been covered here: https://github.com/patternfly/patternfly-react/pull/8733

**Comment by gitdallas** [comment]
closed due to being covered in https://github.com/patternfly/patternfly-react/pull/8733

**Pull request closed without merging**
