### PR TITLE
refactor(Toolbar-docs): use SearchInput in Toolbar demos

### PR DESCRIPTION
**Pull request by MariaAga**
**What**: Closes https://github.com/patternfly/patternfly-react/issues/6682

### CODE REVIEW

**Comment by jeffpuzzo** [comment]
This looks good to me. There are 2 small discrepancies with "with filters" example I'll note here, but I don't consider them blocking:
Original: 
image
image

New:
image
image

**Review by jeffpuzzo — APPROVED** [review]

**Comment by MariaAga** [comment]
I see the original the same for with filters, not sure where to see the second screenshot with the long `risk` and `status` selects.
Original screenshot: 
Screenshot from 2022-01-04 19-49-38

**Comment by jeffpuzzo** [comment]
> I see the original the same for with filters, not sure where to see the second screenshot with the long `risk` and `status` selects. Original screenshot: Screenshot from 2022-01-04 19-49-38

@MariaAga Sorry, I should have specified, that view is possible when the window's width is condensed to < 1200px. At this point, the filter icon is presented, and clicking on that will yield what's seen in those other screenshots.

**Comment by MariaAga** [comment]
I don't see some of the components when using `< 1200px`, is that a known issue?
My view for https://www.patternfly.org/v4/components/toolbar/
Screenshot from 2022-01-04 19-59-17

**Comment by jeffpuzzo** [comment]
> I don't see some of the components when using `< 1200px`, is that a known issue? My view for https://www.patternfly.org/v4/components/toolbar/ Screenshot from 2022-01-04 19-59-17

What you see is correct. The last step is to click this icon here, then you should see those inputs:
image

**Review by nicolethoen — CHANGES_REQUESTED** [review]
Could you also update the text input to a search input in the following files:

https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/demos/Toolbar.md

the Filterable Table demo found here:
https://github.com/patternfly/patternfly-react/blob/main/packages/react-table/src/demos/Table.md#filterable

**Comment by MariaAga** [comment]
Fixed the visual discrepancies. Also changed in https://github.com/patternfly/patternfly-react/blob/main/packages/react-table/src/demos/Table.md#filterable.
I didn't text input in https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/demos/Toolbar.md

**Comment by nicolethoen** [comment]
> Fixed the visual discrepancies. Also changed in https://github.com/patternfly/patternfly-react/blob/main/packages/react-table/src/demos/Table.md#filterable. I didn't text input in https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/demos/Toolbar.md

Thanks! You're right! Someone already went in and updated the Toolbar demo to use a Search Input

**Review by tlabaj — APPROVED** [review]
LGTM

**Review by nicolethoen — APPROVED** [review]

**Comment by mcarrano** [comment]
After discussion with @mmenestr I'd like to hold on merging this for now. We realized that there are lot's of similar examples across the library (including on the core side) and making this change will just introduce more inconsistency. We will look at the bigger picture of this and make some recommendation as to what examples we want to expose in general for demonstrating toolbar capabilities. Thank you for your efforts on this to date @MariaAga . I don't think it's to waste, but I want to consider the larger problem before we move forward.

**Comment by MariaAga** [comment]
Switched the input in some more components, but I'm not sure what do switch in `Masthead` and `Context Selector`

**Comment by mcarrano** [comment]
@MariaAga I'm not sure what needs to change for the Masthead, either. I think we can leave the Context Selector as is since that search is baked into the component. @mmenestr can you review when you are back from PTO?

**Comment by mmenestr** [comment]
The masthead would be changing the search inside of the context selector dropdown, but if you say it's baked in, i'm not sure it applies to either.

In general, it looks good! but @mcarrano I think we had discussed changing all the searches to use the "search input" component without the arrow button. So we might want to change that in this PR as well - but just want to confirm with you?

**Comment by MariaAga** [comment]
Thanks for the review!
Changed the search to be the basic variant in `Toolbar` and `DataList` but in `Table` there is a functional search bar in the original demo, so I left the arrow in that demo:
http://localhost:8002/components/table/react-demos#filterable
Screenshot from 2022-02-04 13-06-37

**Comment by mmenestr** [comment]
@MariaAga thank you for making the changes! All looks good to me, and I'm fine with leaving the arrow in that example, since as you say, it doesn't search until the user submits the search :) 

I did notice a random bug I wanted to flag while I was testing it out, which is that when you get the empty state about no search results, there's a floating checkbox in the left side of the empty state that shouldn't be there haha not sure if that's something we can fix in this PR, or if we'd rather open a new PR - but thought I'd flag.

image

**Comment by mmenestr** [comment]
Sure, if you could open a new PR that would be great, and we can address it there! Thank you :)

**Comment by MariaAga** [comment]
Opened https://github.com/patternfly/patternfly-react/pull/6898 for it

**Review by mmenestr — APPROVED** [review]

**Pull request merged**
