### PR TITLE
feat(core): convert AboutModal to typescript

### PR DESCRIPTION
**Pull request by redallen**
**What**: Convert AboutModal to Typescript

**Additional issues**:

### CODE REVIEW

**Comment by redallen** [comment]
This is ready to go, the only issue is that the Gatsby doc builds are all timing out (over 30 minutes) on CircleCI.

**Comment by dlabaj** [comment]
@redallen Is this ready to be merged if the review comes back as good, or we waiting on the Gatsby timeout issue?

**Comment by redallen** [comment]
The issue with this is that Gatsby times out on both CircleCI and Travis. Not completely sure why, but it has something to do with `typedoc` or `react-docgen` getting the property types. I'm fixing that issue in #1656 and then I'll carry on with Typescript conversion.

**Comment by dlabaj** [comment]
Added do not merge since it breaks the docs at the moment.

**Comment by redallen** [comment]
Closing due to About modal changes over the past 30 days. Will open a new PR later.

**Pull request closed without merging**
