### PR TITLE
fix(Modal): Various bug fixes V5

### LINKED ISSUE #11041: Bug - [Modal] - models incorrectly mark dom nodes with aria-hidden="true"
**Describe the problem**
`Modal` components incorrectly update the `aria-hidden` attribute of the root and siblings.

When a modal is open, the root and all siblings should have `aria-hidden="true"` except for the modal container.

When using `React.StrictMode` along with a `useEffect` somewhere in the app hierarchy, the [double rendering](https://react.dev/reference/react/StrictMode#fixing-bugs-found-by-double-rendering-in-development) effect of strict mode causes the open modal to have `aria-hidden="true"` when it shouldn't.

Also when using `React.StrictMode` a new `div` is appended to the DOM which is never removed until the page is refreshed.

Finally if there are multiple Modals rendered with `isOpen={false}` and one of them is opened, the root and all siblings lose their attribute `aria-hidden="true"`.

When using Cypress for testing, selectors will fail to find elements within a hidden element if `aria-hidden="true"`. This prevents our developers from using cypress against a dev env and allowing them to develop and run their cypress tests against their dev app.

**How do you reproduce the problem?**
Here's a sandbox with all the use cases.
https://codesandbox.io/s/withered-frog-qc67dn?file=/index.js

**Expected behavior**
Using `React.StrictMode` should have no bearing on the correct functionality of the `Modal` component. It should work as expected in or out of this mode.

**Is this issue blocking you?**
**Yes.**
Unable to run our cypress tests within a development environment which is using `React.StrictMode`. 

Work around is to edit the app and remove strict mode however that is not a viable solution all the time.
Alternatively, devs can run cypress against a production build which takes much longer to iterate with during development.

**What is your product and what release date are you targeting?**
RHOAI

**Any other information?**

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #11041 

This fixes:

- Modal container getting `aria-hidden = true` when in `StrictMode`
- Modal adjacent siblings getting `aria-hidden = true` incorrectly removed
- Modal div getting created and not removed until refresh
- This also removes the wrapping container div that was use to append the modal to when creating a portal.  Instead, we append directly to the documentation body by default  (Newer react documentation shows this as an example).   The consumer can still pass an element to append to the via the `appendTo` prop. 

I also added `.history` to the eslint ignore.

The test example can be used to test out the Modal changes [here](https://patternfly-react-pr-11168.surge.sh/components/modal#examples. ) and the Modal Next changes [here](https://patternfly-react-pr-11168.surge.sh/components/modal/react-next). You can compare the examples with the original issue in the code sandbox that was provided by the reporter https://codesandbox.io/s/withered-frog-qc67dn?file=/index.js
cc @christianvogt 

 
TODO:

- Remove the test examples 
~~- Make the same changes to the Modal next~~
- In the main branch make changes to the Modal and deprecated Modal.

### CODE REVIEW

**Comment by kmcfaul** [comment]
I'm a little confused by the test examples' text and want to confirm that we should not be seeing `aria-hidden={false}` on non-hidden modals. The text indicates to look for the attribute but it isn't present. And for the adjacent modal example, the text says to look for closed modals' attributes but the closed modals aren't in the DOM - which the PR indicates should be the case. 

I think both behaviors make sense but want to make sure I'm not misunderstanding. If they are correct, then this PR LGTM.

**Comment by tlabaj** [comment]
@kmcfaul the example are directly copied from the code sandbox in the issue.  SO the text in the example talks about the bug that was fixed.  I agree that is confusing.  I can update it.

**Review by kmcfaul — APPROVED** [review]
lgtm, just needs the test example removed

**Review by thatblindgeye — APPROVED** [review]

**Review by mcoker — APPROVED** [review]
🚀

**Pull request merged**
