### PR TITLE
feat(Modal): Allow custom header and footer

### LINKED ISSUE #1545: Modal - add render prop to allow for custom title content
We would like to more complex content to the title of a `Modal`. This isn't possible now with the existing `title` string prop. Please add support for a render prop to support custom title rendering with more complex content.

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
**What**:
Allows for custom header and/or footer in Modal component

Fixes #1545

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@jeff-phillips-18 can you fix the conflicts please? We could really use this one. Or if you want I cant take this over.

**Comment by jeff-phillips-18** [comment]
Rebased, removed WIP

**Comment by Hyperkid123** [comment]
@jeff-phillips-18 is it possible to include the close button to the modal Header? That would let us to customize the header completely.

Right now the button is the only thing that we cannot do anything about.

**Comment by jeff-phillips-18** [comment]
@Hyperkid123 Added the `showClose` prop, defaulted to true. Set to false to hide the close button.

**Pull request merged**
