### PR TITLE
fix(Label): editable label should have a tooltip

### LINKED ISSUE #6913: Label: Editable variant should have a tooltip when the label would cause an overflow

### PR DESCRIPTION
**Pull request by MariaAga**
**What**: Closes #6913

### CODE REVIEW

**Comment by MariaAga** [comment]
will look into failing tests, looks like the input html tag doesn't get input when focused with enter

**Comment by tlabaj** [comment]
@mcarrano do you think it is worth adding an example of the label with overflow.

**Review by mcarrano — APPROVED** [review]
@tlabaj this is probably OK as is. Looks like all label examples that have overflow text do expose a tooltip so it's implied as standard behavior. But if you think it would be clearer to call out a separate example, I'm OK with that, too.

**Review by nicolethoen — APPROVED** [review]

**Comment by nicolethoen** [comment]
@MariaAga once the conflicts are resolved, this should be good!

**Review by nicolethoen — APPROVED** [review]

**Review by thatblindgeye — APPROVED** [review]

**Pull request merged**
