### PR TITLE
fix(charts): ChartLegendTooltip shown with no data

### PR DESCRIPTION
**Pull request by dlabrecq**
The ChartLegendTooltip may be shown incorrectly when there is no visible data for a given coordinate.

In the "before" example below, all but one data series / legend item is active. When the user hovers over the chart, in an area with no visible data, only the tooltip title is shown because there is no data / legend labels to display here. The tooltip should not be shown at all for this scenario.

Fixes https://github.com/patternfly/patternfly-react/issues/5295

**Before**
before

**After**
after

### CODE REVIEW

**Review by ddonahue007 — DISMISSED** [review]
LGTM

**Comment by redallen** [comment]
Merge conflicts in `chart-tooltip.ts`.

**Comment by dlabrecq** [comment]
Fixed the merge conflict

**Review by redallen — APPROVED** [review]
Nice fix!

**Review by ddonahue007 — APPROVED** [review]
LGTM

**Pull request merged**
