### PR TITLE
feat(Toolbar): allow multiple toggle groups

### LINKED ISSUE #7590: Bug - ToolbarToggleGroup - Multiple ToolbarToggleGroups are not supported in the same toolbar
**Describe the problem**
If you include multiple ToolbarToggleGroup components in one Toolbar, all of the children of every ToolbarToggleGroup are displayed in the dropdown, even if they have different breakpoints

**How do you reproduce the problem?**
https://codesandbox.io/s/kind-night-e5mwfw

**Expected behavior**
Each ToolbarToggleGroup should only show its own children in the dropdown

**Is this issue blocking you?**
No.
Use other components like OverflowMenu to accomplish similar behavior

**Screenshots**
screencast-www patternfly org-2022 06 17-16_06_53

**What is your environment?**
 - OS: MacOS
 - Browser Chrome
 - Version 102.0.5005.115 (Official Build) (x86_64) 

**What is your product and what release date are you targeting?**
OpenShift admin console, no target release date

**Any other information?**
N/A

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #7590

First pass on multiple toggle groups.

Multiple toggle groups (and filter chip groups in different toggle groups) will work separately but currently share a container portal (as in toggling will add/subtract from the same container). I'm experimenting with replacing portal contents, or using separate portals. Unless a single portal will work, WDYT? @nicolethoen 

Overall the current approach requires manual management of the expanded state, and requires passing that expanded state logic to multiple components (`ToolbarContent`, `ToolbarToggleGroup`, `ToolbarFilter`) to bypass internal logic which only supports a single toggle group. There is a temp example up on the Toolbar doc page that I'll remove before merging which showcases it.

### CODE REVIEW

**Comment by nicolethoen** [comment]
When I had been experimenting with this once upon a time, I tried doing it with separate portals. I think it's generally promising, even though it does require manipulation of more pieces. 

When playing with your test example, I do notice that when I expand the filter group at a small screen width, then begin resizing the window to make it wide, the styles are not adjusting like I expect them to. I'm not sure if thats a side effect of the approach.

Jul-05-2023 08-48-28

**Comment by kmcfaul** [comment]
This second pass exposes `ToolbarExpandableContent` and uses multiple expandable groups to prevent new elements from being added/subtracted to the same popup. I've cleaned up the example to be clearer and added some comments about what is enabling the multiple toggle groups as well.

In summary, you need:
- separate expanded state handling and tracking for each toggle group (passed to each `ToolbarToggleGroup`)
- a `ToolbarExpandableContent` for each toggle group, collectively passed to `ToolbarContent` in a fragment
- refs for each expandable content (passed to each `ToolbarToggleGroup`) and expandable content chip group (passed to each `ToolbarFilter`). If the toggle groups don't contain a filter with chips then the second ref shouldn't be needed
- a resize observer to collapse toggle groups so they reformat properly as the window grows. I'm not sure yet why resizing while the popup is expanded results in odd formatting

Exposing `ToolbarExpandableContent` let chip groups be separated out as each group collapses, and allows the customization of the clear filter props per toggle group. However, the internal chip group container that is displayed for the full toolbar is still displaying all chip groups until its own collapse breakpoint is hit. Subtracting each chip group as each toggle group collapses would require more tinkering if we want to add that but should be doable (might have to pass the expanded state through to ToolbarFilter is my initial thought).

The other slight issue is there is a grey area between ~1000px and ~1200px where a toggle group does not expand as a popup menu but instead inline, but I think that's unrelated to the changes here. @mattnolting

**Comment by kmcfaul** [comment]
@nicolethoen How does this look for a solution with the new changes? If the approach looks good lmk and I'll take it out of draft. 

My other open question for all is whether we want to include the example I've created in the Toolbar docs.

**Comment by nicolethoen** [comment]
I wonder if instead of asking the consumer to define their own expandable content, if we can simply create it when they need it rather than having one preexisting whose ref we pass around for using in createPortals.

In that case we could take the children passed to the ToolbarToggleGroup and put them in an ExpandableContent component and place that ExpandableContent in a Popper? WDYT?

**Comment by kmcfaul** [comment]
I had experimented with putting the `ToolbarExpandableContent` inside the `ToolbarToggleGroup` but the layout/pop-out behavior wasn't working with the createPortal properly. That's why I went with the extra property in `ToolbarContent` so the DOM structure doesn't change and the expandable content looks the same. I can try with a Popper and see if it behaves better. 

A user would still need to pass the chip refs around even with an internal popper, because chips are controlled in the `ToolbarFilter`.

**Comment by nicolethoen** [comment]
idk if it helps - i have a SUPER old branch where I tinkered with this during a break away sprint. I think I removed the need for create portal.

I just made a draft PR so you can easily see the diff: https://github.com/patternfly/patternfly-react/pull/9349

**Comment by kmcfaul** [comment]
Take 3 with poppers.

The caveat is that the spacing is now different, because there is no top padding on the expandable content, and popper is appending directly after the toolbar (while the createPortal method looked like it was in line with a grid gap? Shown in all toggle examples but most noticeable in the stacked example as the divider line is being lost now). The weird zone between 1000-1200px also looks more squished as the pop up is losing padding.

The user doesn't have to manually create the ToolbarExpandableContent component with this setup, though they would still have to pipe a lot of those props through ToolbarToggleGroup.

**Comment by nicolethoen** [comment]
I like it better with less that the consumer has to wire up. 
Is there a way place the expandable content div inside the popper div? would that solve the spacing issue?

**Comment by kmcfaul** [comment]
The entire expandableContent is already given to Popper, or do you mean a different div?

If you mean the div where the popper is appending to, that is how the toggle group is appearing below the toolbar line (otherwise the expandable content would be inline with the trigger filter icon).

**Comment by nicolethoen** [comment]
I played with it a bit and was trying to figure out why the padding in the expandable content was being removd/overwritten. 
If it was more like
```
<div /** popper div */>
  <div className="pf-c-toolbar__expandable-content">
    ...
  </div>
<div>
```

rather than 
```
<div /** popper div */ className="pf-c-toolbar__expandable-content">
    ...
<div>
```

**Comment by kmcfaul** [comment]
@nicolethoen I tested wrapping the expandableContent in an additional div to separate out the styling from popper, but it appears something in the two sets of styles is still in conflict. The positioning of the popper also becomes inconsistent (sometimes it will attach to the top of the page instead and only a reload reverts that position).

https://github.com/patternfly/patternfly-react/assets/45077788/3b4a5acf-b7fa-4d25-a1bd-6441debad67d

**Comment by mattnolting** [comment]
@kmcfaul This is looking great!

Looks like we need to offset popper by the `gap` value 

Screenshot 2023-08-09 at 4 44 55 PM

Screenshot 2023-08-09 at 4 44 40 PM

**Comment by kmcfaul** [comment]
@mattnolting Would the gap class be a `pf-u-` class or something else?

**Comment by mattnolting** [comment]
> @mattnolting Would the gap class be a `pf-u-` class or something else?

@kmcfaul looks like you could either remove the inline styles popper is applying (which looks easiest and would avoid conflicting styles) or you could follow the core model

Screenshot 2023-08-14 at 12 37 16 PM

**Comment by mattnolting** [comment]
Looks like `pf-m-chip-container` isn't being applied to `pf-v-5-c-toolbar__content`, which throws alignment off a bit

Screenshot 2023-08-14 at 12 51 04 PM

Screenshot 2023-08-14 at 12 50 53 PM

**Review by mattnolting — APPROVED** [review]
LPTM! Fantastic work, @kmcfaul, love this enhancement 👍

**Comment by nicolethoen** [comment]
It's looking good! Do you see this behavior in the codesandbox?
It looks like the other controls are being hidden when I toggle open the toggle group?
toolbar

**Comment by kmcfaul** [comment]
@nicolethoen I'm not sure what's going on with the codesandbox on the preview - it looks like its not actually using the PR code for it. On the surge, you'll see that the expandable-content section doesn't exist when there's no open toggle group (whereas previously it would always exist, and still does on the codesandbox).

**Review by wise-king-sullyman — APPROVED** [review]
Looks great! I do think an integration test for this bug would be nice, as would unit tests for the new props, but I won't block over it.

**Review by nicolethoen — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]

**Review by andrew-ronaldson — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
