### PR TITLE
fix(SearchInput): hide clear button when onClear function is not set

### LINKED ISSUE #5229: SearchInput: hide the clear icon when user don't set onClear function
**Describe the issue. What is the expected and unexpected behavior?**
The SearchInput component will always show the `TimesIcon` as clear button to clear the search input value no matter whether user pass the `onClear` function or not. However, if users don't set the `onClear` function, it will not trigger any event when clicking on the clear button. So it's better to hide it when user don't set `onClear` function.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Enhancement.

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
**What**: Closes #5229

### CODE REVIEW

**Review by mcarrano — APPROVED** [review]
Looks good to me.

**Review by tlabaj — COMMENTED** [review]
can you had a test to verify.

**Comment by DaoDaoNoCode** [comment]
@tlabaj Will do, thank you.

**Review by tlabaj — APPROVED** [review]
lgtm

**Review by nicolethoen — APPROVED** [review]

**Pull request merged**
