### PR TITLE
feat(select): pass chip group props on typeaheadmulti variant

### LINKED ISSUE #4766: TypeAhead Multi Select should provide a way to pass props to the ChipGroup of its selections
I'm building a `<Select variant="typeaheadmulti">` and only 3 selections are shown as chips before the overflow controls appear. It would be great to be able to customize that by passing my own `numChips` prop to the `<ChipGroup>` rendered here: https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/components/Select/Select.tsx#L527

Perhaps an optional prop for `<Select>` called `chipGroupProps` could be made available that is only used if `variant === 'typeaheadmulti'`, and the chip group could be customized in other ways as well.

### PR DESCRIPTION
**Pull request by boaz0**
**What**: Closes #4766 

//cc @mturley

### CODE REVIEW

**Review by mturley — APPROVED** [review]
@boaz0 this is awesome! LGTM

**Review by mcarrano — APPROVED** [review]
This is a good enhancement. Thanks for adding this @boaz0 !

**Review by tlabaj — APPROVED** [review]
LGTM

**Comment by boaz0** [comment]
Thank you all!

**Pull request merged**
