### PR TITLE
fix(Menu): can navigate via keyboard for checkbox variant

### LINKED ISSUE #7382: [Menu] - [Make checkbox menu keyboard accessible]
**Is this a new component or an extension of an existing one?**
What is the existing component, if any?
Menu 

**Describe the feature**
A clear and concise description of the new feature. What is the expected behavior?
the checkbox menu is not accessible via keyboard.

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Closes #7382

[Menu with checkbox example](https://patternfly-react-pr-7743.surge.sh/components/menu#with-checkbox)
[Composable menu simple checkbox select](https://patternfly-react-pr-7743.surge.sh/demos/composable-menu#composable-simple-checkbox-select)

Updated the menu component logic as well as the composable menu with checkboxes demo

**Additional issues**:

### CODE REVIEW

**Review by kmcfaul — APPROVED** [review]
Looks good. 

Might be unrelated but it appears the composable drilldown example isn't getting set to the right height when you drill in on the surge. I'm not sure what might have changed for that to happen though, nothing in the PR looks like it should affect it. Maybe it's just an issue with the surge?

**Comment by thatblindgeye** [comment]
>Might be unrelated but it appears the composable drilldown example isn't getting set to the right height when you drill in on the surge. I'm not sure what might have changed for that to happen though, nothing in the PR looks like it should affect it. Maybe it's just an issue with the surge?

Yeah that is happening in the workspace as well. 

I know https://github.com/patternfly/patternfly/pull/4980 got merged 8 days ago, and https://github.com/patternfly/patternfly/pull/4892 got merged in Core last month. It doesn't look like this behavior started until maybe https://github.com/patternfly/patternfly-react/pull/7683 got merged in 7 days ago, though. Another possibility might be how the menu heights are getting calculated in that example, as updating `<MenuContent menuHeight=...` to a random 500px resolves that issue.

**Review by wise-king-sullyman — APPROVED** [review]
Seems like a great improvement!

**Review by nicolethoen — APPROVED** [review]
Keyboard and VO work well in both updated examples! :)

**Review by tlabaj — COMMENTED** [review]
@jessiehuff this seems to change the way we currently handle checkboxes in menu like components.  Do you mind taking a look.

**Comment by nicolethoen** [comment]
I did ask @thatblindgeye about it - it seems that MDN’s page on checkboxes only changes via Space and W3's authoring practices only lists space to toggle it, too

**Comment by thatblindgeye** [comment]
For context:

[Checkbox on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox)
[APG Checkbox pattern](https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/)

**Comment by jessiehuff** [comment]
> @jessiehuff this seems to change the way we currently handle checkboxes in menu like components. Do you mind taking a look.

Which interaction are you looking at by the way? I want to make sure that I'm seeing what you are. I tried to compare the interaction to the [keyboard interaction for menu-like components doc](https://docs.google.com/document/d/1m9nICFRgCXnXeHYN487BMX9MHw4DjvOln2B5p8yJa70/edit#heading=h.of6av3k68zqm) that Jenn and I put together a few years ago. I consider Tab as a main form of navigation between components and arrow keys within components, so I think this interaction would probably be fine? I tried to look at our other menu-like components, and I think the only one that probably differs is Select I think. I also consider space more commonly used for checkboxes, but Jenn and I have agreed before that Enter could also be fine at times.

**Comment by tlabaj** [comment]
> > @jessiehuff this seems to change the way we currently handle checkboxes in menu like components. Do you mind taking a look.
> 
> Which interaction are you looking at by the way? I want to make sure that I'm seeing what you are. I tried to compare the interaction to the [keyboard interaction for menu-like components doc](https://docs.google.com/document/d/1m9nICFRgCXnXeHYN487BMX9MHw4DjvOln2B5p8yJa70/edit#heading=h.of6av3k68zqm) that Jenn and I put together a few years ago. I consider Tab as a main form of navigation between components and arrow keys within components, so I think this interaction would probably be fine? I tried to look at our other menu-like components, and I think the only one that probably differs is Select I think. I also consider space more commonly used for checkboxes, but Jenn and I have agreed before that Enter could also be fine at times.

The interaction I am referring to is when I click enter, it does not check the checkbox in this PR.  I believe the select component selects the checkbox if you click enter.

**Review by jessiehuff — COMMENTED** [review]
So I think that surge is down since I can't load the previews anymore, but I think that in general, Space is more expected than Enter. I've seen it far more frequently and, as Nicole and Eric point out, most sources say to use Space. Actually our [checkbox component](https://www.patternfly.org/v4/components/checkbox) also uses Space. I think originally we planned on updating Select's keyboard navigation based on [the epic](https://github.com/patternfly/patternfly-react/issues/3108) I created awhile back, but I think the new plan is that the refactor would eventually iron out all of the interaction patterns and make them consistent.

**Review by tlabaj — APPROVED** [review]

**Pull request merged**
