### PR TITLE
fix typos 

### PR DESCRIPTION
**Pull request by tanvisau**
Fix typos

towards #4501

### CODE REVIEW

**Comment by tlabaj** [comment]
Can you link the issue in the description  please. Thanks

**Comment by tanvisau** [comment]
> Can you link the issue in the description please. Thanks

Thanks for the review.
I've linked it.

**Comment by ljmotta** [comment]
Hi @tanvisau ! I saw that you linked my issue on this PR, but I'm not sure if it was a mistake? My issue is a type problem :no_mouth:

**Comment by tlabaj** [comment]
@jenny-s51 There is already a pr up for that change #4560
@tanvisau can you link to issue #4501 or open a new issue for this PR please.

**Pull request merged**
