### PR TITLE
feat(toggleGroup): add suport to text + icon

### LINKED ISSUE #4716: Toggle group - support for text + icon
https://github.com/patternfly/patternfly/pull/3373

### PR DESCRIPTION
**Pull request by boaz0**
**What**: Closes #4716 

I am still not sure whether the text can be passed through the `children` or the `text` props.

WDYT?

//cc @mcoker

### CODE REVIEW

**Review by nicolethoen — APPROVED** [review]
LGTM - at first i could not decide if the extra ToggleGroupItemElement was necessary - it probably isn't. But, since none of it is exposed to the user, any changes to the ToggleGroupItemElement wont be breaking, so I guess it just lets us flesh out tests better to have it.

**Comment by mcoker** [comment]
> I am still not sure whether the text can be passed through the children or the text props.

@boaz0 what you have works, but if I'm reading it right, we could set it up like a button and keep the `variant === ToggleGroupItemVariant.icon` prop to indicate it's an icon/plain button and wrap `children` in the `.pf-c-toggle-grup__icon` element.

If it's not the icon variant, the check for an `icon` prop for the icon source and `iconPosition` prop for whether to put the icon before or after the text.

**Review by mcarrano — APPROVED** [review]
Looks good to me.

**Review by dlabrecq — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]

**Comment by boaz0** [comment]
@nicolethoen 

> at first i could not decide if the extra ToggleGroupItemElement was necessary - it probably isn't. But, since none of it is exposed to the user, any changes to the ToggleGroupItemElement wont be breaking, so I guess it just lets us flesh out tests better to have it.

Yes, definitely I am not happy with adding `ToggleGroupItemElement`. Maybe we can think of a better way to do it.
I think @mcoker 's idea will fix that. WDYT?

@mcoker thanks for the feedback.

> we could set it up like a button and keep the variant === ToggleGroupItemVariant.icon prop to indicate it's an icon/plain button and wrap children in the .pf-c-toggle-grup__icon element.
> If it's not the icon variant, the check for an icon prop for the icon source and iconPosition prop for whether to put the icon before or after the text and the text is what's passed as children

That's actually a good idea. Although the only disadvantage that I can think of is that it is less trivial than what we have now.

@dlabrecq  @tlabaj  and @nicolethoen

**Review by redallen — APPROVED** [review]
LGTM. Do you want this merged @boaz0 and @mcoker ?

**Comment by redallen** [comment]
Merging. Feel free to use this thread to discuss further.

**Comment by boaz0** [comment]
@mcoker do you want to discuss about it through email or slack?

**Pull request merged**
