### PR TITLE
feat(yarn): Manage dependencies using Yarn

### LINKED ISSUE #33: There are several eslint errors in master
Running npm test in master results in the following:

```
/Users/walden/work/patternfly-react/src/Alert/Alert.stories.js
  12:23  error  Insert `⏎·····`                                                                                                                                    prettier/prettier
  16:21  error  Replace `⏎··'with·danger',⏎··`This·is·the·Alert·with·danger·type.`,⏎··()·=>·(` with `'with·danger',·`This·is·the·Alert·with·danger·type.`,·()·=>`  prettier/prettier
  20:1   error  Delete `··`                                                                                                                                        prettier/prettier
  21:1   error  Replace `······` with `····`                                                                                                                       prettier/prettier
  22:3   error  Delete `··`                                                                                                                                        prettier/prettier
  23:1   error  Delete `··)⏎`                                                                                                                                      prettier/prettier
  29:8   error  Delete `·(`                                                                                                                                        prettier/prettier
  38:1   error  Delete `··)⏎`                                                                                                                                      prettier/prettier
  41:76  error  Delete `·(`                                                                                                                                        prettier/prettier
  50:2   error  Delete `)`                                                                                                                                         prettier/prettier
  55:8   error  Delete `·(`                                                                                                                                        prettier/prettier
  64:1   error  Delete `··)⏎`                                                                                                                                      prettier/prettier
  70:8   error  Delete `·(`                                                                                                                                        prettier/prettier
  78:13  error  Delete `⏎··)`                                                                                                                                      prettier/prettier

/Users/walden/work/patternfly-react/storybook/decorators/storyTemplates.js
   3:50  error  Delete `·(`  prettier/prettier
  35:1   error  Delete `)⏎`  prettier/prettier

✖ 16 problems (16 errors, 0 warnings)
```

### PR DESCRIPTION
**Pull request by jtomasek**
* Add yarn.lock and update travis to use Yarn
* fix prettier issues using prettier 1.4.2

Yarn is a package manager which works on top of npm. It takes care
of pinning the dependencies (maintained in yarn.lock file) and
ensures that all consumers (ci, developers) share the same environment

Usage Docs:
https://yarnpkg.com/en/docs/usage
https://yarnpkg.com/lang/en/docs/migrating-from-npm/

Closes #33

### CODE REVIEW

**Comment by priley86** [comment]
Thanks for putting this together @jtomasek. I'm happy to move to yarn as it seems a React standard these days.

**Comment by priley86** [comment]
@jtomasek can you provide any further input on the direction you see the yarn project going before we merge this? It certainly helps that this is sponsored by Facebook and is the recommendation there.

It seems to match up quite closely with npm v5 feature wise (offline-cache, hoisted depenendencies, etc.). Any commentary on this before we decide to go w/ Yarn instead of npm v5?
https://yarnpkg.com/blog/2017/05/31/determinism/

**Comment by bleathem** [comment]
Is this PR moreso about enabling yarn (via inclusion of the _yarn.lock_ file) rather than favoring it over npm?  It would seem to me that one still has the option of installing the project dependencies with either tool.

**Comment by jtomasek** [comment]
So it seems that npm5 brings equivalent features to what Yarn is doing. (mainly with its proper package-lock.json lock file). In that case, I'd prefer using npm5 and avoid introducing Yarn as another dependency as by switching to use Yarn, it is required that it is used by build and developers to ensure the correct versions of dependencies.

On the other hand, npm5 is included only in latest version of node (v8) which is not LTS but I am not sure how much it is a problem for patternfly-react. It is probably not.

Question is whether travis and other build/publishing tools we use are capable of working with npm5's package-lock.json. I can create another PR which introduces package-lock.json to test it.

In any case. Since patternfly-reacty is not going to have huge dependency tree, switching between dependency management tools should be fairly simple.

What others think?

**Comment by priley86** [comment]
we've gone w/ npm5 for now (see #38). We'll continue to monitor the Yarn project, but npm5 provides the functionality we need for now.

**Pull request closed without merging**
