### PR TITLE
chore(table): update expandable table data

### LINKED ISSUE #7685: Table: Update expandable demo data
- [ ] Convert table data to new data as per design: https://docs.google.com/spreadsheets/d/1-sqIbCpmFfmID0fByWZSOBpn99ocGyT2KoUZ5B_s3zo/edit#gid=0

### PR DESCRIPTION
**Pull request by jenny-s51**
**What**: Closes #7685 , towards #7384, follows investigation done in #7795 

- introduces a set of hardcoded table data to use for the rest of the demos.
- updates the expandable demo data to align with the new data

The expandable table data **must remain hardcoded in the md file** because **the consumer needs to specify the data that  is in the expandable section.**

Because the data is hardcoded here, we cannot paginate this without puffing up the demo with data and pagination logic, therefore pagination cannot be supported in this demo.

Link to expandable demo for convenience: https://patternfly-react-pr-7838.surge.sh/components/table/react-demos/expandcollapse-all/

### CODE REVIEW

**Review by nicolethoen — COMMENTED** [review]
Not too long ago, the table and table composable examples were refactored so that the table data was structured to look more like it was coming from an API and the data was not stored in the example's state. I'm wondering if this is a good thing to also do with this new data set in the demos. If you want to walk through more of what I mean, let me know! Even the most basic table composable example demonstrates what i'm talking about.

**Comment by jenny-s51** [comment]
@nicolethoen this is a great idea - looking at the syntax in the Basic Table Composable demo:
```
  // In real usage, this data would come from some external source like an API via props.
  const repositories: Repository[] = [
    { name: 'one', branches: 'two', prs: 'three', workspaces: 'four', lastCommit: 'five' },
    { name: 'one - 2', branches: null, prs: null, workspaces: 'four - 2', lastCommit: 'five - 2' },
    { name: 'one - 3', branches: 'two - 3', prs: 'three - 3', workspaces: 'four - 3', lastCommit: 'five - 3' }
  ];
```

This would be a great standard to follow for other demos and I think we definitely should try to take data out of the state and apply this approach where we can. 

For this expandable demo specifically, it looks like the data _would_ need to remain in the state, since the `isExpanded` behavior is directly related to the `isOpen` attribute in `this.state.rows`, which gets updated in the state by the `onCollapse` function. WDYT @nicolethoen ?

**Comment by mcarrano** [comment]
@jenny-s51 can you point me to what's changed and what exactly I should be reviewing from a UX perspective? Thanks.

**Review by jenny-s51 — COMMENTED** [review]
@mcarrano The react demo was updated to use the recently updated table data from https://docs.google.com/spreadsheets/d/1-sqIbCpmFfmID0fByWZSOBpn99ocGyT2KoUZ5B_s3zo/edit#gid=0 as part of https://github.com/patternfly/patternfly-design/issues/1157.

Here is the existing core demo: https://pf4.patternfly.org/components/table/html-demos/expandable/

And the updated react demo: https://patternfly-react-pr-7838.surge.sh/components/table/react-demos/expandcollapse-all/

**Comment by nicolethoen** [comment]
@jenny-s51 it shouldn't be necessary to couple the isExpanded behavior with the data coming from the API. You'd probably want to handle it like the [expandable example](https://www.patternfly.org/v4/components/table/react-legacy#expandable) does where it maintains an array of `expandedRepoNames` (line 80 in the example code) and uses that information on line 106 when it's constructing the `rows` object to pass to the Table.

**Review by mcarrano — COMMENTED** [review]
@jenny-s51 I think this looks good. One of the ideas we talked about was maybe using labels to represent status just to give examples of how to add an element other than text in a table cell. How easy or hard would that be to do? It's sort of a nice to have, but would be good to add if we can. Or we can follow up at a later date. @mmenestr what are your thoughts?

**Review by jenny-s51 — COMMENTED** [review]
**WIP - marking this PR a draft until I fix the padding on the expandable content and a few other remaining visual things. Will open for review once those are addressed**

> You'd probably want to handle it like the [expandable example](https://www.patternfly.org/v4/components/table/react-legacy#expandable) does where it maintains an array of expandedRepoNames (line 80 in the example code) and uses that information on line 106 when it's constructing the rows object to pass to the Table.

Thanks for suggesting this approach @nicolethoen ! I've updated the code in the [expandable demo file](https://github.com/patternfly/patternfly-react/pull/7838/files#diff-56c4a25c87e6a4bd8c41fc91583297cb6d03804cef16afc1784fab106a0f66aa) to implement the expandable rows per your comment! I've addressed your feedback regarding https://github.com/patternfly/patternfly-react/pull/7857#discussion_r949164066 as well and removed lodash from the data file. 

> One of the ideas we talked about was maybe using labels to represent status just to give examples of how to add an element other than text in a table cell. How easy or hard would that be to do? It's sort of a nice to have, but would be good to add if we can. Or we can follow up at a later date. @mmenestr what are your thoughts?

This is a great idea @mcarrano - I've updated the demo to represent the status cells using labels, [following the mock you linked](https://marvelapp.com/prototype/2ff7ahj6/screen/87992956). @mcarrano @mmenestr please share your thoughts when you get a chance 🙂

**Comment by jenny-s51** [comment]
Still WIP - marking as draft until I fix the padding on the expandable content and a few other remaining visual things

**Review by tlabaj — APPROVED** [review]
LGTM!

**Review by nicolethoen — APPROVED** [review]

**Pull request merged**
