### PR TITLE
chore(Accordion, ExpandableSection, DescriptionList): update displaySize prop values

### LINKED ISSUE #8098: [Accordion, DescriptionList, Expandable Section ] - [Make displaySize prop consistent]
**Describe the problem**
Accordion, DescriptionList, Expandable Section  all have display size props and the are not defined consistently.

Accordion and Expandable section have:
  `displaySize?: 'default' | 'large';`

DescriptionList has
`displaySize?: 'lg' | '2xl';`

I propose we change them to follow closely to how we name other size variants

Accordion and Expandable section have:
  `displaySize?: 'default' | 'lg';`
and 
DescriptionList:
`displaySize?: 'default' | 'lg' | '2xl';`

### PR DESCRIPTION
**Pull request by jenny-s51**
**What**: Closes #8098

### CODE REVIEW

**Review by thatblindgeye — COMMENTED** [review]
This looks good! 

Regarding the DescriptionList examples, since we're updating the amount of possible `displaySize` options from 2 to 3, it would be worth updating the "Description list with display size and card" and "Display size" examples, as those are using a checkbox to essentially toggle between 2 display sizes.

The easiest way would be an example description that mentions the three options for `displaySize`, and that the example allows toggling a checkbox to swap between 2 of those 3. Another option would be updating the examples so that all 3 displaySize options can be chosen (either via radio buttons or select menu).

@jenny-s51 wdyt?

**Review by jenny-s51 — COMMENTED** [review]
Thank you @thatblindgeye @tlabaj for those great points! We could definitely use some more clarity on those examples.

I've renamed the "Display size" examples to "Large display size", and "Large display size with card" size since they both already had had `displaySize="lg"` set by default.

**Review by mcoker — APPROVED** [review]
LGTM! I'll just mention we should still look at these and button, card, and tile, and have consistency with the prop names/values for things that offer a "display" size. Here's the core issue for that https://github.com/patternfly/patternfly/issues/5155

**Review by tlabaj — APPROVED** [review]
LGTM!

**Pull request merged**
