### PR TITLE
test(code-coverage): Add code-coverage reports

### PR DESCRIPTION
**Pull request by sharvit**
**What**:
* Configure jest to generate code-coverage
* Configure Travis to publish code-coverage to coveralls.io

### CODE REVIEW

**Comment by sharvit** [comment]
I am surprised it just works with the first commit :+1: 

Recommend to install their plugin on you chrome so you will have some helpers inside github:
https://chrome.google.com/webstore/detail/coveralls/plmnloljehipkinecpeoehdnkjhbmcjc

:+1: / :-1:  ?

**Comment by priley86** [comment]
@sharvit i love it. Looks like we are sitting around 80% coverage (not as bad I thought 😄). Would be great to get 100%.

After running the following:
```
npm run test
npm run coveralls
```
I get following indicating that coveralls needs to be enabled:
```
| => npm run coveralls

> patternfly-react@0.0.0-semantically-released coveralls /Users/priley/GitHub/patternfly-react
> cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js


/Users/priley/GitHub/patternfly-react/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
```

The coverage reports print nicely in `/coverage` though.

@jeff-phillips-18 would you like to enable [Coveralls](https://github.com/marketplace/coveralls) for this repo? I think the badge indicating our  current test coverage would be excellent.

**Comment by sharvit** [comment]
@priley86 You actually shouldn't run it locally, in order to do so, you will need to set up some secret-key.

Somehow, Travis, Github, and Coveralls linked together like some kind of weird voodoo.

I already enabled it and the publishing worked:
https://coveralls.io/github/patternfly/patternfly-react

I think you missed that:
test code coverage add code coverage reports by sharvit pull request 202 patternfly patternfly react

**Comment by jeff-phillips-18** [comment]
Yeah, I think enabling coveralls would be great.

**Comment by priley86** [comment]
@sharvit great - so we don't need to enable any github apps before merging this?

**Comment by priley86** [comment]
@sharvit looks like you need a rebase now ;)

**Comment by sharvit** [comment]
Rebased! thanks @priley86 @jeff-phillips-18 :+1:

**Pull request merged**
