### PR TITLE
feat(TableText): allow passing tooltipProps

### LINKED ISSUE #5658: Allow `entryDelay` on TableText
Design has requested to stop tooltips from TableText instantly appearing:
tooltip

### PR DESCRIPTION
**Pull request by redallen**
**What**: Allows greater tooltip customization needed for @mmenestr. Closes #5658

**Additional issues**:

### CODE REVIEW

**Comment by tlabaj** [comment]
Hi @redallen.  Is there an associated issue?

**Comment by redallen** [comment]
Hi @tlabaj I opened an issue.

**Review by kmcfaul — DISMISSED** [review]

**Review by tlabaj — COMMENTED** [review]
can you add a test for this?

**Review by mcarrano — CHANGES_REQUESTED** [review]
This is a great feature to add @redallen . My only ask is that can we change the text in the example to call out that the delay is in milliseconds (e.g. Entry delay(ms)), This tripped me up until I went and read the documentation for the prop.

@mmenestr I definitely like having a delay. Do we want to add this to our design recommendations?

**Comment by redallen** [comment]
@tlabaj What kind of test do you want for this?

@mcarrano How do you want that called out in which examples?

**Comment by mcarrano** [comment]
@redallen I was just referring to updating the text labels on the Options example here:

Screen Shot 2021-04-13 at 2 10 33 PM

**Comment by mmenestr** [comment]
Good idea @mcarrano just created this issue: https://app.zenhub.com/workspaces/design-doc-workspace-5f08c64d6a6ef2001d56a458/issues/patternfly/patternfly-org/2450

**Review by kmcfaul — APPROVED** [review]

**Review by dlabrecq — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]

**Pull request merged**
