### PR TITLE
Chore: add primary button with icon to button docs

### PR DESCRIPTION
**Pull request by nicolethoen**
Closes: https://github.com/patternfly/patternfly-react/issues/9870

### CODE REVIEW

**Comment by tlabaj** [comment]
Semantically this is a chore and not a feature

**Review by thatblindgeye — APPROVED** [review]

**Review by andrew-ronaldson — APPROVED** [review]
LGTM, thanks

**Comment by andrew-ronaldson** [comment]
Do we support icons in other buttons and not just primary like in the example?

**Comment by nicolethoen** [comment]
@andrew-ronaldson they can be on any button

**Review by tlabaj — APPROVED** [review]

**Pull request merged**
