### PR TITLE
fix(Nav): horizontalsubnav aria label default to Local

### LINKED ISSUE #7664: Horizontal subnav - aria-label should be "Local"
https://github.com/patternfly/patternfly-react/blob/2c24a2544447431362f699359ef2ef840b095db6/packages/react-core/src/components/Nav/Nav.tsx#L162

Horizontal subnav replaced tertiary nav, so seems like it should use "Local", too? That's how it is in the core examples:
* https://www.patternfly.org/v4/components/navigation/html#horizontal-subnav
* https://www.patternfly.org/v4/components/navigation/html-demos#horizontal-subnav

### PR DESCRIPTION
**Pull request by gitdallas**
**What**: Closes #7664

### CODE REVIEW

**Review by tlabaj — APPROVED** [review]
LGTM

**Review by thatblindgeye — APPROVED** [review]
@mcoker for the HTML examples, shouldn't the [horizontal subnav overflow](https://www.patternfly.org/v4/components/navigation/html/#horizontal-subnav-overflow) example have the aria-label updated to "Local"?

**Comment by mcoker** [comment]
@thatblindgeye yep, good catch!

**Review by mcoker — APPROVED** [review]
lgtm! 🚀

**Comment by thatblindgeye** [comment]
@mcoker reversing the "good catch" back to you! It'd be worth updating those instances of "global" as well.

In regards to the custom aria-label, using the custom labels rather than only "global" or "local" would provide better context for the examples when announced on their own, but would also provide better context in Voice Over's rotor menu. Currently for the HTML page, the rotor menu lists the nav elements with their aria-label in the "Landmarks" section, so it displays a bunch of "Global navigation" and "Local navigation":

https://user-images.githubusercontent.com/70952936/195656345-38c37a1e-0380-446f-8c6e-afa4c9b49802.mov

And I would agree with removing the "nav" part of the aria-label since it would be a little redundant with "navigation" being announced due to the nav element.

**Comment by gitdallas** [comment]
@mcoker @thatblindgeye - okay? https://github.com/patternfly/patternfly-react/pull/8213/commits/8dc70d239f39eb5baa9be215ad2741989c398828

**Review by thatblindgeye — APPROVED** [review]
Looks great! Thanks for making the additional updates

**Comment by mcoker** [comment]
@gitdallas nice! I was going to open a separate issue for that - thanks for taking care of it!

**Pull request merged**
