### PR TITLE
feat(Tabs) Added support for expandable vertical tabs

### LINKED ISSUE #5520: Expandable vertical tabs
https://github.com/patternfly/patternfly/pull/3836/

Adds  3 variations
* `.pf-m-expandable` - This applies to the vertical variation and can be applied at different breakpoints via `.pf-m-expandable-on[breakpoint]`
* `.pf-m-non-expandable` can be used to go back to regular vartical tabs via something like `.pf-m-expandable.pf-m-non-expandable-on-lg` to make vertical tabs expandable by default, and non-expandable on large viewports.
* `.pf-m-expanded` - applies to `.pf-m-expandable` for the expanded state.

Also adds a new `.pf-c-tabs__toggle` element with a button and toggle text in it that comes before the `.pf-c-tabs__list` when tabs are set to expandable.

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #5520 
Closes: #6360 

this replaces the now closed PR #5520.  Please see the original PR for comments.

### CODE REVIEW

**Review by mcarrano — APPROVED** [review]
Looks good to me!

**Review by jessiehuff — COMMENTED** [review]
It's still a bit odd that the scroll left/right buttons are reachable by keyboard and screen reader, but they're completely hidden visually. They also don't do anything so a screen reader user who can hear what they're called might be confused if they try to use it. Maybe we can add `aria-hidden="true"` and `disabled` whenever it's visually hidden?

**Comment by tlabaj** [comment]
@jessiehuff I opened issue #6360. for vertical tabs and resolved it in this PR.

**Review by jessiehuff — COMMENTED** [review]
Is the preview not updating? I still don't see the changes with `disabled` and `aria-hidden="true"`.

**Review by jessiehuff — APPROVED** [review]
LGTM! :)

**Review by mcoker — APPROVED** [review]
LGTM!

**Review by jessiehuff — APPROVED** [review]

**Review by kmcfaul — APPROVED** [review]
lgtm

**Review by dlabrecq — APPROVED** [review]

**Pull request merged**
