### PR TITLE
fix(Tabs): Handle activeKey props update with mountOnEnter on Tabs

### LINKED ISSUE #4805: Tabs with mountOnEnter are not always correctly updated
When tabs are used with `mountOnEnter`, they will not be correctly updated when the `activeKey` is changed from props, resulting in an empty (unmounted) content. This happens when tabs selection is done programatically by changing props.

(I will open a PR ; basically I think just a `componentDidUpdate` function is missing there)

### PR DESCRIPTION
**Pull request by jotak**
The "shownKeys" state array needs to be updated on props changed

Fixes #4805

### CODE REVIEW

**Comment by jotak** [comment]
PS: here's a code sandbox to illustrate the problem: https://codesandbox.io/s/stoic-oskar-7tn9o?file=/index.js

Clicking on the button would navigate to tab 2, but without showing its content.

**Review by jschuler — APPROVED** [review]
LGTM, thanks @jotak !

**Comment by jotak** [comment]
Thanks @jschuler,
By the way, is there a chance to get it backported to 3.x branch? We're using patternfly in Kiali, currently on 3.153.3, we can certainly do a minor bump without a problem, but major bump is another thing. (And this bug is annoying to us).

**Review by redallen — APPROVED** [review]

**Comment by redallen** [comment]
@jotak I'll backport this for you.

**Comment by redallen** [comment]
@jotak 
```
 - @patternfly/react-catalog-view-extension => 1.4.69
 - @patternfly/react-core => 3.158.4
 - @patternfly/react-inline-edit-extension => 2.17.70
 - @patternfly/react-table => 2.28.51
 - @patternfly/react-topology => 2.14.69
 - @patternfly/react-virtualized-extension => 1.4.70
```

**Comment by jotak** [comment]
Thanks @redallen !

**Pull request merged**
