### PR TITLE
fix(beta): promote components + features out of beta for v5

### LINKED ISSUE #8536: remove beta tags for v5
Banner (html)
Charts: Patterns
Date picker
Description list (html)
Dropdown: bulk select loading state
Dropdown - next
Helper text demo (html)
Icon
LoginPage: header utilities
MenuItem: hasCheck
Page demos (html)
Password strength demo (html)
Progress stepper
removeFindDomNode
SearchInput
Select next
Select: isCreateSelectOptionObject
Select: loadingVariant
Select: isInputFilterPersisted
Tabs: dynamic
Tabs: horizontal overflow
Tabs: actions
Tabs: close button props
Text area: icon sprite
Text input group
Tile
Truncate
Wizard next

### PR DESCRIPTION
**Pull request by nicolethoen**
**What**: Closes #8536

promotes:
Charts: Patterns
 Date picker
 Dropdown: bulk select loading state
 Dropdown - next
 Icon
 LoginPage: header utilities
 MenuItem: hasCheck
 Multiple file upload with helper text
 Progress stepper
 Progress helper text
 removeFindDomNode
 SearchInput
 Select next
 Select: isCreateSelectOptionObject
 Select: loadingVariant
 Select: isInputFilterPersisted
 Tabs: dynamic
 Tabs: horizontal overflow
 Tabs: actions
 Tabs: close button props
 Text area: icon sprite
 Text input group
 Tile
 Truncate
 Wizard next

Components/features still in beta after v5: https://docs.google.com/spreadsheets/d/17aEfvG1DZ0dZmpwacYaCzKv4sog0LuatXCwNizJ7HhE/edit#gid=1239116046

### CODE REVIEW

**Review by mcarrano — COMMENTED** [review]
I think this looks OK, but there were a few things I was missing as I reviewed the file updates so will defer to @tlabaj . Specifically, I didn't find updates that referenced:

- LoginPage
- removeFindDomNode

Also wasn't sure about all the Select changes, but I will admit to not being sure what I was looking for. But otherwise this looks good.

**Comment by tlabaj** [comment]
> I think this looks OK, but there were a few things I was missing as I reviewed the file updates so will defer to @tlabaj . Specifically, I didn't find updates that referenced:
> 
> * LoginPage
> * removeFindDomNode
`removeFindDomNode` was removed for v5 so should not be on this list
it looks like "Login Page header utilities was promoted already.
For select, Nicole promoted Next select.  She also promoted an. beta features in the deprecated select.

**Review by kmcfaul — APPROVED** [review]

**Review by wise-king-sullyman — APPROVED** [review]

**Review by mcarrano — APPROVED** [review]
Looks good to me!

**Review by tlabaj — APPROVED** [review]
LGTM

**Pull request merged**
