### PR TITLE
feat(Dropdown): Added simple template

### LINKED ISSUE #10303: Add basic dropdown template

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Closes #10303

**Additional issues**:

### CODE REVIEW

**Review by wise-king-sullyman — APPROVED** [review]
Would love to see tests for the `isToggleFullWidth` and `shouldFocusToggleOnSelect` props added but I won't block for that. This is great 🚀

**Review by wise-king-sullyman — APPROVED** [review]
🎸

**Review by kmcfaul — APPROVED** [review]
LGTM

For the name - we started with SelectSimple, but we moved to CheckboxSelect/TypeaheadSelect for other templates. I was wondering if we overall wanted to keep the {X}Simple naming pattern for the basic Select/Dropdown templates, or rename them to Simple{X} or just {X} as the import path is different?

**Comment by thatblindgeye** [comment]
@kmcfaul I kind of want to suggest "[X]Template[template type]", but depending on how many we actually end up with over time that could get verbose. SelectTemplateSimple, SelectTemplateTypeahead, SelectTemplateMultiTypeahead... Maybe something like that would work better if the API was more `<SelectTemplate template="simple" ...otherProps />` or something (not suggesting that for an API, though).

At the very least I think there should be some quantifier attached to the component name. Even though the import path is different, and a consumer could differentiate the import names if they're using both composable and template Select, could just make it easier to outright name them differently.

I've probably gotten used to having the component name start names from our examples/demos, e.g. `examples/SelectBasic.tsx` etc., so would probably lean towards `[Component][Template type]` for the template naming. Not sure how strongly I really feel about that, though.

**Review by tlabaj — APPROVED** [review]
LGTM

**Pull request merged**
