### PR TITLE
chore(Page) remove deprecated props

### LINKED ISSUE #8091: [Page] - [remove deprecated props]
**Describe the problem**
Remove the deprecated props in the following Page subcomponents:

- PageBreadcrumb: `sticky`
- PageGroup: `sticky`
- PageNavigation: `sticky`
- PageSection: `sticky`

### PR DESCRIPTION
**Pull request by Dominik-Petrik**
**What**: Closes #8091

### CODE REVIEW

**Review by tlabaj — APPROVED** [review]
LGTM

**Review by thatblindgeye — COMMENTED** [review]
This is looking good! Had a couple of questions which @tlabaj may be able to weigh in on:

1. The snapshots look to have been updated where the `pf-m-sticky-[top/bottom]` class is removed, and a `sticky` attribute is instead added. Should the `pf-m-sticky` class not still be applied in the snapshots?
2. In the PageHeader component, the `isManagedSidebar` prop description mentions "This prop is no longer managed through PageHeader but in the Page component", and the prop is also given the alias of `deprecatedIsManagedSidebar` on line 46. Would we want to remove this prop as well or add a proper `@deprecated` in the description?

**Comment by tlabaj** [comment]
> This is looking good! Had a couple of questions which @tlabaj may be able to weigh in on:
> 
> 1. The snapshots look to have been updated where the `pf-m-sticky-[top/bottom]` class is removed, and a `sticky` attribute is instead added. Should the `pf-m-sticky` class not still be applied in the snapshots?
> 2. In the PageHeader component, the `isManagedSidebar` prop description mentions "This prop is no longer managed through PageHeader but in the Page component", and the prop is also given the alias of `deprecatedIsManagedSidebar` on line 46. Would we want to remove this prop as well or add a proper `@deprecated` in the description?

@thatblindgeye is correct.  
1. It should still be  `pf-m-sticky-[top/bottom]` for the modifier.
2. We should removed the isManagedSidebar prop and the associated generated console warning.

**Review by tlabaj — CHANGES_REQUESTED** [review]
Please address @thatblindgeye comments

**Pull request closed without merging**
