### PR TITLE
feat(CodeEditor): improve type-safety for onChange prop

### LINKED ISSUE #6537: Change event type for CodeEditor is not complete
The type for the `onChange` prop of the CodeEditor component is not complete. The value is not optional and the event is typed as `any`.

### PR DESCRIPTION
**Pull request by jonkoops**
Closes #6537

### CODE REVIEW

**Review by nicolethoen — APPROVED** [review]

**Comment by jonkoops** [comment]
Closes #6537

**Review by kmcfaul — APPROVED** [review]

**Review by dlabrecq — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]

**Comment by tlabaj** [comment]
please link associated issue for tracking

**Comment by jonkoops** [comment]
@tlabaj See my comment above. I do not have permissions to link issues or merge PRs.

**Comment by nicolethoen** [comment]
@jonkoops I linked it for you! :) Thanks for making it!

**Comment by jonkoops** [comment]
Thanks!

**Pull request merged**
