### PR TITLE
docs(EmptyState): add example to set icon size

### LINKED ISSUE #1434: PF4 Empty State Icon: Allow size to be set
The Cost Management UI needs to provide an empty state in a table, per Kyle's high fidelity mock below. However, it appears that the empty state icon component does not allow me to set the size?

Also, the empty state icon component is undocumented in the PF4 examples.

This icon appears to be too large and does not match the size shown in Kyle's high fidelity mock.

screen shot 2019-02-22 at 4 27 49 pm

Kyle's Mock:
screen shot 2019-02-22 at 2 58 34 pm

### PR DESCRIPTION
**Pull request by boaz0**
**What**:

closes #1434

Added an example of how to set the icon size through `EmptyStateIcon`.

In general, `EmptyStateIcon` also has `color` and `title` props that set the icon color and title.

### CODE REVIEW

**Comment by tlabaj** [comment]
@christiemolloy We don't have an example in core that matches this.  Is it worth adding? Or maybe we   If so, I can add an issue in core.  The example is useful for the consumer.

**Comment by tlabaj** [comment]
@redallen This one did not deploy a preview.

**Comment by redallen** [comment]
CircleCI is pretty inconsistent building the Patternfly-4 docs, it's on my backlog of things to look into. In the future, just click "Rerun workflow" in CircleCI (I just [kicked it off again](https://circleci.com/gh/patternfly/patternfly-react/248) for you).

**Comment by tlabaj** [comment]
@christiemolloy Thanks for the feedback!

**Comment by tlabaj** [comment]
Closing this PR since the example is not consistent with core and the Empty state Icon should not be resized.

**Pull request closed without merging**
