### PR TITLE
feat(Slider): Added touch support

### LINKED ISSUE #5363: Add touch interactions to the Slider
The Slider should support touch interactions when used on a mobile device.

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #5363 

**Additional issues**:

### CODE REVIEW

**Review by kmcfaul — APPROVED** [review]
LGTM and works on my touch device

**Comment by nicolethoen** [comment]
I'm seeing the same issue here where the touchmove event is still bubbling up, so if someone drags left or right they may accidentally force the browser 'back' functionality and navigate off the page.

I solved this on the drawer by using `e.stopImmediatePropagation` seen here: https://github.com/nicolethoen/patternfly-react/blob/a03ba01c0788641bda753feb8c3049cf7bb61043/packages/react-core/src/components/Drawer/DrawerPanelContent.tsx#L93

and by making the handler passive, seen here: https://github.com/nicolethoen/patternfly-react/blob/a03ba01c0788641bda753feb8c3049cf7bb61043/packages/react-core/src/components/Drawer/DrawerPanelContent.tsx#L71

**Comment by tlabaj** [comment]
> I'm seeing the same issue here where the touchmove event is still bubbling up, so if someone drags left or right they may accidentally force the browser 'back' functionality and navigate off the page.
> 
> I solved this on the drawer by using `e.stopImmediatePropagation` seen here: https://github.com/nicolethoen/patternfly-react/blob/a03ba01c0788641bda753feb8c3049cf7bb61043/packages/react-core/src/components/Drawer/DrawerPanelContent.tsx#L93
> 
> and by making the handler passive, seen here: https://github.com/nicolethoen/patternfly-react/blob/a03ba01c0788641bda753feb8c3049cf7bb61043/packages/react-core/src/components/Drawer/DrawerPanelContent.tsx#L71

thanks @nicolethoen.  I will investigate.

**Review by mcarrano — COMMENTED** [review]
Testing this on my Android phone, I had a really hard time making the slider drag work. I could only get it some of the time. Perhaps the touch target is too small?

**Comment by tlabaj** [comment]
> Testing this on my Android phone, I had a really hard time making the slider drag work. I could only get it some of the time. Perhaps the touch target is too small?

@mcarrano interesting.  I tried it on my Android phone and  it worked well for me.

**Comment by nicolethoen** [comment]
I don't think you implemented my suggestions exactly correctly.
The whole window is still trying to scroll when dragging left/right:
Feb-11-2021 16-15-46

**Comment by mcarrano** [comment]
>  I tried it on my Android phone and it worked well for me.

I can get it to work, but it's hard to get focus in the slider thumb. I have to tap very precisely. Maybe it's my big clumsy fingers :)

**Comment by evwilkin** [comment]
LGTM - tested on safari/chrome on iPhone and chrome on Chromebook tablet

**Comment by tlabaj** [comment]
@mcarrano I had Don try it too.  He has the same phone I have and had the same issues you are seeing.  I thin you are right the touch point is to small.  @mcoker any thoughts on this?  Could we make the touch point larger?

**Comment by dlabaj** [comment]
> > I tried it on my Android phone and it worked well for me.
> 
> I can get it to work, but it's hard to get focus in the slider thumb. I have to tap very precisely. Maybe it's my big clumsy fingers :)

I tried it and have the same problem with big clumsy fingers as well :-)

**Comment by mcoker** [comment]
> Could we make the touch target larger?

@tlabaj yep! Increased the target size to 44x44 https://github.com/patternfly/patternfly/pull/3859

**Review by nicolethoen — APPROVED** [review]

**Review by kmcfaul — APPROVED** [review]

**Review by dlabaj — APPROVED** [review]
Works great now.  Thanks for the update.

**Review by evwilkin — APPROVED** [review]
LGTM - way easier to grab the slider now 👍

**Review by mcarrano — APPROVED** [review]
This looks great, now. Thanks @tlabaj !

**Review by nicolethoen — APPROVED** [review]

**Pull request merged**
