### PR TITLE
chore(Panel): update component unit tests to meet new RTL standards

### LINKED ISSUE #8247: Panel test revamp

### PR DESCRIPTION
**Pull request by drewamunat2**
**What**: Closes #8247

### CODE REVIEW

**Review by thatblindgeye — CHANGES_REQUESTED** [review]
This is looking nice! Only had a few small changes below for consistency

**Review by thatblindgeye — APPROVED** [review]
🎉

**Review by jenny-s51 — APPROVED** [review]
Code LGTM, all Panel tests passing locally 👍

**Review by kmcfaul — APPROVED** [review]

**Review by wise-king-sullyman — APPROVED** [review]
🚀

**Pull request merged**
