### PR TITLE
chore(react-tokens): exclude dark theme blocks

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly-react/issues/7469

### CODE REVIEW

**Comment by jschuler** [comment]
Here's a diff between the current react-tokens and after the change FYI
https://diffy.org/diff/7263e28925bd5

**Comment by mcoker** [comment]
@evwilkin @jschuler the problem is that react tokens just does a regex match for CSS vars in a global CSS var file - https://github.com/patternfly/patternfly-react/blob/35dea6aaa7ed4c6f49ae0d3ee6644dda3efb2889/packages/react-tokens/scripts/generateTokens.js#L103-L107

That file has a handful of selectors in it that redefine global variables (https://unpkg.com/browse/@patternfly/patternfly@4.196.3/base/patternfly-variables.css), so the vars in those selectors will be returned multiple times. The dark theme code was in there, and I'm assuming since those vars are required to be defined last, their value was getting used as the value in the token.

I'm sure there's a better way to do this, but I'm using `css` to `parse` that stylesheet instead, excluding blocks that match `/\.pf-theme-dark/` and `stringify` to put it back in stylesheet form before running the existing regex match - https://github.com/patternfly/patternfly-react/blob/bfd2f40f8a72bc1777882d9fb2904aaab839a7b4/packages/react-tokens/scripts/generateTokens.js#L108-L116

**Comment by jschuler** [comment]
Hi @mcoker , thanks for the fix! The diff looks much smaller now
https://diffy.org/diff/243e6fc7161a1
Assuming these changes are intended, so LGTM!

**Review by jschuler — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]
LGTM

**Pull request merged**
