### PR TITLE
Add stacked area chart example

### PR DESCRIPTION
**Pull request by dlabrecq**
Added stacked area chart example, per design's request

Fixes https://github.com/patternfly/patternfly-react/issues/2853

Screen Shot 2019-09-09 at 2 18 13 PM

### CODE REVIEW

**Comment by jenny-s51** [comment]
Hi Dan, I didn't know you were working on this, so I also added a stack chart example, demo, and cypress test to my branch here https://github.com/jenny-s51/patternfly-react/commit/9e57aee10ab460b422d34af02a5131265ec0c342 ... your changes look great to me so I'll just go ahead and approve yours 🙂

**Comment by dlabrecq** [comment]
Sorry, I've been working with Matt and Michael offline on the design.

**Comment by dlabrecq** [comment]
If you want to add your demo and cypress test, that would be great!

**Comment by dlabrecq** [comment]
Sorry @jenny-s51, I've been working with Matt and Michael on a specific design.

If you still want to add your demo and cypress test, that would be great. I'll approve.

**Comment by jenny-s51** [comment]
Awesome, thank you Dan! it's up now at https://github.com/patternfly/patternfly-react/pull/2896 @dlabreq

**Pull request merged**
