### PR TITLE
fix(page): replace hasNoPadding property in the documentation example

### LINKED ISSUE #4856: page: stop using hasNoPadding deprecated property in the documentation examples
Resulting in it not taking effect.

Screen Shot 2020-09-22 at 11 00 55

### PR DESCRIPTION
**Pull request by KKoukiou**
Closes #4856

### CODE REVIEW

**Review by jschuler — DISMISSED** [review]

**Review by tlabaj — DISMISSED** [review]
Can you please link associated issue in the description for tracking purposes.  Thanks

**Comment by KKoukiou** [comment]
> Can you please link associated issue in the description for tracking purposes. Thanks

There is not issue created for this one - I just noticed the problem and posted a fix.

**Comment by tlabaj** [comment]
Thanks for fixing that.  Do you mind opening an issue so we can merge it?

**Review by redallen — APPROVED** [review]

**Review by redallen — APPROVED** [review]

**Comment by KKoukiou** [comment]
@tlabaj can you please approve this one?

**Pull request merged**
