### PR TITLE
feat(Slider): Add a Slider Component with storybook and test

### LINKED ISSUE #183: Component : Slider
Provide implementation for the [PatternFly Slider](http://www.patternfly.org/pattern-library/forms-and-controls/slider/)

Test page for the PF core implementation can be found here for comparison: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/bootstrap-slider.html?

Include story examples demonstrating this features in a mock application scenario

### PR DESCRIPTION
**Pull request by Laviro**
Added Slider.js, WrappedBootstrapSlider.js and Slider.stories.js.

The Slider component is based on the 'bootstrap-slider' library. In this library jQuery is optional
and without its instance there will be raised an error. To fix this error I went inside
webpack.config.js and add an externals line to map 'jquery' into 'null'.

fix #183

Will glad to hear what do you think about it

### CODE REVIEW

**Comment by laviro** [comment]
Check the storybook's examples here: https://laviro.github.io/patternfly-react/?selectedKind=Slider

**Comment by laviro** [comment]
@serenamarie125 
Hey, you can check the slider implementation here: 
https://laviro.github.io/patternfly-react/?selectedKind=Slider

In case a slider has a range (like in the third example) 
should we create two text-inputs and select-boxes, one for each value ?

**Comment by Laviro** [comment]
Added tests with Enzyme and jest that simulate 'change' event on the select-list and input field,
The test also trigger component life-cycle function.

**Comment by Laviro** [comment]
@serenamarie125 Hey, sorry about that, I had upload another storybook and it might override this one, now the link for the slider's storybook works :)

**Comment by serenamarie125** [comment]
It would also be nice to include the Numeric Scale on one of the options (as shown in the [design](http://www.patternfly.org/pattern-library/forms-and-controls/slider/#design))

**Comment by jgiardino** [comment]
Hi @Laviro,

The [example in patternfly core](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/bootstrap-slider.html) is using `<label>` for the text labels, but they’re just `<div>`s in this example. 

Can you use `<label>` instead, and associate the labels with the `<input>` of the slider using the `for` attribute?

**Comment by Laviro** [comment]
@serenamarie125 @jgiardino, Hey, thank you for your comments, 
I am going to mimic the design and later I would like to hear what your think :)

**Pull request closed without merging**
