### PR TITLE
feat(date-picker): bugfixes and add range picker demo

### LINKED ISSUE #4732: Build Date Range picker

### PR DESCRIPTION
**Pull request by redallen**
**What**: Closes #4732

Bugfixes:
- Remove `'@patternfly/patternfly/patternfly-date-picker.css'` left over from `flatpickr` implementation and remove unused `@patternfly/patternfly` dependency
- Allow `value={null}` or other invalid dates in DatePicker and CalendarMonth
- Memoize weeks, days, and validity of days to only recompute when the year, month, or weekStart changes. Scrolling between months and years is noticeably faster.
- Only validate DatePicker `onBlur` per @mcarrano's suggestion
  - Don't validate if field was untouched per @nicolethoen's suggestion
- Clone dates before passing them to consumers (before consumers could mutate component state since dates are mutable)
- Add `ariaLabel` props to `CalendarMonth` per @nicolethoen 

Demo https://patternfly-react-pr-5184.surge.sh/components/date-picker/react-demos
- Expose `isValidDate` helper
- Add hovered date support to CalendarMonth for the range picker

**Additional issues**:

### CODE REVIEW

**Review by jessiehuff — COMMENTED** [review]
Looks pretty good to me! Still works with keyboard, and it's pretty solid in VO. The only enhancement I'd make is changing the `aria-label` on the input fields from "Date picker" on both: `<input type="text" aria-label="Date picker" placeholder="yyyy-MM-dd" class="pf-c-form-control" value="1993-01-01" aria-invalid="false">`
to "Start date" and "End date". That's the model that Google calendar follows, and I think that makes the most sense. 🙂

**Review by nicolethoen — COMMENTED** [review]
First thought - can we allow for custom aria labels throughout the component for localization purposes?

**Comment by nicolethoen** [comment]
Also, when I focus on the first date input in the range picker demo, then tab out without typing a date, I get an invalid date error. I dont think that should happen

**Comment by redallen** [comment]
@nicolethoen In DatePicker yes but in CalendarMonth no. I'll add a slew of props now.

**Comment by redallen** [comment]
@nicolethoen I've added pristine state tracking as well. It will only show error text on blur if you've typed into it.

**Comment by nicolethoen** [comment]
idk if this is more a css thing, but It doesn't look very pretty to me when I have an invalid date error message:
can we keep both pickers in the range on the same line? even if one has an error message?
Screen Shot 2020-11-30 at 1 50 51 PM

**Review by jessiehuff — APPROVED** [review]
It looks great from an accessibility standpoint. 👍 I see what Nicole means on the invalid date error though.

**Comment by redallen** [comment]
@nicolethoen I've been working since last week with @mcoker to make a layout that addresses that issue.

**Comment by mcoker** [comment]
If I pick a start date, then open the end date calendar and go to the next month, I end up with this - seems like the `pf-m-end-range` class isn't being applied correctly. It fixes itself if I hover over the cell.

Screen Shot 2020-12-01 at 9 43 28 AM

**Review by nicolethoen — APPROVED** [review]
If they don't already exist, could you be sure to create issues to add cypress and unit tests for the calendar month and datepicker components?

**Comment by redallen** [comment]
Good point @mcoker . What should the calendar look like after clicking the previous/next month arrows from the following state @mcarrano ?
image

**Review by jessiehuff — DISMISSED** [review]
Looks good from the a11y side! 🙂

**Review by mcarrano — APPROVED** [review]
Looks good to me. Thanks @redallen !

**Review by mcoker — APPROVED** [review]
lgtm!

**Pull request merged**
