### PR TITLE
fix(Wixard): Fixed id not being applied to wizard step

### LINKED ISSUE #6993: WizardStep: 'id' property is not parsed
**Describe the issue. What is the expected and unexpected behavior?**

WizardStep defines the 'id' property, but this is not used in the component.
https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/Wizard/Wizard.tsx#L16

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
https://codesandbox.io/s/ed85iv

Note id `#test` as defined in the code sandbox does not appear in the nav items. 

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
bug

**What is your product and what release version are you targeting?**
Workaround is to use: `stepNavItemProps: { id: "test" }`

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #6993

### CODE REVIEW

**Review by nicolethoen — APPROVED** [review]
LGTM!

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
Changes look good and seem to work well, but can you add a quick test (or a couple of tests) for them?

**Comment by tlabaj** [comment]
@wise-king-sullyman one of the examples has ids being applied.  IT was not working before.

**Review by wise-king-sullyman — APPROVED** [review]
Looks great!

**Pull request merged**
