### PR TITLE
[WIP]  feat(Tagging) Introduce Tagging React component

### PR DESCRIPTION
**Pull request by PanSpagetka**
Add Tagging component in React to patternfly repo. Originally introduced in https://github.com/ManageIQ/react-ui-components/pull/3

**Link to Storybook**:
https://PanSpagetka.github.io/patternfly-react/

**Additional issues**:

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
@patternfly/patternfly-react-ux  Looking for a volunteer to self-assign themselves to handle the UX review for this

**Comment by PanSpagetka** [comment]
@jeff-phillips-18 Yep, still working on some issues with css build process, but I will add less version.

Storybook is working and I don't plan any major changes, so it is ready for UX review. Maybe I would change sorting of items in Selects and Categories/Values, but that could be subject of UX review.

**Comment by terezanovotna** [comment]
Hi @PanSpagetka, I have few things I've noticed. 
1.  image message on hover needs to be displayed quicker. I know its there, but the user is not going to wait for it. 

2. Displaying icon only oncei icon

3. I see that the tags are organized in the order the user added them. Could we organize them alphabetically?
screen shot 2018-05-17 at 10 35 20

4. Tag truncation - Do we want to show super long tags? We probably don't want to display super long tags, but what limitation should we have? When truncated, the rest of the name should appear on hover. 

truncation

Great job so far, tags look great!!
@patternfly/patternfly-react-ux anything else you noticed?

**Comment by terezanovotna** [comment]
Is the storybook link showing the latest changes @PanSpagetka? Or am I being too proactive?

**Comment by PanSpagetka** [comment]
@terezanovotna I forgot to update it, now ishttps://PanSpagetka.github.io/patternfly-react/  running new version

**Comment by terezanovotna** [comment]
Looks great!!

Can we make the hover faster?

- "i" it takes a while to figure out there's a hover on the i
 screen shot 2018-06-11 at 11 41 36
- I like how we truncated both parts of the tag. Can we make the hover appear faster on both areas?
screen shot 2018-06-11 at 11 41 47

**Comment by jgiardino** [comment]
Hi @PanSpagetka, thanks for opening this PR! 

Is this contribution providing the UI shown under the heading "Assigned Tags", or does it also include the UI shown under the heading "Add/Modify Tag"? If it does include the UI shown under "Add/Modify Tag" then we would need to work with the patternfly design team, as noted [here in contributing.md (5th bullet)](https://github.com/patternfly/patternfly-react/blob/master/CONTRIBUTING.md#react-component-requirements). 

Most storybooks include a link to the design documentation for the component as well as a button to view the storybook code, but this section of the storybook is missing.

**Comment by PanSpagetka** [comment]
Hey @jgiardino 

It is providing both parts,  "Assigned Tags" and  "Add/Modify Tag" one. But it is exporting only static component for both parts. Interaction is separate wrapper component, which is not exported and serves as an example for storybook. 

I worked with @terezanovotna and we figure out this design, there might not be any kind of official documentation, but I am not sure. I believe, that more member of design team reviewed this in https://github.com/ManageIQ/react-ui-components/pull/3

**Comment by jgiardino** [comment]
Hi @PanSpagetka, 

I was chatting with @terezanovotna yesterday about this component. Currently, as part of our [react component requirements](https://github.com/patternfly/patternfly-react/blob/master/CONTRIBUTING.md#react-component-requirements), when components are contributed they should have existing documentation on patternfly.org. In cases where a component does not have design documentation, then the contributors can work with the patternfly designers to determine if the component, or some aspect of the component, passes the [patternfly decision tree](https://github.com/patternfly/patternfly-design/blob/master/resources/decision-tree/PatternflyDecisionTree.pdf). 

@terezanovotna is going to work with @mcarrano on this process for the part of the storybook that's labeled "Add/Modify Tags". 

But the part that's labeled "Assigned Tags" already is very similar to our latest design for filter chips in our [Filters design documentation](http://www.patternfly.org/pattern-library/forms-and-controls/filter/#design). If you're interested, you could split this part out and contribute that piece, while we wait for the other part to go through the pf decision tree process.

**Comment by terezanovotna** [comment]
Thanks @jgiardino for the guidance. @PanSpagetka and I discussed what would be the best way to divide these components so they could be more generalized.

[Here is a design pattern issue.](https://github.com/patternfly/patternfly-design/issues/680)

What do we have to do to move it forward? 

Should we discuss it on a quick call? @PanSpagetka @jgiardino @mcarrano 
Thanks!

**Comment by mcarrano** [comment]
I agree with @jgiardino . The only thing that is really unique here is the Tags themselves and this is really an elaboration on the existing filter chips. The remainder of this can be built from existing components and is best documented as a design pattern to ensure a consistent approach across products. @PanSpagetka @terezanovotna is that also in line with your thinking?

As an additional point of information, for PF4, we identified the need for a more generalized Tag component that can satisfy use cases like this as well as filtering.

**Comment by karelhala** [comment]
@jgiardino great points! However I don't think this falls under react component requirements since this component does not have PF design yet and the sole purpose of this being here is for others to use this component. Based on the decision tree (btw nice treee, didn't know about it) it passes it rather easilly. Once UX team brings design for this component I guess @PanSpagetka will be happy to rewrite it based on the design. But I don't think it needs to hold this PR from merging, correct me if I am wrong but when I was discussing Monorepo with @ohadlevy and @priley86 I got and impression that we would be able to introduce new components which does not directly fall under PF design but we feel like that it might be of interest for other teams. 

Btw somewhat similiar discussion was when [SerialConsole](https://github.com/patternfly/patternfly-react/pull/160) was introduced but at that time we didn't had the luxury of monorepo.

We have two options here:
1) Merge this without PF design and let PF team to work on it without them to work in a hurry.
2) Wait for PF design on this component and in the meantime create new component in side repository and once such design is provided rewrite everything.

For me personally it feels like second option is much more work, but it will be easier for @PanSpagetka to make this fork for ManageIq. But we'll loose the option to be shared amongst other projects, which is kinda a bummer.

@mcarrano Sadly this is not applicable to filter chips since the both categories can have a lot of values and user needs to both filter trough them to make the work much easier. In theory it serves to same purpose so with some minor tweaks filter chips could be used for this, but these 2 designs aim to different use cases and should bring users to different thinking. One to filter trough some content while the second adds some properties to content.

However if any of you think that this shouldn't be part of PF react repository no big deal we are glad that designers started to talk about this and will come up with much better design. In the meantime we will use this component in our repo and once solid design is introduced we'll use it.

**Comment by jgiardino** [comment]
Thanks for sharing your thoughts, @karelhala! A lot of what you say is totally valid. 

I have also heard that after the changes we made related to the monorepo work, we could enable contributors to share code that hasn't been fully vetted by the patternfly design review process. And that these components would be available in a separate package from the core patternfly-react package. I don't know if there was a final decision on that yet, so I'm adding @dgutride and @priley86 in case they have any more information to share.

I would still recommend that the part of this contribution that's labeled "Assigned Tags", shown here:
image

be contributed in a way that it can serve for both the original requirement in ManageIQ as well as the [pattern documented for Filter Chips](http://www.patternfly.org/pattern-library/forms-and-controls/filter/#overview), shown here:
image

This tag/label/filter chip component seems general enough that it could be used in both patterns. And if we can create a component that could serve both purposes, and for which a pf design already exists, then I'd suggest we introduce that piece to the core patternfly-react package of this repo. We definitely need a component like this.

> @mcarrano Sadly this is not applicable to filter chips since the both categories can have a lot of values and user needs to both filter trough them to make the work much easier. In theory it serves to same purpose so with some minor tweaks filter chips could be used for this, but these 2 designs aim to different use cases and should bring users to different thinking. One to filter trough some content while the second adds some properties to content.

The example I included above is quite new to the patternfly design library. Do you think this new pattern would work for tags? I think if the same visual design can be used for both, then the same component can be used for both, even if they are supporting different use cases. 

In @mcarrano's comment:

> The remainder of this can be built from existing components and is best documented as a design pattern to ensure a consistent approach across products.

I agree with the idea of constructing this design from separate, independent components. At the moment, we don't have a [Select component](https://github.com/patternfly/patternfly-react/issues/54). But it would be great to have the pieces of this as separate components that can be used independently.

**Comment by PanSpagetka** [comment]
@jgiardino I agree that we can use chips for both, Tagging and Filtering. There exist Filter component in patternfly-react core package with simple version of these chips.
screenshot from 2018-06-15 12-11-35

I try to wrap up what you are suggesting, correct me if I am wrong.
- Extract chips from `Tagging` and `Filter` into separate `Chips` component, with grouped and simple version.
- Use these  `Chips` in  `Tagging` and `Filter`
- Use `PatternflySelect` in `Tagging` when we have one

So I would do a separate PR extracting 'Chips'  and another one for integrating into `Filter`. In the meantime, can this PR be merged as a separate package or shall we wait until `Chips` component is made and integrated?

Is there another design/process problem with this approach?

**Comment by jgiardino** [comment]
@PanSpagetka The breakdown of components that you describe sounds right to me, but would love to have one of the JS devs confirm. @priley86, @jeff-phillips-18, or @mturley - do you have any thoughts on how to break these pieces down into individual components?

One thing I'm wondering is if what @PanSpagetka refers to as a `Chip` is just a variation of the [`Label`](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?selectedKind=patternfly-react%2FWidgets%2FLabel&selectedStory=Label%20with%20remove&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)? Should we extend the Label component to support the second example here, or would both examples below be included as a new and separate component from 'Label':
image

If it is a new component, does anyone have concerns with `Chip` or is there another name we should use instead? (adding @mcarrano in case he has thoughts on this one)

> In the meantime, can this PR be merged as a separate package or shall we wait until Chips component is made and integrated?

I think this is possible, but would like guidance from the JS devs mentioned above on this.

**Comment by mcarrano** [comment]
After looking at this further, I agree with @jgiardino that what is being proposed here is really just an extension of the Label component and should be treated as such. I'd suggest we define a new variant that is called something like a Compound Label to describe a single attribute label with multiple values applied.

So while the use case/design pattern can be called "Tagging" it is actually using a Label component. I think the same would be true for what we are calling a Filter Chip.  @terezanovotna please take note as you are writing up the design doc.

**Comment by PanSpagetka** [comment]
Yep this could be treated as extension of `label` component, but i still suggest making separate components not extend `Label`. So `Label` component will stay exactly same as it it now, just create variants of labels as a new components.

One we can call `CompoundLabel` and it will represent grouped Key:Value(s) pair displayed in Label way. Both Labels in picture will be `CompoundLabels`
image

Second one, I couldn't come with nice name, let's call it for now `KeyValueLabel` would represent simpler case, just one Key:Value pair displayed in `Label`. Even though technically is not necessary to make this new component, it is possible to use `Label` with `key:value` string, I would still do it because I want to separate Key and Value as a separate pieces of data.
image

**Comment by jeff-phillips-18** [comment]
The tagging component was completed by #464 as CompoundLabel.

**Comment by PanSpagetka** [comment]
@jeff-phillips-18 No, #464 is just one part of Tagging component, this PR is still relevant.

**Comment by jeff-phillips-18** [comment]
@PanSpagetka Ah, OK. Reopening.

**Pull request closed without merging**
