### PR TITLE
perf(ouia): make ouia functional, add namespace

### LINKED ISSUE #3317: <Button> rendered as <Component> in jest snapshots after updating to the latest PatternFly, breaking our tests
After updating to `@patternfly/react-core@3.120.5` (we previously used `@patternfly/react-core@3.86.1`), every `<Button>` in our snapshot is now `<Component>`, and some other components are affected too.

If this was just an issue with the snapshot itself, it wouldn't be a big deal, but it also affects more functional tests that we have, for example finding a button in the shallow rendered component, simulating a click, and checking the result. Now that the snapshot no longer has `<Button>`, we can't use `.find('Button')` anymore, as it doesn't find anything.

This means that we can't upgrade to the latest PatternFly, and this blocks us from implementing important features and improvements.

### LINKED ISSUE #3626: Add namespacing into data-ouia-component-type attributes
**Describe the issue. What is the expected and unexpected behavior?**

There are cases when a web application can use more than one component library and there could be used similar components such as Dropdown. In order to distinguish components with OUIA in QA suite  `data-ouia-component-type` should contain namespace e.g. `data-ouia-component-type=PF4/Dropdown`

Here spec excerpt https://ouia.readthedocs.io/en/latest/README.html#ouia-component:

> A root level HTML element with a data-ouia-component-type attribute describing a unique name identifying ALL HTML components that can be controlled with the same code or interactions. These identifiers MAY and SHOULD be namespaced when used within a framework, particularly when the name is generic. The delimiter between namespace and type name should be a single / character.

> * e.g. A page that has a special dropdown could choose to name that dropdown as FrameworkA/CustomDropdown. All instances of this FrameworkA/CustomDropdown component MUST be expected to be able to be controlled via the same automation.

### PR DESCRIPTION
**Pull request by redallen**
**What**: Remove `withOUIA` HOC as discussed in #3622. In this PR it is replaced in favor of a functional:
```ts
function getOUIAProps(componentName: string, id: OuiaId | undefined, ouiaSafe: Boolean = true) {
  return {
    'data-ouia-component-type': `PF4/${componentName}`,
    'data-ouia-safe': ouiaSafe,
    'data-ouia-id': id === undefined ? uid++ : id
  };
}
```

Many snapshots now correctly identify the component since our old [withOUIAContext HOC](https://github.com/patternfly/patternfly-react/blob/83924aa5c081796f3e72667f23d90d27d96c5672/packages/react-core/src/components/withOuia/withOuia.tsx#L19) with a [displayName of `Component`](https://reactjs.org/docs/react-component.html#displayname) is gone.

Implementation in components is much cleaner:
```tsx
import { getOUIAProps, OUIAProps } from '../../helpers';

export const Alert: React.FunctionComponent<AlertProps & OUIAProps> = () => (
  <div {...getOUIAProps('Alert', ouiaId)} />
);
```

Spec: https://ouia.readthedocs.io/en/latest/README.html#ouia-component

**Additional issues**: Closes #3626 , Closes #3317

### CODE REVIEW

**Comment by mturley** [comment]
@redallen does this need to be in v4 or can it go into master too? What's the breaking change?

**Comment by mturley** [comment]
This issue was closed by `stale-bot`, but I think this PR resolves it (which is why it might be nice to backport to master): https://github.com/patternfly/patternfly-react/issues/3317

**Comment by redallen** [comment]
There is no breaking change, but because of the +178,936/−235,682 of snapshot changes we considered this "breaking" enough to put on this branch since most consumer snapshots will change.

 See https://github.com/patternfly/patternfly-react/pull/3622#issuecomment-582557302

**Comment by mturley** [comment]
Fair enough. I'll talk to folks downstream about upgrading to v4.

**Pull request merged**
