### PR TITLE
feat(Toolbar): consumed Penta updates

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Towards #9677 
@mattnolting Based on updates in Core, we removed some modifier classes/props in React. The `pf-m-chip-container` class no longer has any styles in Core so was removed in React, but Core is still applying the class. Do we want to keep this modifier class or should it be removed in Core?

**Additional issues**:

### CODE REVIEW

**Comment by mattnolting** [comment]
> **What**: Towards #9677 @mattnolting Based on updates in Core, we removed some modifier classes/props in React. The `pf-m-chip-container` class no longer has any styles in Core so was removed in React, but Core is still applying the class. Do we want to keep this modifier class or should it be removed in Core?
> 
> **Additional issues**:

@thatblindgeye good to delete!

**Review by wise-king-sullyman — APPROVED** [review]

**Comment by mattnolting** [comment]
Great work @thatblindgeye, thank you!

**Comment by andrew-ronaldson** [comment]
Screenshot 2024-02-01 at 12 48 15 PM
This stacked example has a split select but the menu doesn't have selectable items.

The only other thing I see is for Core. I think we need a spacer--xs between the pf-m-icon-button-group

**Comment by andrew-ronaldson** [comment]
This [react demo](https://www.patternfly.org/components/toolbar/react-demos/console-log-viewer-toolbar-demo/) also cuts off the content. Doesn't do that on current site.

Screenshot 2024-02-01 at 1 04 31 PM

**Pull request merged**
