### PR TITLE
feat(react-core/card): added PatternFly 4 Card Component

### PR DESCRIPTION
**Pull request by dmiller9911**
affects: @patternfly/react-core, @patternfly/react-docs

Added the Card Component from here: https://pf-next.com/components/Card/examples/

ISSUES CLOSED: #386

### CODE REVIEW

**Comment by jgiardino** [comment]
The only potential concern I have is about the default html elements defined. I realize that a request was made in PF4 core to default cards to `<article>`. For this element, using `<header>` and `<footer>` makes sense. But if another element is defined that is either not a [sectioning content](http://w3c.github.io/html/dom.html#sectioning-content-2) element or [sectioning root](http://w3c.github.io/html/sections.html#sectioning-roots) element, then `<header>` should not be used, as [stated by the w3c](http://w3c.github.io/html/sections.html#elementdef-header):

> The `<header>` element represents introductory content for its nearest ancestor `<main>` element, sectioning content, or sectioning root element.  

Does anyone have thoughts or suggestions on that? I'm torn between using these defaults, which are likely to be the right elements to use for most cases, versus requiring consumers to explicitly set what they want these elements to be. My concern is that if we make assumptions and set defaults, and the consumer isn't fully aware, then we're partly responsible for bad semantics. Is it possible to switch the default from `<header>` to `<div>` if the parent element is not a sectioning content or sectioning root element?

**Comment by jgiardino** [comment]
This comment may be out of scope for this PR, but when I look at the preview, it looks like I'm only seeing details about the parent Card component, and not the children components being used, like CardBody and CardHeader. Would you expect all components that are used to create the example to be represented in the Props section?

**Comment by dmiller9911** [comment]
@jgiardino What is the risk of header/footer being used outside of a sectioning element?  I can't find that in the docs it just mentions to not do it.  Is it treated like a `div`? Also what is going to be the majority use on these?  I am cool to use `div`s as defaults, but if users are meant to make them articles 90% of the time I think it makes sense to default to `article`. As for verifying there is not a good way to do this in all honesty. Anything we would do would be hacky, hard to maintain, and not very performant. For the props table that is a known issue.  I plan to fix that soon.

**Comment by jgiardino** [comment]
> What is the risk of header/footer being used outside of a sectioning element?

@dmiller9911 My best guess is that the first occurrence of `<header>` will be considered the header for the `<main>` section if `<main>` is present as an ancestor to the Card, or `<body>` if `<main>` isn't present. 

I'm on the fence for this one. I'm guessing this situation could come up again for other components. I added this as an agenda topic for our weekly a11y review on Thursdays. I'm also copying @andresgalante on this one in case he has any suggestions before then.

While I'm all for promoting the use of semantically correct elements, I don't like making assumptions about the consumer's use case. Something seems off about requiring the consumer to 1.) understand that default elements are defined, and 2.) explicitly define generic elements if the default ones aren't appropriate for their use case.

One possible solution is to use a default `<article>` element for the parent `<Card>` component, but require the consumer to explicitly set `<header>` as the element for `<CardHeader>` and `<footer>` for the `<CardFooter>`.

**Comment by dmiller9911** [comment]
@jgiardino That seems like a good middle ground.

**Comment by dmiller9911** [comment]
@jgiardino mind taking a look and giving the thumbs up for this? The extra component docs will be coming soon with a different PR.  Most likely early next week. Right now Card defaults to article.  Header and Footer default to divs.

**Pull request merged**
