### PR TITLE
fix(Topology): Fix for multiple popovers occurring for pipeline badges

### LINKED ISSUE #8100: Bug - Pipelines Topology - Multiple popovers are shown at the same time
**Describe the problem**
A clear and concise description of the problem. Which components are affected?

Clicking on `Task` badge opens popover but fails to close the previously opened popover.

**How do you reproduce the problem?**

1. Visit  and click on `Layout` option in https://topology-pipeline-zoom2.surge.sh/
2. click on multiple Task badge icon

**Expected behavior**

Previously opened popover should be closed on clicking a task badge.

**Screenshots**
If applicable, add screenshots to help explain the issue.

image

**What is your product and what release date are you targeting?**
Openshift Developer Console.

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
**What**: 
Fixes #8100 

/cc @christianvogt @karthikjeeyar

### CODE REVIEW

**Comment by nicolethoen** [comment]
@jeff-phillips-18 is this 'breaking change' something that has been or can be communicated to openshift ahead of merging/releasing it? usually something like this would really slow down the release as we try to either get openshift to agree to making the change or decide if we need to revert. In this case, if they can know it's coming and be prepared to make the change (if needed) then that'd be very helpful.

**Comment by nicolethoen** [comment]
Otherwise, we are only a few milestones away from our next major release which can include breaking changes

**Comment by christianvogt** [comment]
I think `Popper` should attach listeners to the `document` and use `capture = true` such that clicking on the document will get the event on the capture phase and avoids interrupting from intermediate nodes that choose to stop propagation.

**Comment by jeff-phillips-18** [comment]
@nicolethoen This is not a breaking change. I have gone with @christianvogt's suggestion and there is no change necessary for the application to make any changes to get this fix

**Comment by jeff-phillips-18** [comment]
@nicolethoen I don't think #8100 warrants holding up the release for this. We can wait for next time.

**Comment by nicolethoen** [comment]
Code freeze is EOD tomorrow, so i think we can aim to get this in

**Review by tlabaj — APPROVED** [review]

**Review by nicolethoen — APPROVED** [review]

**Pull request merged**
