### PR TITLE
fix(button): support setting tab index unless not button and disabled

### LINKED ISSUE #3208: PF4 Button does not pass through tabIndex prop
Define a pf4 button with `tabIndex` prop,
```
import { Button } from '@patternfly/react-core';
......
<Button tabIndex="-1">test</Button>

```

The `tabIndex` prop is missing from the rendered DOM,
```
<button class="pf-c-button" type="button">test</button>
```

### PR DESCRIPTION
**Pull request by boaz0**
**What**:

closes #3208 

//cc @petli-openshift

### CODE REVIEW

**Comment by boaz0** [comment]
It seems like a problem with the memory size causes pf4 docs build to fail.

In addition, I can build the docs successfully on my machine and can't reproduce it on my machine.

@redallen can you look at it?

>@patternfly/react-docs: failed Building static HTML for pages - 70.042s
@patternfly/react-docs: error Building static HTML failed
@patternfly/react-docs:   1 | function _defineProperty(obj, key, value) {
@patternfly/react-docs: > 2 |   if (key in obj) {
@patternfly/react-docs:     | ^
@patternfly/react-docs:   3 |     Object.defineProperty(obj, key, {
@patternfly/react-docs:   4 |       value: value,
@patternfly/react-docs:   5 |       enumerable: true,
@patternfly/react-docs: 
@patternfly/react-docs:   WebpackError: Call retries were exceeded

**Comment by redallen** [comment]
Yeah, this is an OOM error. I left both -next and -org previews somewhat broken last week and are going to go back and fix them this week. I've rekicked your job for you in the meantime.

**Comment by boaz0** [comment]
Thanks @redallen !

**Comment by tlabaj** [comment]
@boaz0 Can you update this pR so we can try and get it in?  Thanks!

**Comment by boaz0** [comment]
Yeah sure. No problem.

**Pull request merged**
