### PR TITLE
chore(Tooltip): updated unit tests

### LINKED ISSUE #7687: Tooltip

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Closes #7687 

Replacement for https://github.com/patternfly/patternfly-react/pull/7740

@wise-king-sullyman There's a lot I didn't include in tests here as they felt more like tests applicable to Popper rather than Tooltip. Do you think it'd be worth using the Popper mock we have to test more of the Tooltip props here? We aren't really using a Popper mock much at the moment (you did add it to an OverflowTab test file, and it's in the Dropdown test file as well).

**Additional issues**:

### CODE REVIEW

**Comment by wise-king-sullyman** [comment]
Yeah I would use the Popper mock and just assert that we're passing the right things to it for those props. Feel free to update the mock however you need to for that.

**Comment by thatblindgeye** [comment]
@wise-king-sullyman let me know what you think of the current tests. With the way we'd be mocking Popper here, it doesn't look like we could really test the Tooltip being visible on hover and such. Could make a separate test file for that or just have cypress tests handle testing for that.

**Review by wise-king-sullyman — COMMENTED** [review]
In addition to our discussions on Slack about the props that aren't currently tested I have two small nits

**Review by wise-king-sullyman — APPROVED** [review]
🥳

**Review by gitdallas — APPROVED** [review]

**Review by kmcfaul — APPROVED** [review]

**Pull request merged**
