### PR TITLE
feat(Table): set default sort direction

### LINKED ISSUE #5329: Click table column header always sorts by ascending first
**Describe the issue. What is the expected and unexpected behavior?**

If you click the table header of a column that isn’t currently sorting the table, the first sort order is ascending, then the second click it’s descending. There doesn’t appear to be a way to specify the sort order for the first click to be descending.

In the context of a table view with a date column, if someone wants to change the sort order to be date created or modified, it’s going to show oldest first (i.e. ascending). However, in most cases, the user is likely more interested in seeing the newer items first (i.e. descending).

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
No steps to reproduce. The expected behavior doesn't appear to be supported.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
enhancement

**What is your product and what release version are you targeting?**
App Services, nice to have for end of March

cc @mcarrano @christiemolloy

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #5329

For both `Table` and `TableComposable` - the default sort direction can now be changed by setting `sortBy.defaultDirection` and will continue to default to ascending order.

Edit: updated to use a separate prop because using `sortBy.direction` meant that the starting sort order would change when toggling sort between different columns.

### CODE REVIEW

**Review by wise-king-sullyman — COMMENTED** [review]
Is there any good way to explain how to take advantage of this functionality? As someone not familiar with Table it would've taken me a long time to figure out how to enable a default direction if I didn't have the changes in this PR to go off of.

I understand from looking at the Table docs that there's already....a lot. There may not be a good place/way to document it because of that, and it seems like there's a lot of quasi-documented stuff in Table already anyway so it might not be needed. If nothing else I feel like it would be beneficial to update the `sortBy` description.

**Comment by nicolethoen** [comment]
@wise-king-sullyman That is always super helpful feedback!
I will point out, since it's not clear from the PR, that there are examples in the docs that [demonstrate sorting](https://patternfly-react-pr-6544.surge.sh/components/table/react-legacy#sortable--wrapping-column-headers) and do explicitly call out how to set a default sort behavior.

But @kmcfaul, I think that we should take the time to somehow define the `ISortBy` type listed in the `ThSortType` [props table](https://patternfly-react-pr-6544.surge.sh/components/table#thsorttype)

**Comment by kmcfaul** [comment]
Added `ISortBy` to the docs as well as to the sorting demos to showcase how to set it (but uses the default value so the behavior isn't changing). I had to change `TableTypes.ts` to `TableTypes.tsx` to get the docs to pick up that file for `ISortBy`, will that be an issue?

**Comment by nicolethoen** [comment]
@kmcfaul I dont think that's an issue.
You need to also add ISortBy to the legacy table docs, too.

And since you're going to expose the ISortBy - I wonder if it's worth exposing all the types in that file that are referenced in the Legacy Table docs. i.e.:
Screen Shot 2021-11-04 at 2 46 08 PM
a86b31491.png)

**Comment by kmcfaul** [comment]
@nicolethoen Added `iSortBy` to the legacy docs. `IActions` and `IActionsResolver` don't appear to want to be added to docs, I think because they are defined as types instead of interfaces?

**Review by nicolethoen — APPROVED** [review]

**Review by wise-king-sullyman — APPROVED** [review]

**Pull request merged**
