### PR TITLE
docs(Masthead): update demo to be fullscreen

### LINKED ISSUE #7210: Docs: - [Masthead] - [Make the Basic demo full screen]
**Describe the problem**
A clear and concise description of the problem. Which components are affected?
Masthead

**How do you reproduce the problem?**
The basic masthead demo is not full screen.  Make it full screen to match core.
https://www.patternfly.org/v4/components/masthead/html-demos#basic

### PR DESCRIPTION
**Pull request by tompsota**
**What**: Closes #7210

### CODE REVIEW

**Review by nicolethoen — CHANGES_REQUESTED** [review]
This demo is built well. I just have two questions/observations.

There are currently a number of core Masthead demos. I think this basic masthead demo should match the [basic core demo](https://www.patternfly.org/v4/components/masthead/html-demos#basic). For that reason, we probably don't want to use the dashboard wrapper. 
@mcarrano is there any reason this demo should diverge from the core basic masthead demo? Should it not use a kebab menu at wide viewport widths? And only use it at smaller widths? What should it display at wider widths if not the kebab menu?

Another reason we would probably opt not to use the dashboard wrapper would be because that obfuscates the code for a consumer who would like to implement something similar to the demo. I think in the masthead demos, we should avoid the dashboard wrapper in general.

**Comment by nicolethoen** [comment]
After talking with @mattnolting and @mcarrano, this demo should be renamed to "Masthead with utilities and user dropdown menu". It might also help to add a few sentences below the title that explains some of the design and implementation details. Possibly something like:
```
Many mastheads contain utilities which collapse into a dropdown at smaller view port widths. These utilities could include a notification badge to open and close a notification drawer, a link to app or user settings, a help icon which could launch quick starts or link to other resources, and many other utilities. In this demo, the notification badge does not collapse down into the mobile menu so that it is always visible even at narrower view port widths.
```

Additionally this demo needs to include building the masthead itself so consumers can see how it's done. It shouldn't use the DashboardWrapper.

**Review by nicolethoen — APPROVED** [review]
Looks great!

**Review by thatblindgeye — APPROVED** [review]

**Review by jenny-s51 — APPROVED** [review]
LGTM - nice work on this @tompsota !

**Review by mcoker — CHANGES_REQUESTED** [review]
Looks great to me! Just one super small nit in the docs.

**Review by mcarrano — CHANGES_REQUESTED** [review]
@tompsota the responsive behavior for this is not quite right. At the mobile breakpoint everything except for the notification bell should move to the kebob menu, including the user menu items as seen in this demo: https://www.patternfly.org/v4/components/page/react-demos/sticky-section-group/

**Comment by tompsota** [comment]
Good catch @mcarrano! Should be fine now.

**Review by nicolethoen — APPROVED** [review]

**Review by mcarrano — APPROVED** [review]
Looks good. Thanks for making that update @tompsota !

**Pull request merged**
