### PR TITLE
Core bump with cypress fix

### PR DESCRIPTION
**Pull request by kmcfaul**

### CODE REVIEW

**Review by redallen — DISMISSED** [review]

**Review by tlabaj — DISMISSED** [review]

**Comment by tlabaj** [comment]
we can merge once conflicts are resolved

**Comment by redallen** [comment]
Yep, let's not merge anything else in the meantime @tlabaj .

**Comment by kmcfaul** [comment]
rebased with latest versions

**Review by redallen — APPROVED** [review]
Hurry before another PR gets merged!

**Pull request merged**
