### PR TITLE
WIP: Base Card Component 

### PR DESCRIPTION
**Pull request by gilad215**
**What**:
Creating the Base Card component. I opened a new PR because i created a new branch `base-card` as @priley86 requested.
issue #192 

Existing Components so far:
`CardContainer` `Card` `CardHeading` `CardTitle` `CardBody` `CardFooter` `CardLink` `CardDropdownButton` `CardTimeFrameFilter`

**Link to Storybook**:
Was unable to pass a custom branch to the `storybook:deploy` command, any suggestions?

**Additional issues**:

Following @priley86 review:
- `CardLink` -  is this what you asked for? i still passed the CSS class required for the button to position right.

- `Card` - are the `accented` and `aggregated` props even needed? please provide more info.

Until further reviews, i'm moving on to creating the custom cards :)

### CODE REVIEW

**Comment by gilad215** [comment]
@ohadlevy @priley86 I'm having some issues with removing the unwanted files. I can't revert `base-card` to patternfly `master`  because i already changed my fork's `master.` I'll meet with @sharvit tomorrow so he can teach me some git guidelines (i didn't have an upstream until now) and i'll create a new fork,pull request if needed.

Until tomorrow, i'll be working on the custom cards!

**Comment by priley86** [comment]
@gilad215 ... yep `CardLink` name is better to me...we can use it to render both footer links with icon/footer links w/o icon. Re: `accented`/`aggregated` we will need them later so I think it's fine if you want to leave them, but we are just trying to tackle the bottom 4 rows in this example w/ the Basic Card issue in this PR:
https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/cards.html

**Comment by priley86** [comment]
hey @gilad215 here is some suggestions:
https://github.com/priley86/patternfly-react/commit/990598d67e532b553431aa16e520696787d0cdac

hope it helps...

**Comment by priley86** [comment]
also - please leave your usage of `defaultProps` in for now. I am going to try to bring up a PR with the additional `airbnb-eslint-config` into this repo later this week where we can discuss it further (but i think it is fine to leave `defaultProps` in the PR for now).

**Comment by gilad215** [comment]
Closing this PR, creating a new formal PR

**Pull request closed without merging**
