### PR TITLE
Page nav flyout bug

### LINKED ISSUE #6396: bug(Nav): Cant see flyout nav when using page component
**Describe the issue. What is the expected and unexpected behavior?**
When using the `Nav` with flyout option inside `PageSidebar`, the flyout elements aren't shown on hover, they appear in the dom but are hidden
**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

https://codesandbox.io/s/summer-star-f9h1e?file=/index.js
Screenshot from 2021-10-04 12-56-33

**What is your product and what release version are you targeting?**
Product - foreman
pf version: "@patternfly/react-core": "4.155.0",

### PR DESCRIPTION
**Pull request by wise-king-sullyman**
**What**: Closes #6396 

**Additional issues**: N/A

This issue didn't call for a new demo, but making one simplified testing/debugging and cleaning up that test demo into something presentable didn't take long so I've included it. If you'd like me to remove the demo entirely I'm happy to do so.

### CODE REVIEW

**Comment by nicolethoen** [comment]
I think the demo is great!
Are we planning to make the flyouts darker to match the rest of the nav?

**Comment by wise-king-sullyman** [comment]
@nicolethoen from looking into it so far making the nav flyouts dark again will require a core change, as the current dark background style is applied when a flyout is nested within a nav item, which they no longer are because we now use popper. I'm honestly not sure how we would want to approach that.

**Comment by kmcfaul** [comment]
@mattnolting @mcoker

We may need a new css class and flag added to `Menu` to get the dark nav-like styling since the nav flyouts are now contained in Popper outside the nav itself.

**Comment by mcarrano** [comment]
+1 to having the new demo. It's very helpful so let's keep it in. And yes, we need to fix the CSS issue before we can release this. The other thing I noticed besides the flyouts being light is that when the mouse leaves the primary nav item to hover on the flyout, the primary item losses it's hover styling which is different from before.

Other than the styling issues above, the behavior looks good.

cc @mcoker

**Comment by mcoker** [comment]
@wise-king-sullyman @kmcfaul @mcarrano I've opened a core issue here to move the styling out of the nav component and into the menu component under a modifier - https://github.com/patternfly/patternfly/issues/4510

**Review by kmcfaul — APPROVED** [review]

**Review by nicolethoen — APPROVED** [review]

**Review by mcoker — APPROVED** [review]
LGTM!!

**Pull request merged**
