### PR TITLE
fix(Multiple): update old component classnames

### LINKED ISSUE #9116: Replace hard coded reference to CSS vars with imported react-tokens

### LINKED ISSUE #9128: Bug - Menu -Spacing issue regression with checkbox menu
**Describe the problem**
A clear and concise description of the problem. Which components are affected?

There is a spacing issue wit the checkbox menu 
it should appear like this 

image

but it appears like this 

image

### PR DESCRIPTION
**Pull request by gitdallas**
Closes #9128 

Possibly closes or atleast makes effort towards #9116 .  I replaced hard coded classes in instances that the style object had one to match.

### CODE REVIEW

**Comment by wise-king-sullyman** [comment]
image

Should these be changed?

**Comment by wise-king-sullyman** [comment]
Primary detail icons are still off. This PR is left, v4 is right. Is this change expected?
image

**Comment by gitdallas** [comment]
@wise-king-sullyman Ah - I think I just searched the react-core/component dir.. I'll see if I can update those real quick and see what's going on with the icons.

**Comment by gitdallas** [comment]
@mcoker @srambach @mattnolting 

any idea about the spacing of icons? for v5 i'm seeing:
image

and for v4 i'm seeing:
image

the v5 margin-right is coming up as nothing

**Comment by mcoker** [comment]
@gitdallas @wise-king-sullyman nice find! That's a bug in core - your update looks good to me. I created a core issue to fix that, no react follow up should be needed https://github.com/patternfly/patternfly/issues/5591

**Review by thatblindgeye — APPROVED** [review]

**Comment by gitdallas** [comment]
@mcoker if you could give an approval with your "approval", that'd be great 😆

**Comment by tlabaj** [comment]
> @gitdallas @wise-king-sullyman nice find! That's a bug in core - your update looks good to me. I created a core issue to fix that, no react follow up should be needed [patternfly/patternfly#5591](https://github.com/patternfly/patternfly/issues/5591)

that is a PR approval correct?

**Review by mcoker — APPROVED** [review]
LGTM! I see some others that should probably be updated, too? But looks like they're all example things, so no rush for release candidate.

#### Components
```
packages/react-core//src/components/MenuToggle/examples/MenuToggle.css:#ws-react-c-menu-toggle-primary .pf-c-menu-toggle, #ws-react-c-menu-toggle-secondary .pf-c-menu-toggle {
packages/react-core//src/components/Alert/examples/alert.css:.ws-react-c-alert .pf-c-alert {
packages/react-core//src/components/Checkbox/examples/checkbox.css:.ws-react-c-checkbox .pf-c-check.nested {
packages/react-core//src/demos/JumpLinks.md:    const masthead = document.getElementsByClassName('pf-c-masthead')[0];
packages/react-core//src/demos/examples/JumpLinks/JumpLinksWithDrawer.js:    const masthead = document.getElementsByClassName('pf-c-masthead')[0];
```

#### Layouts
```
packages/react-core//src/layouts/Split/examples/split.css:.ws-react-l-split .pf-l-split,
packages/react-core//src/layouts/Split/examples/split.css:.ws-react-l-split .pf-l-split > .pf-l-split__item {
packages/react-core//src/layouts/Gallery/examples/gallery.css:.ws-react-l-gallery .pf-l-gallery {
packages/react-core//src/layouts/Gallery/examples/gallery.css:.ws-react-l-gallery .pf-l-gallery > div {
packages/react-core//src/layouts/Bullseye/examples/bullseye.css:.ws-react-l-bullseye .pf-l-bullseye,
packages/react-core//src/layouts/Bullseye/examples/bullseye.css:.ws-react-l-bullseye .pf-l-bullseye > div {
packages/react-core//src/layouts/Level/examples/level.css:.ws-react-l-level .pf-l-level {
packages/react-core//src/layouts/Level/examples/level.css:.ws-react-l-level .pf-l-level,
packages/react-core//src/layouts/Level/examples/level.css:.ws-react-l-level .pf-l-level > div {
packages/react-core//src/layouts/Stack/examples/stack.css:.ws-react-l-stack > .pf-l-stack {
packages/react-core//src/layouts/Stack/examples/stack.css:.ws-react-l-stack .pf-l-stack,
packages/react-core//src/layouts/Stack/examples/stack.css:.ws-react-l-stack .pf-l-stack > .pf-l-stack__item {
packages/react-core//src/layouts/Flex/__tests__/Flex.test.tsx:            .className.replace('pf-l-flex', '')
packages/react-core//src/layouts/Flex/examples/flex.css:.ws-react-l-flex .pf-l-flex {
packages/react-core//src/layouts/Flex/examples/flex.css:.ws-react-l-flex .pf-l-flex > div,
packages/react-core//src/layouts/Grid/examples/grid.css:.ws-react-l-grid > .pf-l-grid,
packages/react-core//src/layouts/Grid/examples/grid.css:.ws-react-l-grid > .pf-l-grid > .pf-l-grid__item {
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">100C</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">50C</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">0C</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">3.6Ghz</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">1.5Ghz</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">0GHZ</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">100C</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">50C</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">0C</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">3.6Ghz</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">1.5Ghz</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">0GHZ</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">100C</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">50C</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">0C</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">3.6Ghz</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">1.5Ghz</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">0GHZ</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">100C</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">50C</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">0C</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">3.6Ghz</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">1.5Ghz</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">0GHZ</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">100C</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">50C</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">0C</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">3.6Ghz</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">1.5Ghz</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">0GHZ</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">100C</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">50C</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">0C</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">3.6Ghz</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">1.5Ghz</div>
packages/react-core//src/demos/CardDemos.md:                          <div className="pf-l-flex__item">0GHZ</div>
```

**Comment by nicolethoen** [comment]
@mcoker @tlabaj 
i opened a [follow up issue](https://github.com/patternfly/patternfly-react/issues/9144) and added it to the [clean up examples/demo epic](https://github.com/orgs/patternfly/projects/16?pane=issue&itemId=27180833) on the roadmap

**Review by tlabaj — COMMENTED** [review]
@dlabrecq does this will need to be updated correct?  I can open a follow up to this PR.

**Comment by dlabrecq** [comment]
@tlabaj charts uses tokens, so snapshots will need updating. The only "pf-" prefixes are for a couple keys and the pattern ID.

**Review by tlabaj — CHANGES_REQUESTED** [review]
It looks like some updates are needed in react-styles and anywhere those classes are being pulled in.  the classes her are still using `pf-c` prefix.
https://github.com/patternfly/patternfly-react/tree/v5/packages/react-styles/src/css/components

**Comment by mcoker** [comment]
re: the react-styles updates @tlabaj mentioned, I'm not sure where the names for the color vars are coming from - https://github.com/patternfly/patternfly-react/blob/v5/packages/react-styles/src/css/components/Table/inline-edit.css

We don't have a `--global--[color]--number` CSS var in core, though it looks like that is how the vars were defined before we added the `v5` prefix, too - https://github.com/patternfly/patternfly-react/commit/3879fc757aefeed80b0694365aa20d5ca856a797#diff-d99fb7d33fdb9c29c555e2926969439a2857b3ec7e95c13155c6c21bb3dce1e2

I can't find an editable table example using composable table, but I see the legacy table example - https://www.patternfly.org/v4/components/table/react-legacy#editable-rows. It doesn't look like any of the classnames in https://github.com/patternfly/patternfly-react/blob/v5/packages/react-styles/src/css/components/Table/inline-edit.css are being applied in edit mode.

If those colors still need to be applied, `--pf-v5-global--[color]--[number]` should be `--pf-v5-global--palette--[color]-[number]` - and the color names should be lower-case.

**Comment by nicolethoen** [comment]
@tlabaj I think that can be a follow up issue because there are lots of other problems with that CSS.

**Comment by tlabaj** [comment]
> @tlabaj charts uses tokens, so snapshots will need updating. However, the only "pf-" prefixes are for a couple keys and a chart pattern ID.

@dlabrecq sorry i forgot to paste a link to what I was talking about above.  I assume this is what needs to be updated correct?
https://github.com/patternfly/patternfly-react/blob/v5/packages/react-charts/src/components/ChartUtils/chart-helpers.ts

**Review by nicolethoen — APPROVED** [review]

**Comment by tlabaj** [comment]
Here is a list of issues that will be follow ups to this PR
#9144, #9150, #9151

**Review by tlabaj — APPROVED** [review]

**Pull request merged**
