### PR TITLE
fix(jest tests): converted table.test.js to TSX

### PR DESCRIPTION
**Pull request by jenny-s51**
**What**: in regards to #1950 , #2360 , and #2328. Snapshots are being generated for Table.test.tsx and tests are running successfully.

### CODE REVIEW

**Comment by priley86** [comment]
hey @jenny-s51 ! Thanks a lot for this. I am reviewing it some more today. Should have more feedback for you soon!

**Comment by jenny-s51** [comment]
@priley86 Looking forward to it -- thank you Patrick!

**Comment by priley86** [comment]
Looking really good to me @jenny-s51! I've rebased these changes in #2360 and tests are now passing 😸 

We will also need to rebase #2554 which just landed.

Still working on some other typescript conversions, but getting closer! One area of improvement here might be converting any of the `any` type references in the tests to types exposed in:

types.tsx (base reactabular table types):
https://github.com/patternfly/patternfly-react/blob/0b2a87b23023fc4e954ba25c1a82330f80ee2aac/packages/patternfly-4/react-table/src/components/Table/base/types.tsx

OR Table.tsx:
https://github.com/patternfly/patternfly-react/blob/0b2a87b23023fc4e954ba25c1a82330f80ee2aac/packages/patternfly-4/react-table/src/components/Table/Table.tsx#L96

Types are in the base `types.tsx` are the base Reactabular types necessary for the existing table. My hope is that types exposed in `Table.tsx` are extended types created by us and exposed as "add-ons" to consumers (which inherit the base types where possible and add our additional API properties). We change this of course as we do API improvements, but this seems the simplest mental mapping at the moment.

Not urgent a.t.m. at all and big thanks for doing this!

**Comment by jenny-s51** [comment]
@priley86 Thank you so much for all your help and feedback on this issue, Patrick! That sounds like a plan -- I'll put this in my to-do list and will plan to revisit the `any` type references as soon as I wrap up the bug-fixes I've been assigned for this sprint.

**Pull request closed without merging**
