### PR TITLE
Bug - Wizard - The appendTo property is ignored by the wizard 

### LINKED ISSUE #8972: Bug - Wizard - The `appendTo` property is ignored by the wizard
**Describe the problem**
`appendTo` and possibly other props are not properly delegated:
(https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/Wizard/Wizard.tsx#L576)

**How do you reproduce the problem?**
Use Wizard with `appendTo` other then document.body

**Expected behavior**
`appendTo` being properly delegated

**Is this issue blocking you?**
Yes

**What is your product and what release date are you targeting?**
ASAP/Summit

**Any other information?**

Discovered by @Hyperkid123

### PR DESCRIPTION
**Pull request by MariaAga**
**What**: Closes #8972

can be tested by replacing the wizard modal example in https://www.patternfly.org/v4/components/wizard#wizard-in-modal with this:
``` js
 <React.Fragment>
      <Button variant="primary" onClick={handleModalToggle} id='tst-id'>
        Show Modal
      </Button>
      <Wizard
        title={title}
        description="Simple Wizard Description"
        descriptionComponent="div"
        steps={steps}
        onClose={handleModalToggle}
        isOpen={isOpen}
        appendTo={() => document.getElementById('tst-id')}
      />
    </React.Fragment>
  ```

### CODE REVIEW

**Comment by MariaAga** [comment]
@nicolethoen why? its a bug in pf4

**Comment by nicolethoen** [comment]
We are not releasing any more changes to v4 outside of business critical blockers that are needed before a product can update to v5. If that's the case here, we'd need to escalate the issue to the leads if we are going to merge it to v4.

**Comment by MariaAga** [comment]
@shaded-enmity is this a business critical blocker?

**Comment by shaded-enmity** [comment]
@MariaAga Thanks for looking into this, we found a workaround (by wrapping the wizard in our own Modal where `appendTo` worked fine) so this is not a business critical blocker.

**Comment by MariaAga** [comment]
Closing since there is no `appendTo` prop in wizard in v5

**Pull request closed without merging**
