### PR TITLE
feat(Wizard): use height token to set height

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: React counterpart to https://github.com/patternfly/patternfly/issues/6457

### CODE REVIEW

**Review by thatblindgeye — CHANGES_REQUESTED** [review]
Doesn't look like passing just a number works anymore, at least based on the basic Wizard example. We should probably update the `height` prop type to just a string, and update any instance of it being used to pass a string/CSS unit value.

The Wizard height doesn't seem to be adjustable inside a modal still, either. @mcoker should React set the `--#{$modal-box}--c-wizard--FlexBasis` token as well?

**Comment by kmcfaul** [comment]
I can update the prop type to string (or fix it so numbers work).

The fix in core isn't in yet, so it's not setting the flex-basis with the value atm.

**Comment by kmcfaul** [comment]
Pending further updates to https://github.com/patternfly/patternfly/issues/6457, this PR will need to updated to use the new `--#{$wizard}--height` token once core is updated in react.

**Review by mcoker — APPROVED** [review]
Other than updating/fixing the width prop type so numbers don't break, lgtm! Agree it should be good once this is updated with the latest core.

**Pull request merged**
