### PR TITLE
fix(Popper): prevented forceUpdate from firing when not necessary

### LINKED ISSUE #9012: Bug - Popper/Dropdown - positioning of popper element is set incorrectly
**Describe the problem**
Followup to a bug found in https://github.com/patternfly/patternfly-react/pull/8868

When a Dropdown has `popperProps={{position: "right"}}` passed in, a bug can be see when opening a dropdown (might require opening the dropdown more than 1 time). The popper gets positioned very briefly too far to the right before snapping into place below the trigger (the positioning is still off by ~12 px from what I noticed).

**How do you reproduce the problem?**
Go to a [Page demo](https://patternfly-react-pr-8868.surge.sh/components/page/react-demos/) from the linked PR surge and try to open the "Ned Username" dropdown a few times:

**Expected behavior**
The popper is positioned correctly when rendered rather than being positioned and then having the position updated after being rendered

**Is this issue blocking you?**
List the workaround if there is one.

**Screenshots**
If applicable, add screenshots to help explain the issue.

**What is your environment?**

**What is your product and what release date are you targeting?**

**Any other information?**

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Closes #9012 

This should resolve the recent visual bug for now. Opened #9089 for investigating an alternate solution.

**Additional issues**:

### CODE REVIEW

**Review by tlabaj — APPROVED** [review]
I am not seeing the behavior anymore.  LGTM

**Comment by tlabaj** [comment]
> I am still seeing the behavior the first time this [composable advanced search menu](https://patternfly-react-pr-9088.surge.sh/components/search-input/react-demos/#composable-advanced-search) is opened. Unless it's a different behavior? Are there possibly a few things we might need to update in demos like this to make sure it's using your change correctly?

I believe that is a different issue.  I will defer to @thatblindgeye.

**Comment by thatblindgeye** [comment]
@nicolethoen @tlabaj it doesn't look like it's caused by the forceUpdate call. I added another conditional to only forceUpdate if `popper.props.role === 'tooltip'` (since that's really the only situation this forceUpdate is for I believe) and the issue still persisted on that search input demo.

**Comment by nicolethoen** [comment]
> @nicolethoen @tlabaj it doesn't look like it's caused by the forceUpdate call. I added another conditional to only forceUpdate if `popper.props.role === 'tooltip'` (since that's really the only situation this forceUpdate is for I believe) and the issue still persisted on that search input demo.

I opened an issue to investigate this 'flashing' behavior we are seeing in components/demos using popper.
https://github.com/patternfly/patternfly-react/issues/9119

**Review by nicolethoen — APPROVED** [review]

**Review by kmcfaul — APPROVED** [review]

**Pull request merged**
