### PR TITLE
feat(Flex): add plain gap spacing

### LINKED ISSUE #9141: Flex - add plain gap spacing
Add plain values to `gap`, `rowGap`, and `columnGap` enums which do not have size (`pf-m-gap`, `pf-m-gap-on-sm`, etc.).

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #9141

Adds the plain/non-size modifiers to gap, row gap, and column gap.

Currently this will not actually apply any styling because react's core package needs a version bump.

### CODE REVIEW

**Comment by kmcfaul** [comment]
Waiting on https://github.com/patternfly/patternfly-react/pull/9133 to fix table

**Comment by kmcfaul** [comment]
Rebased

**Review by nicolethoen — APPROVED** [review]

**Review by thatblindgeye — APPROVED** [review]
React-wise looks good. Not related to this PR, but I'm noticing that using `gapXs` doesn't seem to apply any class/do anything? Though this is present in both React and Core workspaces. @mcoker is the `xs` spacing for gap working as intended?

**Review by tlabaj — APPROVED** [review]

**Comment by mcoker** [comment]
@thatblindgeye nice catch! Sorry I didn't see that comment until after I reviewed - opened a core issue, it should fix the react component once merged https://github.com/patternfly/patternfly/pull/5600

**Pull request merged**
