### PR TITLE
Expandable cells

### LINKED ISSUE #4858: Table - Expanded content is always one cell (<td>)
**Describe the issue. What is the expected and unexpected behavior?**

I have a table that shows an expanded content that aligns with the row headers, I added the cells to the expanded content (a cells inside the row with with the correct parent id).

**Expected behavior**: All the cells show as I configured it.
**Unexpected behavior**: It always takes the first cell and applies a colSpan of the total number of headers.

Notice that this only happens when `onCollapse` is specified on the `Table` component:

**With `onCollapse`**
Screenshot_2020-09-22_10-15-39

**Without `onCollapse` (The way I want to have it minus the toggle)**
Screenshot_2020-09-22_10-14-41

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

`child - 1 with more rows` should have all the rows
 
https://codesandbox.io/s/musing-silence-8bc0z?file=/index.js

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
It could be a bug or by design (I suppose), is blocking some of my work and I don't have any workaround yet.

**What is your product and what release version are you targeting?**
Insights Notifications UI

### PR DESCRIPTION
**Pull request by jschuler**
https://patternfly-react-pr-4899.surge.sh/components/table#compact-expandable

Closes #4858

### CODE REVIEW

**Comment by josejulio** [comment]
When using

**Comment by josejulio** [comment]
This PR + https://github.com/patternfly/patternfly-react/commit/272d1d2f96d9252b70a721f98a9c3ab8a649ae91 (or something to achieve the same) seems to work for me. Thanks!

**Comment by jschuler** [comment]
thanks @josejulio , I'll take a look at your workaround!

**Comment by jschuler** [comment]
Hi @josejulio I cherry-picked your commit, but I ended up changing the code anyways. I noticed that in the case of `fullWidth`, the first cell would get mapped to the "wrong" column (the first user defined column). 
I changed it so that for fullWidth it maps to the correct column, but still grabs the formatters of the first user defined column (so that previous behavior is not broken).
You can also now set `formatters` at the cell level.
Would you mind taking another look at this approach? Thanks again!

**Comment by josejulio** [comment]
> Hi @josejulio I cherry-picked your commit, but I ended up changing the code anyways.

:rofl:   I understand, I'm not familiar with all the code so that was my best guess :)

>  I noticed that in the case of `fullWidth`, the first cell would get mapped to the "wrong" column (the first user defined column).

That's correct, I hope that the workaround helped you to identify the problem or that at least it didn't block you.

> I changed it so that for fullWidth it maps to the correct column, but still grabs the formatters of the first user defined column (so that previous behavior is not broken).
> You can also now set `formatters` at the cell level.

+1

> Would you mind taking another look at this approach? Thanks again!

Of course, Thank you!

> 
> Also, if you have more than one child cell, it will be up to the user to specify the correct `colSpan` values

That's what I had in mind, the user needs to take care of setting the proper `colSpan`, considering the non-user-defined columns.

**Comment by josejulio** [comment]
Is working great for me, thanks!

**Review by redallen — APPROVED** [review]

**Review by redallen — APPROVED** [review]

**Review by redallen — APPROVED** [review]

**Review by kmcfaul — APPROVED** [review]

**Comment by josejulio** [comment]
This closes #4858

**Review by kmcfaul — APPROVED** [review]

**Review by redallen — APPROVED** [review]

**Pull request merged**
