### PR TITLE
fix(deps): updated to the latest core alpha

### PR DESCRIPTION
**Pull request by nicolethoen**
**What**: Closes #

**Additional issues**:

### CODE REVIEW

**Review by gitdallas — APPROVED** [review]

**Review by jenny-s51 — COMMENTED** [review]
This is mostly looking good! However I'm seeing that the popover is appearing behind the nav in this PR in several examples e.g.:
Screen Shot 2023-02-15 at 9 13 09 AM

**Comment by nicolethoen** [comment]
Good catch! that's likely a side effect of the popper defaulting to appending things inline by default. But it is already an existing issue on the v5 branch, so I will open a bug issue to track.

**Comment by nicolethoen** [comment]
https://github.com/patternfly/patternfly-react/issues/8689

**Review by jenny-s51 — APPROVED** [review]
Awesome, thank you for clarifying @nicolethoen and for opening the bug for tracking. In that case LGTM!

**Pull request merged**
