### PR TITLE
fix(dropdown): add focus trap option that allows  close on click

### LINKED ISSUE #1113: PF4 Dropdown close broken
You cannot close the dropdown clicking on it anymore. As a workaround you can click somewhere on a page to close it.

### PR DESCRIPTION
**Pull request by ibolton336**
**What**:
fixes #1113 and #1125

**Additional issues**:

### CODE REVIEW

**Comment by jgiardino** [comment]
Thanks for looking into this, @ibolton336! @kmcfaul Has a similar update in #1014. I posted [feedback](https://github.com/patternfly/patternfly-react/pull/1014#issuecomment-445068500) in that PR when I reviewed her updates using different interaction methods. 

Just to double-check, I also reviewed the preview for this PR. I'm getting the same results in both PRs for touch interaction:
- Testing on an iOS device, I can touch the toggle and collapse the menu. But touching anywhere outside the dropdown toggle or menu does not collapse the menu. Whereas with a mouse, I am able to click anywhere outside the toggle and menu to collapse the menu.

**Comment by ibolton336** [comment]
@jgiardino Thanks Jenn - do you think it would make sense to open a separate issue for handling the mobile bug for the dropdown not closing when touching"outside of the dropdown focus?

**Comment by jgiardino** [comment]
@kmcfaul That sounds good to me. Also, @ibolton336 raised the question of whether the issue with handling touch events on mobile should be a separate issue. It's currently noted in the issue you're working on for PR #1014, but I'm curious if you have thoughts on separating that out.

**Comment by ibolton336** [comment]
created https://github.com/patternfly/patternfly-react/issues/1131 to deal with the touch issues @jgiardino @kmcfaul

**Pull request merged**
