### PR TITLE
add eslint-config-airbnb and stylelint

### PR DESCRIPTION
**Pull request by priley86**
**What**:
Adds eslint-config-airbnb rules and stylelint

@mturley you had some ideas for `react/require-default-props` (and a few misses in vert. nav.), do you want to brush these up?

@michaelkro i am seeing a few additional misses in the Treeview now...do you want to clean those up and send me a patch?

patternfly-react needed a bath w/ some [react-codemod](https://github.com/reactjs/react-codemod) bubbles 🛁 ✨✨✨
 
* disabling jsx-a11y rules and some others for now
* still need to go back and double check the story description sources for changed code

luckily we have some confidence for this kind of change now with Jest tests ;)

@sharvit @jeff-phillips-18 any concerns on these new rules? I think they will help new contributors a lot. 😄 

**Link to Storybook**:
https://rawgit.com/priley86/patternfly-react/airbnb-lint-storybook/index.html

**Additional issues**:

### CODE REVIEW

**Comment by priley86** [comment]
thanks for cleaning this up @michaelkro !

we are down to just three lint issues here (with others disabled):
`react/require-default-props`, `react/default-props-match-prop-types`, and `react/no-unused-state` in the Vert Nav...

@mturley do you mind giving us some direction on those when you get a chance?

**Comment by sharvit** [comment]
@priley86 I love it!
The evolution of the eslint rules is really cool! It is going to help contributors and reviewers!

**Comment by priley86** [comment]
going to take another stab at this soon after chatting w/ @mturley yesterday...

**Comment by priley86** [comment]
* fixed `react/require-default-props`, `react/default-props-match-prop-types`
* updated mock story sources
* ignored vert.nav. jest warnings and other lint warnings for now
* redeployed storybook

I'd like to go ahead merge this when ready @jeff-phillips-18 @sharvit

**Comment by priley86** [comment]
yea... i would definitely be happy to consolidate these configs into our own in the future (however, doesn't seem super pressing at the moment, and being explicit is OK... the configs just build on to each other). 

I am really kicking myself for not pulling in the airbnb config originally now (had used it prior and liked it, but was on the fence back then). Would have saved a lot of work here!  ⏱ ⏰ 

I'm liking the conjunction of these configs a lot though (prettier for code style, standard for es6 base conventions & integration w/ prettier, and now airbnb to further tighten up some other React conventions for default props/method ordering/import ordering/ etc). I disabled the ones I felt were too opinionated and left ones out I don't think we were ready for. Airbnb config is one of the most widely used (and for good reason).

I think for now we just continue to iterate on these lint rules and bring in the a11y rules as we can adopt/review those standards. @jgiardino you may want to take a peak at these when you get some time...

**Comment by priley86** [comment]
closes #235 

filed #236 for further enhancements.

@jeff-phillips-18 mind doing the honors when you have a moment? I am already getting questions about "should i rebase my patternfly-react PR" 😸

**Pull request merged**
