### PR TITLE
chore(deps): Update babel dependencies

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: towards #8003

### CODE REVIEW

**Comment by nicolethoen** [comment]
Do you know what the babel plugin is used for?

**Comment by wise-king-sullyman** [comment]
I'm also curious about that. It seems like we use it for transpiling jsx/tsx for Jest, and set the babel parser as the parser in the eslint-plugin-pf-react, but I don't see any other uses of it in the repo?

**Comment by tlabaj** [comment]
> Do you know what the babel plugin is used for?

Which one?

**Comment by tlabaj** [comment]
> I'm also curious about that. It seems like we use it for transpiling jsx/tsx for Jest, and set the babel parser as the parser in the eslint-plugin-pf-react, but I don't see any other uses of it in the repo?

@wise-king-sullyman I think your question is different from Nicole's.  Babel was used before we converted to TS.  This is just left over for things that still needed it (like the docs when we used Gatsby).  I do have an issue open to remove Babel.

**Review by wise-king-sullyman — APPROVED** [review]

**Pull request merged**
