### PR TITLE
feat(Select): add checkbox variant of the simple select template

### LINKED ISSUE #10112: Create CheckboxSelect template & example

### PR DESCRIPTION
**Pull request by wise-king-sullyman**
Closes #10112

### CODE REVIEW

**Comment by kmcfaul** [comment]
Looks like the snapshot still needs updating / or it's regenerating random ids when it shouldn't?

**Comment by wise-king-sullyman** [comment]
Ah yeah, it's getting a new random id each time now that my GenerateId PR is in, will try to fix. I'm not entirely sure how to have jest mock something that's coming from another package in a monorepo 🤔 

If nothing else I'll just remove the snapshot test for now.

**Comment by wise-king-sullyman** [comment]
I figured out how to mock out GenerateId, but mocking it out with a fixed value caused issues in the non-snapshot tests.

Because of that and difficulty with mocking things out in jest for only specific tests in a file I just moved the snapshot tests to their own file.

**Review by kmcfaul — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]
LGTM

**Pull request merged**
