### PR TITLE
fix(Table): improve a11y for selectable table rows

### PR DESCRIPTION
**Pull request by wise-king-sullyman**
**What**: Addresses part of #6295 

**Additional issues**:

Convenience link: https://patternfly-react-pr-7447.surge.sh/components/table/react-composable/composable-row-click-handler-hoverable--selected-rows/

### CODE REVIEW

**Comment by wise-king-sullyman** [comment]
@thatblindgeye yes, this approach doesn't announce anything when navigating the table cell-by-cell as would intuitively be done when using a screen reader. As you said we could change that, but I feel like having each cell in a row announce if its row is selected or not would be a less than ideal user experience.

I think that the best fix for that issue would probably be for me to revise the demo to have the table announce rows are selectable as you suggested.

I'll update that so that we can see how well it ends up working. If anyone else has thoughts about this I'd love to hear them 🙂

**Review by thatblindgeye — COMMENTED** [review]
With my previous comments kept in mind, I feel like something along the lines of the latest update might be one of the better ways to go about letting users know via screen reader that the table has rows that are selectable without getting overly verbose.

One issue with hardcoding the caption as it is is that passing in your own Caption component will visually render, but it doesn't get announced by screen reader. If instead of a caption element being applied when `hasSelectableRows` is true, a plain `div` with an ID is used to add to the `table` element's `aria-describedby` attribute, the same problem occurs where the `caption` element gets ignored by VO (since the table is being described by that `div` now).

After toying around, adding a `div class="pf-screen-reader">...</div>` *inside* the `caption` element allows the actual visible caption to be announced and the hidden instructions to be announced. This may not be any closer to a perfect solution, but in theory this could allow a consumer to pass in a custom visible caption to the table and still have screen reader instructions hidden visually (we could even potentially allow passing in custom instructions if needed).

Here's what the DOM looks like after I toyed around a bit:

hidden div inside a table caption element

**Comment by wise-king-sullyman** [comment]
@thatblindgeye when attempting to add a div inside of the caption like you suggested I'm running into an issue where the div itself pushes the table down.

image

I think I've found a solution that works around this while still enabling consumers to add content in to the caption by only placing the assistive text inside a hidden div when additional caption content is passed and otherwise rendering the assistive text directly in the caption. I should have this approach working and pushed shortly.

**Comment by wise-king-sullyman** [comment]
Also in the last commit I added a `hasSelectableRowCaption` prop to make this new behavior opt-in and prevent breaking changes. I've created #7473 to remove this prop in the next breaking change release to enable this behavior to be automatic in the future.

**Review by thatblindgeye — COMMENTED** [review]
Things are sounding how I had them when editing things via dev tools, so I'm glad that was able to be done without that shifting.

With the new props added, I think an issue that could arise is if the Caption component is also passed in as the first child of the Table as it results in that double caption element issue from occurring. Would adding these props to the Caption component work do you think?

**Review by kmcfaul — APPROVED** [review]

**Review by mattnolting — APPROVED** [review]
Seems like a good enhancement to me. I'm not sure how we make the entire row selectable in VO?? But this is definitely an improvement. 👍

**Pull request merged**
