### PR TITLE
Rebase v6 branch

### LINKED ISSUE #9831: rebase v6
**Describe the enhancement or change**
rebase v6 branch

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #9831

### CODE REVIEW

**Review by mfrances17 — APPROVED** [review]
LGTM, verified mine

**Review by jenny-s51 — APPROVED** [review]
Exciting to review a Pentafied PR! 

Verified my changes in the Table and Primary Detail demos and they look good for the most part... I'm seeing some visual discrepancies with menu toggles but it seems like those will be corrected as part of https://github.com/patternfly/patternfly-react/issues/9413.

Noting those discrepancies below for tracking purposes, otherwise LGTM 👍

Screenshot 2023-11-21 at 9 43 09 AM
Screenshot 2023-11-21 at 9 28 59 AM
Screenshot 2023-11-21 at 9 53 55 AM

**Review by wise-king-sullyman — APPROVED** [review]
My changes look good

**Review by kmcfaul — APPROVED** [review]
My changes look good

**Pull request merged**
