### PR TITLE
Move from Less to Sass, create dist directory.

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
**What**:
Updating to use Sass rather than less. Though there are no component specific less files yet, this sets up the repository to use Sass.

Creates a dist directory to contain the Javascript, Sass files, and compiled CSS file. Removes the lib directory from being created.

**Link to Storybook**:
No storybook changes.

**Additional issues**:
Updated to require patternfly w/ sass 3.31.0

### CODE REVIEW

**Comment by priley86** [comment]
@jeff-phillips-18 I'm excited to have Sass! Great job pulling this together... 👍 

Couple questions:
* would it be ok to gitignore dist now that we are changing from lib?
* can we go ahead and publish your storybook here (notes in Readme). I would like to review it for differences from the Less consuming Storybook.

**Comment by jeff-phillips-18** [comment]
@priley86 Agreed, I will add dist to .gitignore

I will get a storybook link here shortly.

**Comment by priley86** [comment]
awesome - @jgiardino would <3 help reviewing the Storybook once it's up...

**Comment by jeff-phillips-18** [comment]
Added storybook link

**Pull request closed without merging**
