### PR TITLE
chore: update breadcrumb dropdown item arrow to work in RTL

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly-react/issues/9587

This may not be a great way to do this, but these are basically drillup items in the breadcrumb menus.

### CODE REVIEW

**Review by thatblindgeye — COMMENTED** [review]
One issue with using the `direction` prop for the icon is that it's also going to set some other code internal to MenuItem that isn't needed:

https://github.com/patternfly/patternfly-react/blob/1d539173f5eef0a9ea17bccb7810aeb6fc177054/packages/react-core/src/components/Menu/MenuItem.tsx#L249-L265

When it's used in Menu, it's also used for a drilldown type of menu, where the item leads to another sub-menu or a parent menu. For these breadcrumbs, it's more just selecting an item within a list that has been truncated to save space, rather than leading to a sub or parent menu.

This may be a case to use the modifier class to mirror the icon in the examples.

**Comment by thatblindgeye** [comment]
If we wanted to utilize the `direction` prop to render the icon correctly, we could update the logic inside of Menu around the code lines I linked above so that we're only reassigning the `drill` variable if `direction && (onDrillIn || onDrillOut)`.

Overall I dont think I feel too strongly if we want to get this in, though. Unless a user is also passing either of those onDrill callbacks in it may not ultimately matter.

**Comment by mcoker** [comment]
@thatblindgeye we could close this PR (and the [core PR](https://github.com/patternfly/patternfly/pull/5924/files)) and leave the issues open, and we can work on it after the release or in a breaking change release if that's needed. WDYT? On the core side, I think it's just going to be updating the examples to wrap the icon in the `menu__item-toggle-icon` element.

**Comment by thatblindgeye** [comment]
@mcoker Unless anyone else feels it's urgent to fix I'd be fine with that. As it is it could be considered more the example issue rather than an issue with the component.

**Comment by wise-king-sullyman** [comment]
That sounds like a great plan to me as well.

**Review by thatblindgeye — APPROVED** [review]

**Review by wise-king-sullyman — APPROVED** [review]

**Review by tlabaj — COMMENTED** [review]
Did we decide we were nit going to make any changes to fix example code to work with RTL since this would be consumer provided?  Maybe this belongs in handbook.

**Comment by mcoker** [comment]
@tlabaj great question 😅. We have updated a few examples, most cases from what I recall are with code that really should be built into our component. For random icons and things included as filler in components, I believe we've just left all of those alone.

This PR is an example of something a menu item should support. Another example is the expand all [icon used in a `<ToolbarItem variation="expand-all">`](https://github.com/patternfly/patternfly-react/blob/2953b78290b3baee6cf506303c88dfc5ab9d0329/packages/react-core/src/demos/DataListDemo.md?plain=1#L112-L134).

There are issues for both of these to update our components to support making RTL work natively

* The issue this PR addresses - https://github.com/patternfly/patternfly-react/issues/9653
* Toolbar expand-all icon https://github.com/patternfly/patternfly-react/issues/9641

**Review by tlabaj — APPROVED** [review]

**Pull request merged**
