### PR TITLE
docs(Card): add utilization card demos

### LINKED ISSUE #6301: Utilization card 1

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #6301, #6302, #6303, #6304

Adds the 4 utilization card demos.

### CODE REVIEW

**Comment by kmcfaul** [comment]
TODO: update demos to use real charts instead of images

**Comment by kmcfaul** [comment]
Updated demos to use real `Chart` components over images. They're not 100% exact to the image but very close.

**Comment by mcarrano** [comment]
These are looking b good with the actual charts embedded. @mceledonia perhaps you can also take a look.

**Review by nicolethoen — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]

**Comment by evwilkin** [comment]
@kmcfaul @tlabaj should we wrap the `ChartGroup` in these examples in a fixed-width container similar to [this example](https://www.patternfly.org/v4/charts/sparkline-chart#basic)?  Currently the charts grow/shrink and overlap the surrounding text based on the window size:

Screen Shot 2021-09-30 at 11 35 09 PM
:

**Comment by tlabaj** [comment]
> @kmcfaul @tlabaj should we wrap the `ChartGroup` in these examples in a fixed-width container similar to [this example](https://www.patternfly.org/v4/charts/sparkline-chart#basic)? Currently the charts grow/shrink and overlap the surrounding text based on the window size:
> 
> Screen Shot 2021-09-30 at 11 35 09 PM
> 
> :

@evwilkin  Probably.  I would be interested to hear what core dev thinks.

**Review by mcoker — APPROVED** [review]
LGTM

**Review by mceledonia — APPROVED** [review]
Looking good, thanks!

**Review by dlabrecq — APPROVED** [review]

**Pull request merged**
