### PR TITLE
fix(popover): forwarded focus to close button with VoiceOver click

### LINKED ISSUE #4210: Popover interaction inconsistency
**Describe the issue. What is the expected and unexpected behavior?**

Popover doesn't forward focus correctly to close btn unless you use the enter key to launch it. 

VoiceOver (VO) screen readers use `cmd+option+space` as the primary way of selecting a thing. It's not uncommon to also use the enter key, but VO instructs the former when you focus on a clickable element. What I see is that a blind user wouldn't know the Popover was correctly launched when they use the `cmd+option+space` bar to launch it. The popover content is, by design, outside of the normal page content flow. Because the popovers are not live regions, nothing is announced other than the fact that the button is now "expanded" which is just a change in state of the button - not an indication or announcement of the new dynamic content. When new dynamic content appears on the screen, we generally want to send focus to it

In this state, the user hears the popover is expanded so they know its been launched, but unable to navigate to the content except through the rotor menu. This means they have to "figure out" that they need to press enter to get it to forward the VO cursor into the popover so that they can read the content like normal, or switch to another method of navigation to find the new content.

`cmd+options+space` fires a _click_ event on the focused element. If we can listen for that also, it could bring further alignment between the sighted and accessible experiences. 

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Click a [Popover host element](https://www.patternfly.org/v4/documentation/react/components/popover#basic), notice it doesn't send focus to the Popover close button. Then, keyboard focus that same element, and press enter on your keyboard. Notice the focus is sent to the dynamic content.

Screen Shot 2020-05-07 at 10 54 41 AM

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?** Considering we generally want alignment between sighted and unsighted experiences, I'm inclined to call this a bug.

**What is your product and what release version are you targeting?** Ongoing PF development

Ping @jessiehuff @mcarrano

### PR DESCRIPTION
**Pull request by evwilkin**
**What**: Closes #4210 

This PR:
- Forwards focus to close button within popover when triggering with VoiceOver click
  - `cmd+F5` on a Mac to enable VO, then `ctrl+option+space` on button to trigger Popover (see [Activate a link or form control](https://dequeuniversity.com/screenreaders/voiceover-keyboard-shortcuts#vo-mac-navigation))
- Removes the optional `onTriggerEnter` function passed as a prop to Popper
  - This function was duplicating the `onTriggerClick` functionality but targeted only at the `Enter` key, but that key press was triggering both functions so this seems to be unnecessary.

### CODE REVIEW

**Comment by evwilkin** [comment]
@jschuler I know you've worked with Popper a lot and I believe wrote the code I removed here, WDYT?  Want to make sure there's not an edge case I'm unaware of to keep the `onTriggerEnter` function.

**Review by nicolethoen — COMMENTED** [review]
It seems to me that that in this PR and in production I cannot get VO focus into the popover when it opens. VO focus stays on the toggle, even though it reads the contents of the popover. That is fine except in the example of [close-popover-from-content-controlled](https://patternfly-react-pr-6660.surge.sh/components/popover/react/close-popover-from-content-controlled/) where I really struggled to figure out how to use VO to hit the controlled close button.

**Review by jschuler — APPROVED** [review]
@evwilkin Not sure why i added this :) seems to all work well without it!

**Review by jessiehuff — COMMENTED** [review]
I agree with Nicole's comment in that there are a few that don't switch focus for me (close popover from content (controlled) and the advanced example). However, I don't think that they currently switched focus through keyboard either looking at org. I'm ok with solving these here or in another issue/PR. I'm open to what you guys think! :)

**Review by tlabaj — APPROVED** [review]
LGTM

**Pull request merged**
