### PR TITLE
fix(Pagination): Styling discrepancy with HTML version

### LINKED ISSUE #2903: Styling of Pagination component is incorrect
The styling of the "items per page" select menu is not correct. This should not use standard Select list styling as shown below.

Core implementation is correct. See

### PR DESCRIPTION
**Pull request by SpyTec**
**What**: Fix differences with upstream. This makes Pagination be identical to HTML variant

**Additional issues**: Fixes #2903 

~~Note, work in progress. Trying to figure out the best approach for fixing the font size and padding of the dropdown button as well as the font color.~~ Fixed

image

### CODE REVIEW

**Comment by SpyTec** [comment]
Trying to change DropdownToggle in OptionsToggle to OptionsMenuToggleWithText doesn't help much. HTML variant has `button.pf-c-options-menu__toggle-button`, but I'm unable to see how we can get this without the `.pf-c-dropdown__toggle` being added

**Comment by SpyTec** [comment]
I've managed to sync everything with HTML version. One note to keep in mind, to get around applying `.pf-c-dropdown__toggle` class to the dropdown I added a `DropdownContext.Provider` with toggleClass value of a space which is shown in the outputted HTML. 

image

**Comment by mcoker** [comment]
Looks like `.pf-c-options-menu` is nested in another `.pf-c-options-menu`, and in the top level `.pf-c-options-menu`, there is a `#pagination-options-menu-top-label` element with "Items per 
 page:" that we don't have in core. 

Screen Shot 2019-09-17 at 1 58 29 PM

"Items per page" is an `aria-label` on the toggle button in core, and the `.pf-c-options-menu__menu` element's `aria-labelledby` is set to the ID of the toggle button.

Also looks like `.pf-c-options-menu__menu-item` is listed twice on the menu items

Screen Shot 2019-09-17 at 2 00 44 PM

And for the `.pf-c-options-menu__menu-item-icon`, can we just apply that class directly to the `<svg>` and remove the `<i>`?

Screen Shot 2019-09-17 at 4 11 23 PM

**Comment by SpyTec** [comment]
Fixed all but the `.pf-c-options-menu__menu-item-icon`. Putting on the SVG itself didn't work. Personally I think it would be better to keep it to an `<i>` as it is in core so that the elements don't change

**Comment by mcoker** [comment]
@SpyTec thanks! I opened https://github.com/patternfly/patternfly-next/issues/2297 re: the SVG/icon class.

This looks good to me, although I'm still seeing this element in the react component that isn't in the core examples:

Screen Shot 2019-09-23 at 4 20 36 PM

And in the react component, `.pf-c-options-menu__toggle-button` has `aria-label="Select"` and in core, we have `aria-label="Items per page"`.

@jessiehuff or @jgiardino can you confirm if we need to make updates there?

**Comment by jgiardino** [comment]
Replying to @mcoker's [comment above](https://github.com/patternfly/patternfly-react/pull/2904#issuecomment-534291671), there is a related open issue to the aria label applied to the toggle: https://github.com/patternfly/patternfly-react/issues/1882

However, when I compare the html in core to the html in react, they are different, and the solution we want is dependent on which html we're using. So that issue might need to be updated depending on that. 

The main difference I'm seeing is that in core, the text that displays in the toggle "x-y of z items" is not part of the button. But in react, it is.

**Comment by jgiardino** [comment]
Doh! I was looking at the current version of the react component, and not the fixes included in this PR. 😜 

This hidden span was an artifact of the old way we were labelling the toggle. It can be removed.
`<span id="pagination-options-menu-top-label" hidden="">Items per page:</span>`

That issue I mention above is still relevant, but not a blocker for this PR.

**Comment by SpyTec** [comment]
Fixed the last bit with `Select` aria-label so it's now `Items per page`. Also removed old labelling `<span id="pagination-options-menu-top-label" hidden="">Items per page:</span>` as suggested

**Pull request merged**
