### PR TITLE
fix(Select/Dropdown): updated autofocus to false by default in v6

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Towards #10393 

We have a followup to investigate [improving the focus logic/styling overall](https://github.com/patternfly/patternfly-react/issues/11025) post-v6

**Additional issues**:

### CODE REVIEW

**Review by adamviktora — APPROVED** [review]
Thanks for doing this update!

I have some feedback which can be done as a followup:

1. Noticed that all of the descriptions of Typeahead examples have duplicated sentences (in the `examples/Select.md` file), possibly caused when merging v5 to v6

2. Now after the change, the menu items are not easily accessible with keyboard. I know that's the reason why autofocus was introduced in the first place, and although the autofocus now defaulting to false is a great visual update, I think we should still support some kind of keyboard accessibility.

I made an [update in this commit](https://github.com/patternfly/patternfly-react/commit/710ab0a81e5b28dd3b4e763c4fd01763c369e305) to the basic Select example to react on arrow up / down press, when the toggle is focused. (I don't know if it is making too many assumptions about what to do on arrow up/down event, but it is just an example). Here is an example of its behaviour:

https://github.com/user-attachments/assets/7aa8765b-0858-4741-a351-4a3d4979f431


It would require us to update all other examples though, but I think (given that e.g. the typeahead examples already have a lot of code in them) we can do that and make it a part of the Select (and Dropdown) Templates.

I know there is a followup to investigate, so let's say the commit could be one of the possible approaches (or maybe not and the logic should be encapsulated within the Select itself, this is just an idea)

**Comment by thatblindgeye** [comment]
@adamviktora I think I did something similar locally at some point when tinkering around, though it was done as part of the base Menu/Select/Dropdown logic (rather than in each example code). May depend whether we would want to at least show a way consumers could handle focus management themselves in the mean time (since if a consumer opts to not autofocus for  a non-typeahead, they'll have to do handle it themselves), or if we want to wait and see what potentially refactoring the logic internally may look like.

@kmcfaul one issue with that may be that it depends where the menu is appended; with the document body appending then Tab may not go into the menu itself

**Comment by adamviktora** [comment]
@thatblindgeye I prefer doing it as part of the base Menu logic.

> if we want to wait and see what potentially refactoring the logic internally may look like

I prefer this, but it depends how long will it be, so we don't ship a half-working version now. But if the followup to fix it is a high priority, then I am absolutely ok with it.

**Comment by thatblindgeye** [comment]
The current plan is:

1. Merge this PR as-is
2. Create a followup to add logic internal to Select, Dropdown, and MenuContainer to handle up/down arrow keys with ability to customize this
3. Re-evaluate whether https://github.com/patternfly/patternfly-react/issues/11025 is still applicable

**Review by dlabaj — APPROVED** [review]
LGTM

**Pull request merged**
