### PR TITLE
feat(DualListSelector, SearchInput): use SearchInput in DLS, add type prop to SearchInput

### LINKED ISSUE #7977: Dual list selector: Search should use search input component

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #7977

Updates DualListSelector to internally build a SearchInput.
Adds `type` prop to SearchInput to match DualListSelector's initial input type.

### CODE REVIEW

**Review by thatblindgeye — APPROVED** [review]
Looks good! Something that would be worth a followup since it might be a little out of scope here is that the Search Input should be passed `onClear` callback so that a focusable "clear" button renders (right now an icon is rendered when you type into the DLS search, but you can't focus it)

I can open a followup for that, unless you'd want to try sneaking it into this PR.

**Comment by kmcfaul** [comment]
I can sneak an update for that in. The default behavior will call `onChange` with an empty string and may be overridden with `onSearchInputClear`. 

Though I'm a little confused about how some of these search callbacks are meant to work, because several are hidden from the props documentation with `@hide`, and it doesn't look like `onSearch` (which is visible) is used anywhere. Is the new prop I added `onSearchInputClear` actually necessary if a user is meant to ignore all these props and use `searchInput` instead for composable dual list selectors?
@nicolethoen

**Comment by mmenestr** [comment]
This looks great! The only thing I'd suggest is adding an empty state if the search doesn't match any of the options? I realize that is an oversight from when I designed this. But maybe just a small or xs empty state using the text and icon here: https://www.patternfly.org/v4/components/empty-state#no-match-found

**Comment by nicolethoen** [comment]
> 

That may be a pretty significant enhancement to the Dual list selector at this point. I am in the process of a dual list selector re-work and if you open an issue to incorporate an empty state, I can include it with the re-work

**Comment by mmenestr** [comment]
@nicolethoen sounds good, just opened this: https://github.com/patternfly/patternfly-react/issues/8080

**Review by tlabaj — APPROVED** [review]

**Review by mcoker — APPROVED** [review]
lgtm! 🥳

**Comment by kmcfaul** [comment]
Rebased conflict

**Pull request merged**
