### PR TITLE
feat(bullet-chart): add Bullet Chart component

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
affects: patternfly-react

ISSUES CLOSED: #347

**Link to Storybook**:
https://rawgit.com/jeff-phillips-18/patternfly-react/bullet-chart-storybook/index.html?selectedKind=patternfly-react%2FData%20Visualization%2FCharts&selectedStory=Bullet%20Charts

Requires upgrade to patternfly 3.48.0

### CODE REVIEW

**Comment by priley86** [comment]
this looks excellent from a React perspective and very closely resembles the design in the [test page](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/bullet-charts.html) in PF Core.

I don't have a lot of feedback from a JS perspective other than you might add a few more tests for the 
BulletChartAxisTic, BulletChartLegend, BulletChartLegendItem, BulletChartRange, BulletChartValue. The only one which might require interaction is the BulletChartValue (to get the tooltip) so I would use the `mount` method (instead of shallow)... the others can be targeted directly and snapshotted w/ different props to achieve full coverage it seems.

screen shot 2018-05-31 at 2 15 03 pm

Only other feedback would be, do we have the expectation that this chart should be made accessible phase one (i don't see any aria/role attributes)?

Very nice work @jeff-phillips-18 !

**Comment by jeff-phillips-18** [comment]
Updated tests to gain coverage.

@jgiardino any accessibility concerns here?

**Comment by priley86** [comment]
tests look good to me!

**Comment by jgiardino** [comment]
I haven't spent much time reviewing charts. But we did review the solution shown on this test page with the a11y participants from GMS, and it seemed to work really well: https://rhelements.github.io/cp-accordion.html

On the page, expand the section "Which book has the most pages?" and there's a donut chart. The donut chart is wrapped with a `<figure>` element, and the last element inside `<figure>` is [`<figcaption class="sr-only">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figcaption) which includes a description of the chart and has the `.sr-only` class so that it's visually hidden. 

Would it be simple enough to create a text template that maps the values of the bullet chart to a text description of the chart? I'm happy to test this too to see how it behaves.

**Comment by jeff-phillips-18** [comment]
I'd like to move ahead with this component and add the accessibility features as a follow on. I feel there is more needed from UX in order to come up with textual descriptions of the values/ranges/thresholds depicted in the bullet chart.

**Comment by jgiardino** [comment]
That sounds reasonable to me.

**Comment by abonas** [comment]
@jeff-phillips-18 it looks awesome, thank you!

**Pull request merged**
