### PR TITLE
fix(VncConsole): prevent running initialization code more than once (#8373)

### LINKED ISSUE #8373: Bug - [VncConsole] - [Release 4.49.8 broke VncConsole causing random disconnects]
**Describe the problem**
VncConsole from extensions is currently broken. It flickers, (component re-renders unnecessarily) and finally disconnects causing 'Connection lost' messages in console.

**How do you reproduce the problem?**
This is pretty hard to reproduce on the docs or demo-app page. I reproduce by building the console package, package it locally in a tar, and testing it against cockpit-machines.

**Any other information?**
Although this change seems correct, https://github.com/patternfly/patternfly-react/commit/e0240737eb6abb091c3ac83c3de8fb68420d7578#diff-bf986d61c9b208d09c9cff07c052d59c216f3f9f5abb28fd745813052de6ec27 , we are assuming that this caused the problem. These functions will change whenever the component updated. This will cause the code in useEffect to rerun, which is unwanted, and causes the above mentioned behavior. 

A correct solution would be to use useCallbac for the functions used inside the useEffect. Shortly tried it without much success yet.

### PR DESCRIPTION
**Pull request by KKoukiou**
The functions that were on the dependency list of the useEffect hook got redefined each time the component got updated, resulting in the component's initialization code, from within the useEffect hook, to be running more than once.
That was unwanted behavior and the useCallback wrappers should prevent it.

Closes #8373

### CODE REVIEW

**Comment by martinpitt** [comment]
@KKoukiou : So good to see you back! :heart:

**Comment by nicolethoen** [comment]
Do the useCallback hooks still work as intended when you update them to include the missing dependencies flagged by the github linter?

**Comment by KKoukiou** [comment]
> Do the useCallback hooks still work as intended when you update them to include the missing dependencies flagged by the github linter?

Where is the linter output? Did not see it, sorry. Genrally all functions used inside the hooks need to be defined with the useCallback, if defined outside the hooks otherwise there might be unnecessary re-renders.

**Comment by KKoukiou** [comment]
@nicolethoen can you please take a look :) ?

**Comment by KKoukiou** [comment]
@nicolethoen thanks for the pointer. I now see the errors. I will fix them and notify you again.

**Comment by nicolethoen** [comment]
@KKoukiou is this ready for re-review?

**Review by nicolethoen — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]

**Pull request merged**
