### PR TITLE
feat(Dropdown): add badge toggle variant

### LINKED ISSUE #5361: Add collapsible breadcrmb variant
Introduce a collapsible variant of the Breadcrumb to implement core updates here: https://github.com/patternfly/patternfly/pull/3797

Consumer must be able to specify now many levels to show before collapsing via a prop. Default behavior will always be to not collapse the breadcrumb.

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #5361, #5506, #5333

Adds badge toggle variant to Dropdown.
Adds badge dropdown demo to Breadcrumb + wrapper.
Adds Breadcrumb dropdown to Drilldown Menu demo.

### CODE REVIEW

**Comment by kmcfaul** [comment]
Currently this is done manually, putting however many desired items in the dropdown when it is built. This gives the user finer control over how many breadcrumbs are shown before vs. after the dropdown as well as how many items are in the dropdown. The `BreadcrumbItem` has a flag `isDropdown` indicating that a badge dropdown is contained for spacing styles, rather than wrapping the entirety of a Dropdown and expecting those props + props to control number of items/order.

**Review by mcarrano — APPROVED** [review]
Thanks for the explanation @kmcfaul . I will defer to your judgement on this. In that case I approve!

**Review by nicolethoen — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]
LGTM!

**Review by mcoker — APPROVED** [review]
L🤩TM!

**Pull request merged**
