### PR TITLE
Gatsby v2

### PR DESCRIPTION
**Pull request by jschuler**
Upgrade to gatsby v2

### CODE REVIEW

**Comment by jschuler** [comment]
Still looking at a prod build failure

**Comment by jschuler** [comment]
Should work now

**Comment by michaelkro** [comment]
@dgutride @tlabaj we're still looking into a FOUC issue.  To see, visit the surge test page, and after it loads, refresh the page.

It is even more apparent if you visit a component page first, and then refresh

**Comment by tlabaj** [comment]
@michaelkro Do you think we should put "Do not merge" Label on this until it is ready?

**Comment by michaelkro** [comment]
@tlabaj yes, I think that's a good idea, at least for now :)

**Comment by jschuler** [comment]
Please use this prod build, i think the pr site has a possible caching issue
http://gaudy-frog.surge.sh

**Comment by jschuler** [comment]
Thanks for your help and contributions @michaelkro

**Pull request merged**
