### PR TITLE
docs(Backdrop): remove "with spinner" example

### LINKED ISSUE #8447: Backdrop - Remove "With Spinner" example
Want to remove the example of a Backdrop with a spinner (https://www.patternfly.org/v4/components/backdrop#with-spinner) as this is something we don't intend to support.

See discussion here: https://github.com/patternfly/patternfly/pull/5248

### PR DESCRIPTION
**Pull request by adamviktora**
**What**: Closes #8447

### CODE REVIEW

**Review by mcarrano — APPROVED** [review]
Looks good to me. Thanks @adamviktora !

**Review by tlabaj — COMMENTED** [review]
Do you mind updating the prop decription for class name while you are in the component.  IT says "additional classes added to the button". It should be "Additional classes added to the backdrop"

**Review by nicolethoen — APPROVED** [review]
LGTM - should be good to merge after addressing Titani's note

**Review by tlabaj — APPROVED** [review]
lgtm

**Pull request merged**
