### PR TITLE
Add component property to Flex, Gallery and Grid and the subitems. 

### PR DESCRIPTION
**Pull request by KKoukiou**
Relevant to #5967

### CODE REVIEW

**Review by nicolethoen — DISMISSED** [review]
code looks good - just want to check with pf core and @mcoker that this doesn't have unforeseen consequences.

**Review by mcoker — DISMISSED** [review]
LGTM! Thanks @KKoukiou. My only comment is I'm not sure what the examples should show - to use `<List/ListItem>` as the components or just `ul/li`. These 2 examples look a little weird, though it's a valid use case. 

Screen Shot 2021-09-09 at 9 47 11 AM
Screen Shot 2021-09-09 at 9 47 03 AM

**Comment by KKoukiou** [comment]
@mcoker I happy to change the example code if we have any other idea here! I think most people will use directly the string though, like 'ul' and not specify the React PF component name.

**Comment by mcoker** [comment]
@KKoukiou cool! I think the string would be better. That will match the core examples, too.

**Review by kmcfaul — APPROVED** [review]

**Review by nicolethoen — APPROVED** [review]

**Review by mcoker — APPROVED** [review]
🥳

**Pull request merged**
