### PR TITLE
chore(DragDrop): deprecate in v6

### LINKED ISSUE #10096: V6 - Drag drop - Deprecate drag drop
**Describe the enhancement or change**
A clear and concise description of the request. What is the expected outcome?
Deprecate drag drop in v6 branch.  Move it to deprecated directory.

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #10096

@tlabaj Do we want to move any of the old DragDrop examples? Currently there are examples using the now deprecated DragDrop on DataList and DualListSelector (current and next). Should we move those onto DragDrop's `React deprecated` page now? We do have examples for DataList/DualListSelector using the newer `DragDropSort` but they only live on the `React next demos` page currently.

### CODE REVIEW

**Comment by tlabaj** [comment]
> @tlabaj Do we want to move any of the old DragDrop examples? Currently there are examples using the now deprecated DragDrop on DataList and DualListSelector (current and next). Should we move those onto DragDrop's `React deprecated` page now? We do have examples for DataList/DualListSelector using the newer `DragDropSort` but they only live on the `React next demos` page currently.

Can we update those examples to use the new drag and drop?  Or are you asking if the even belong in the examples pages to begin with?

**Comment by kmcfaul** [comment]
@tlabaj Bit of both. We have updated examples for those two components already, but they currently live in the Drag and Drop page's demo tab. I mostly wonder if we want to move those old examples to the deprecated Drag and Drop page, and if we want to move the new examples to the respective component pages.

**Comment by kmcfaul** [comment]
If we're not sure we can probably open a docs followup to update the documentation to let this PR in

**Comment by kmcfaul** [comment]
Per working session discussion, I'm adding a deprecated flag to the current examples and opening https://github.com/patternfly/patternfly-react/issues/10196 to follow up updating the documentation with the new demos.

**Review by thatblindgeye — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]

**Pull request merged**
