### PR TITLE
WIP: Canvas pattern

### LINKED ISSUE #14: Component - Canvas Pattern
Implement components that provide the following UI elements associated with the [Canvas pattern](http://www.patternfly.org/pattern-library/content-views/canvas-view/#/overview):

- Canvas
- Canvas Toolbar
- Canvas Top Aligned Toolbox
- Canvas Properties Panel

Acceptance Criteria:

- When rendered, the component matches the examples in the PatternFly Pattern Library (see link above)
- Should implement drag/drop and zoom behavior associated w/ the Canvas pattern

### PR DESCRIPTION
**Pull request by priley86**
*Update*: No longer being actively worked on. Leaving this PR up for reference only at this point.

This PR starts the [Patternfly Canvas Pattern](http://www.patternfly.org/pattern-library/content-views/canvas-view/#/design) implementation.

Running storybook demo: 
https://rawgit.com/priley86/patternfly-react/canvas-projects-rawgit/index.html?knob-Label=Danger%20Will%20Robinson%21&selectedKind=Canvas&selectedStory=canvas%20with%20top-aligned%20toolbox&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs

* Adds `Canvas`, `CanvasLayout`, `CanvasToolbar`, `CanvasTopAlignedToolbox`,  `CanvasNode`, & associated drag/drop components
* Adds [react-dnd](http://react-dnd.github.io/react-dnd/docs-overview.html)
* Adds [react-dnd-mousebackend](https://github.com/zyzo/react-dnd-mouse-backend) due to issue w/ the HTML5 drag/drop API and SVG elements (described in [#395](https://github.com/react-dnd/react-dnd/issues/395))
* Adds `react-patternfly.css` for temporary new React component css rules
* Adds Jest snapshot tests for Canvas components
* Droppable Canvas Nodes

Todo:
- [ ] Design / CSS review
- [ ] Add node connections and node actions support
- [ ] Add `CanvasPanel` component implementation

[Source](https://github.com/priley86/patternfly-react/tree/canvas-projects)

Closes #14

### CODE REVIEW

**Comment by priley86** [comment]
After reviewing the css/svg rendering some more, this has a lot of improvements to make. We can make the rendering of nodes / images much more flexible and respect variable sizes.

Will revisit this again post-Summit. @andresgalante @bleathem @jgiardino

**Comment by priley86** [comment]
referencing [#660](https://github.com/patternfly/patternfly/pull/660). The upstream CSS/HTML is being reviewed there first in PF Core...

**Comment by jeff-phillips-18** [comment]
@priley86 Should this be closed at this point?

**Comment by priley86** [comment]
@jeff-phillips-18 yes, fine with closing this. We can revisit Canvas in the future...

**Pull request closed without merging**
