### PR TITLE
fix(Popper): add display contents to wrapping divs

### LINKED ISSUE #8277: Bug - Popper - `removeFindDomNode` props could cause layout issues
**Describe the problem**
Take Tooltip as an example, I have the following use of a tooltip.
```
<span className="odh-card__title-supported">
  {odhApp.spec.displayName}
  <Tooltip content={`${ODH_PRODUCT_NAME} certified and supported`}>
    <img
      className={supportedImageClasses}
      src="../images/CheckStar.svg"
      alt={`${ODH_PRODUCT_NAME} certified and supported`}
    />
  </Tooltip>
</span>
```
`odh-card__title-supported` has the following CSS style:
```
display: flex;
align-items: center;
```

which results in the following:
Screen Shot 2022-10-21 at 12 08 53 PM

However, if I add `removeFindDomNode` to `Tooltip`, I will get the following:
Screen Shot 2022-10-21 at 12 08 19 PM

I checked the HTML and found a div was added which caused the layout issue, the old layout:
Screen Shot 2022-10-21 at 12 10 24 PM

The new layout:
Screen Shot 2022-10-21 at 12 11 05 PM

**How do you reproduce the problem?**
See the description.

**Expected behavior**
The style should keep the same before and after I apply `removeFindDomNode` to `Tooltip`.

**Is this issue blocking you?**
I can add <Bullseye> to the `children` of `Tooltip` to make it work.

**Screenshots**
If applicable, add screenshots to help explain the issue.

**What is your environment?**

**What is your product and what release date are you targeting?**
Open Data Hub

**Any other information?**

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #8277

This should resolve the layout issues that can occur due to the new `div`.

### CODE REVIEW

**Review by thatblindgeye — COMMENTED** [review]
It looks like `display: contents` has some a11y issues: [MDN display-box article](https://developer.mozilla.org/en-US/docs/Web/CSS/display-box#accessibility_concerns)

I tested with VoiceOver in the preview build and I was still able to get things announced/navigated to as expected, though I'd like to test out in JAWS and NVDA as well to see how it is there.

I also tried just throwing in a couple of buttons into an example and gave one `style={{display: "contents"}}`, and that helps show what can happen (it no longer becomes navigable via keyboard)

**Comment by nicolethoen** [comment]
When doing a little more reading [in this blog](https://hidde.blog/more-accessible-markup-with-display-contents/), it looks like the browsers are fixing the issue with `display:contents`
```
Update August 2018: the bug was fixed in Firefox 62

Update March 2021: the bug was fixed in Chrome 89

Update May 2022: initial fix was announced for Safari Technology Preview 144

Update June 2022: reflected that bug fix will be in Safari 16

Update July 2022: [Adrian Roselli's latest tests in Safari](https://adrianroselli.com/2022/07/its-mid-2022-and-browsers-mostly-safari-still-break-accessibility-via-display-properties.html)
```

**Review by thatblindgeye — APPROVED** [review]
@nicolethoen thanks for that link! Tested with both JAWS and NVDA and it looks like the behavior remains the same in this PR's preview build compared to the live site. And what I had tried last Friday with the button thing probably isn't a practical use case for the `display: contents` (tried wrapping a button in a div and applying that style to the div instead, and the button worked fine).

EDIT: Per my comment at https://github.com/patternfly/patternfly-react/pull/8316#pullrequestreview-1170575546, looks like there is actually another visual bug that comes up now.

**Comment by kmcfaul** [comment]
Brought back the older popper update check to handle the popper when content changes. I'm not sure why the newer check suddenly doesn't handle a content change (neither strict mode method works with it) but there shouldn't be an impact adding the old check back in.

**Review by nicolethoen — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]

**Pull request merged**
