### PR TITLE
Move items in main nav

### LINKED ISSUE #8777: Workspace - move pages per v5 website IA
Follow up on: https://github.com/patternfly/patternfly-org/pull/3416

Want to move/rename pages that are used to populate the PF website. Affected pages include:

Release notes
Demos:

* Card view
* Composable menu
* Date and time picker
* Filters
* Password generator
* Password strength
* Primary-detail

Group menu and form components using tertiary nav. See https://github.com/patternfly/patternfly-org/issues/3425 and https://github.com/patternfly/patternfly-org/issues/3426

### PR DESCRIPTION
**Pull request by mcarrano**
Reorganizes items it the workspace towards improved findability on patternfly.org. Tertiary expandable navigation is now used to group items in the component nav. A new "Patterns" section is introduced to replace Demos. Specific changes include the following:

* Group Date and Time related components together in the Components navigation.
* Move menu related components into a group named "Menus"
* Move form related components into a group names "Forms."
* Group File Upload and File-Upload multiple into a new group named File Upload and rename components to Simple and Multiple File upload.
* Move password strength, password generator, and composable menu demos to Components and rename Demos section to Patterns where the remaining full page demos can live.

Closes #8777

### CODE REVIEW

**Comment by mcarrano** [comment]
@nicolethoen @tlabaj @evwilkin these changes in the React repo are now ready for review.

**Comment by evwilkin** [comment]
@mcarrano it looks like the "File upload - multiple" demo needs to be updated similar to the examples file you've already changed, as it isn't grouped within the new "File upload" subsection
- https://github.com/patternfly/patternfly-react/blob/v5/packages/react-core/src/demos/MultipleFileUploadDemos.md

Also for @tlabaj - for the components renamed in the navigation (File upload => Simple file upload, File upload - multiple => Multiple file upload) should we also rename the exported components in the code?  I ask because this would require follow-up React issues to change the name, along with codemods to update imports & usages for consumers.  Or do you think going to "Simple file upload" to view docs for the "File upload" component makes sense - these would be the only 2 component docs to not match the component names in that case.

**Comment by nicolethoen** [comment]
> rename the exported components in the code

I believe we were not going to do that at this time. We were renaming the documentation for clarity, but leaving actual exported component names as they were. @tlabaj was that your understanding?

**Comment by tlabaj** [comment]
> > rename the exported components in the code
> 
> I believe we were not going to do that at this time. We were renaming the documentation for clarity, but leaving actual exported component names as they were. @tlabaj was that your understanding?

Yes,  I thought we agreed to leave component names as is.

**Comment by evwilkin** [comment]
@tlabaj @nicolethoen thanks!

@mcarrano this looks good with your last update to move that demo, it just looks like there are 2 merge conflicts that need to be resolved before we're able to merge.

**Comment by mcarrano** [comment]
@evwilkin I believe that the two conflicts are because those components got deprecated after I opened this branch and moved to the /deprecated folder. Does that make sense? How do I fix that?

**Review by evwilkin — APPROVED** [review]
LGTM

**Review by evwilkin — APPROVED** [review]
LGTM

**Review by tlabaj — CHANGES_REQUESTED** [review]
> ... Specific changes include the following:
> 
> * Group Date and Time related components together in the Components navigation.

Should `Calander month` be included in with these

> * Move menu related components into a group named "Menus"

I only see one tab in `Dropdown`.   I should see the "React Deprecated as well.

**Comment by mcarrano** [comment]
@tlabaj Good catch regarding Calendar Month. I will move that to Date and Time. The other issue was fixed with my last commit.

**Review by nicolethoen — APPROVED** [review]

**Comment by mcarrano** [comment]
@evwilkin @nicolethoen @tlabaj Moved Calendar month to Date & Time. Please give a final review. Thanks.

**Comment by nicolethoen** [comment]
Should we move `Timestampe` into the `Date and time` section while we are doing this?

**Comment by mcarrano** [comment]
> Should we move Timestamp into the Date and time section while we are doing this?

@evwilkin and @tlabaj what do you think?

**Comment by tlabaj** [comment]
> Should we move Timestamp into the Date and time section while we are doing this?

Calendar month is used in the Date and time picker demos and that is why I called that one out to be moved.  The timestamp is really independent of what is currently under the "Date and time picker" Nav item.  Given the name of the Nav item, I don't know that I would look for it there.

**Review by tlabaj — APPROVED** [review]
LGTM

**Pull request merged**
