### PR TITLE
test(components): Add tests to Filter and Sort selectors 

### PR DESCRIPTION
**Pull request by boaz1337**
**What**:

Added more tests to `Sort` and `Filter` + fixed a bug in `Sort`.

**Link to Storybook**:

:no_entry_sign:  None
 
**Additional issues**:

:no_entry_sign:  None

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
The design is to not show the category when there is only one category. For both filter and sort.

@serenamarie125

**Comment by boaz1337** [comment]
@jeff-phillips-18 that's what I thought too but what if I have the following scenario:
a list view of hosts that have IP, hostname and operating system and I would like to filter only by IP in one page and by hostname or operating system in other page while using the same Toolbar component.

**Comment by jeff-phillips-18** [comment]
We would need to make it optional with the current functionality being the default. This change would break existing applications that don't expect to see the single category.

**Comment by boaz1337** [comment]
@jeff-phillips-18 in a second thought it seems like there are way to handle my use case without changing the code: putting a placeholder in the filter input text field.

However, since this PR includes unit tests, I thought it would be a shame to close this.
Thus, I am changing the commit title and updating the tests to pass with the current logic.

**Comment by serenamarie125** [comment]
@boaz1337 & @jeff-phillips-18 I'm a bit confused.  I can't do a UX approval if i don't see screenshots, or understand what to test.  Can someone include the following:
- is this a fix for PF3 or PF4 ? 
- where would i look in the storybook to test the fix
- include a screenshot of what this looks like without a category for each scenario

Thanks!

**Comment by boaz1337** [comment]
@serenamarie125 
- it's a fex for  PF3
- [here](https://rawgit.com/boaz1337/patternfly-react/sorterror/index.html?selectedKind=patternfly-react%2FForms%20and%20Controls%2FSort&selectedStory=Sort%20test&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) is what I get when the `currentSortType` is "" and `sortTypes` is:
```js
[
            {
              id: 'name',
              title: 'Name',
              isNumeric: false
            },
            {
              id: 'address',
              title: 'Address',
              isNumeric: false
            },
            {
              id: 'birthMonth',
              title: 'Birth Month',
              isNumeric: true
            },
            {
              id: 'car',
              title: 'Car',
              isNumeric: false
            }
          ]
```

and [here](https://rawgit.com/boaz1337/patternfly-react/sortfixed/index.html?selectedKind=patternfly-react%2FForms%20and%20Controls%2FSort&selectedStory=Sort%20test&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) it's fixed.

**Pull request merged**
