### PR TITLE
feat(Accordion): pulled in Penta updates

### LINKED ISSUE #9851: Accordion: Consume Penta tokens
Follow up to core PR https://github.com/patternfly/patternfly/pull/6058

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Closes #9851 

Confirmed that using the latest alpha locally fixes the border color mismatch between this PR and the core v6 staging.

If we want to wait until https://github.com/patternfly/patternfly-react/pull/9877 gets merged and pulled into the v6 branch, I can update the new example + tests that were added, otherwise the updates shouldn't be too difficult if done during the merge of main into v6.

**Additional issues**:

### CODE REVIEW

**Review by andrew-ronaldson — APPROVED** [review]
LGTM, thanks!

**Review by nicolethoen — COMMENTED** [review]
This looks like the sort of update that might need a codemod, right? can we open a codemod issue to track?

AccordionContent - `isHidden` was removed.
AccordionToggle - `isExpanded` was moved to AccordionItem.

Anything else?

**Review by nicolethoen — APPROVED** [review]

**Review by srambach — APPROVED** [review]
LGTM

**Review by mcoker — APPROVED** [review]
👍👍

**Review by wise-king-sullyman — APPROVED** [review]

**Pull request merged**
