### PR TITLE
fix(TextInput,TextArea, FormSelect): changed form control div to a span

### LINKED ISSUE #9333: TextInput, FormSelect, TextArea - update wrapping div to span
re: https://github.com/patternfly/patternfly/pull/5703

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #9333

### CODE REVIEW

**Review by srambach — COMMENTED** [review]
I think that this is missing also changing the sub-component parts to be spans rather than divs. E.g. `pf-v5-c-form-control__utilities` and `pf-v5-c-form-control__icon` should also be spans.

**Comment by gitdallas** [comment]
should the formControl divs within `TreeViewSearch` and deprecated `Select` also be updated?

**Comment by tlabaj** [comment]
> should the formControl divs within `TreeViewSearch` and deprecated `Select` also be updated?

Good question.  
@srambach @mcoker should the Tree view be using a `TextInput` rather than an input wrapped by formControl span?


https://github.com/patternfly/patternfly-react/blob/fd920e5469a24f6f677ed4a849e5b6f8f0349e61/packages/react-core/src/components/TreeView/TreeViewSearch.tsx#L32-L41

**Comment by srambach** [comment]
> > should the formControl divs within `TreeViewSearch` and deprecated `Select` also be updated?
> 
> Good question. @srambach @mcoker should the Tree view be using a `TextInput` rather than an input wrapped by formControl span?
> 
It seems like that should match Search (or use search?), but I think it's out of scope for this PR, since the purpose here is to remove divs from within form controls so that they can be placed in places where only phrasing content is allowed.

I'm ok with merging this and adding a follow on issue if it's agreed that tree view needs to be updated.

**Review by srambach — APPROVED** [review]

**Review by gitdallas — APPROVED** [review]

**Review by kmcfaul — APPROVED** [review]

**Comment by mcoker** [comment]
+1 to what @srambach. We should update it eventually to use `<TextInput>` so that updates to the form control component are reflected here, too. Though would we use `<TextInput>` or `<SearchInput>` like the menu uses? https://github.com/patternfly/patternfly-react/blob/f038112114d5416ef598135f46ee04ecf33f8d92/packages/react-core/src/components/Menu/examples/MenuFilteringWithSearchInput.tsx#L48-L52

**Review by thatblindgeye — APPROVED** [review]

**Comment by tlabaj** [comment]
> +1 to what @srambach. We should update it eventually to use `<TextInput>` so that updates to the form control component are reflected here, too. Though would we use `<TextInput>` or `<SearchInput>` like the menu uses?
> 
> https://github.com/patternfly/patternfly-react/blob/f038112114d5416ef598135f46ee04ecf33f8d92/packages/react-core/src/components/Menu/examples/MenuFilteringWithSearchInput.tsx#L48-L52

@mcoker I think you are right.  It should be search input.  It was missed when we made the updates.  We would need to wait to breaking change release to update that.  I can open an issue...

**Review by wise-king-sullyman — APPROVED** [review]

**Pull request merged**
