### PR TITLE
Fixes #28 - npm install error

### LINKED ISSUE #28: Npm install fails on prepublish
prepublish script runs **babel** command, however if babel is not installed globally it fails, since devDependencies have not yet been installed.

a quick solution may be:
https://github.com/npm/npm/issues/10366
`"prepublish": "npm install --ignore-scripts && npm run build",`
or to have travis run the build task on merge, which seems more natural to me.

### PR DESCRIPTION
**Pull request by matanwerbner**
Trying to npm install patternfly-react currently fails unless babel-cli, babel-presets-stage2 are globally installed

running build on **prepublish** executes before any devDependencies are installed, and so babel-cli is not found.

as a workaround, running npm install before build (--no-scripts prevents recursion) fixes it.

### CODE REVIEW

**Comment by priley86** [comment]
hey @matanwerbner , thanks for providing this. Would you mind recommitting your patch using `npm run commit`? This will ensure your commit is formatted semantically and can be automatically published via Travis.

**Comment by matanwerbner** [comment]
@priley86 ok, does it do --amend?

**Comment by jtomasek** [comment]
The description is slightly misleading. `npm install patternfly-react` works fine, `npm run prepublish` fails unless you have run `npm install` to get a project dependencies installed. I think this is expected behavior as building the project assumes that you have it correctly setup first (`npm install`). Semantic-release automation does not seem to have a problem with this either and publishes package at npm just fine.

Can you please describe exact usecase you're trying to resolve with this change? Applying it probably does not hurt though. 

What if some of the devDependencies have scripts which are required to run to install them properly? Won't `--ignore-scripts` potentially cause problems in build?

**Comment by matanwerbner** [comment]
I was not able to consistently reproduce this issue (npm install patternfly-react fails), if ill be able to ill let you know.
The issue is this: 
scripts in "prepublish" will currently run upon npm install, which is not the desired outcome.
This is true for npm versions < 4 (current TLS is 3.10.9) and there is much discussions online about prepublish (https://docs.npmjs.com/misc/scripts), and i am thinking if there is a better way to build the package.
If we are ok with requiring npm > 4 then all is good.
We may want to consider "prepublishOnly"...

**Comment by jtomasek** [comment]
Thanks for clarification, I think I understand the problem better now. I've been able to reproduce the issue when installing patternfly-react from local repository (using npm 2 and 3) `npm install ~/patternfly-react`. Althought I am not able to reproduce this anyhow when installing patternfly-react from npm registry. Which means travis/semantic-release do not hit the issue when preparing the package.

**Comment by matanwerbner** [comment]
I know, it happens sometimes to me on regular npm install too, not sure if it's a cache issue or just weired behavior :)

**Comment by priley86** [comment]
@matanwerbner are we OK to close this issue / PR then? Just following up...

**Comment by matanwerbner** [comment]
Sure, go ahead. Hope this does not bite us in the future :)

**Comment by priley86** [comment]
ok - thanks for reporting and following up. let us know if you see this again...

**Pull request closed without merging**
