### PR TITLE
docs(Card): Added nested card demo

### LINKED ISSUE #6381: Nested cards with expanded toggle on right

### LINKED ISSUE #6382: Nested cards with expanded toggle

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #6382 Closes #6381

### CODE REVIEW

**Review by mcarrano — COMMENTED** [review]
This looks good @tlabaj . Does this also pull in the compact card changes or will that require follow-up? cc @mcoker

**Review by mcoker — CHANGES_REQUESTED** [review]
Looks good but the nested cards use a plain card variation that removes the card's box shadow.

**Review by redallen — CHANGES_REQUESTED** [review]
Demo works, but you have a failing lint check and `violations: duplicate-id-aria` for the demo

**Review by nicolethoen — APPROVED** [review]

**Review by redallen — DISMISSED** [review]
Thanks @tlabaj !

**Review by redallen — APPROVED** [review]

**Comment by mcarrano** [comment]
Looks good @tlabaj But I am seeing some slight spacing differences when I toggle between core and React. That may just be a function of the different workspaces. Not sure. @mcoker can you verify?

**Comment by mcoker** [comment]
@mcarrano it LGTM. The toggle button icon shifts a little bit, but it's because the icons in core and react are a bit different (font awesome vs SVG)

https://user-images.githubusercontent.com/35148959/136051628-ac42f525-40dc-406f-9b96-6867ac0f2d60.mov

**Review by mcoker — APPROVED** [review]

**Review by mcarrano — APPROVED** [review]
Thanks for the explanation @mcoker . I'm good then.

**Pull request merged**
