### PR TITLE
feat(Wizard,ClipboardCopy): add OUIA props to WizardNav, WizardNavItem, ClipboardCopy

### LINKED ISSUE #7767: [enhancement] - [add ouiaId properties to WizardNav, WizardNavITem, ClipboardCopy and the Modal close icon]
There's a few elements that we would like add tags to for user tracking and automation, however there's a few React components that don't appear to offer properties to set a customized ID.  It'd be great if these 3 components offered a `ouiaId` property:

* WizardNav
* WizardNavItem
* ClipboardCopy

Additionally while the Modal component does accept a custom automation ID however the close icon uses a generated ID.  It'd be nice if there was a way to either specify the OUIA ID for the Modal close icon or if the Modal component could perhaps use value built off of the `ouiaId` property it receives.

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #7767

Adds OUIA props to WizardNav, WizardNavItem, and ClipboardCopy.
Adds OUIA props to the above respective docs pages.

ModalCloseButton does have the OUIA props extended, and the passed ouiaId is set to `{ouiaId}-ModalBoxCloseButton`. Will that be sufficient or should this be changed to directly reflect the ouiaId without the added suffix? @gashcrumb

### CODE REVIEW

**Comment by nicolethoen** [comment]
@kmcfaul @tlabaj should we also expose these OUIA props in the docs?

**Review by tlabaj — APPROVED** [review]
LGTM

**Comment by kmcfaul** [comment]
@nicolethoen I should have added in the OUIA props to Wizard and ClipboardCopy, unless I'm missing something as part of that.

**Comment by nicolethoen** [comment]
@kmcfaul I am not sure - is there an ouiaId prop on clipboard copy now? i don't see it in the prop tables like I do for Alert in [this props table](https://www.patternfly.org/v4/components/alert/#alert)

**Comment by kmcfaul** [comment]
@nicolethoen Ah you're right I missed adding the props to the table, I only extended the interface. Updated.

**Review by nicolethoen — APPROVED** [review]

**Pull request merged**
