### PR TITLE
feat(NotificationBadge): refactor to use status buttons for penta

### LINKED ISSUE #9811: (Notification badge): Consume Penta tokens
Follow up to core issue https://github.com/patternfly/patternfly/issues/5990

### PR DESCRIPTION
**Pull request by wise-king-sullyman**
**What**: Closes #9811 

**Additional issues**:

Core is removing the notification badge, this PR internally replaces our notification badge with the button component while keeping the external API the same.

Convenience link: https://patternfly-react-pr-10020.surge.sh/components/notification-badge

### CODE REVIEW

**Review by nicolethoen — COMMENTED** [review]
It looks like there is an extra `pf-m-start` class on the notification badges in the first example causing the icon to be slightly misaligned to the left?
Screenshot 2024-01-18 at 4 09 56 PM

**Comment by wise-king-sullyman** [comment]
@nicolethoen I think that might be more of a bug with button, but there are some ways we could resolve it NotificationBadge side.

I could pass the icon as a child of the Button when there isn't a count, and to the `icon` prop when there is so that things are properly spaced. How that will work with children of NotificationBadge could be tricky though.

I wonder if we should cut the flexibility of NotificationBadge back in penta since if a more custom solution is needed consumers can just customize the stateful Button themselves 🤔

**Review by andrew-ronaldson — APPROVED** [review]
LGTM, thanks

**Review by nicolethoen — APPROVED** [review]

**Review by thatblindgeye — APPROVED** [review]
May be worth making a codemod just to warn consumers about the markup change

**Review by lboehling — APPROVED** [review]
lgtm!

**Review by thatblindgeye — APPROVED** [review]
CSS wise 👍🏼

**Pull request merged**
