### PR TITLE
feat(avatar): add border prop

### LINKED ISSUE #5717: Avatars for light and dark background
Create new variants of the Avatar component that work well on either light or dark backgrounds. See core implementation here: https://github.com/patternfly/patternfly/pull/3990

### PR DESCRIPTION
**Pull request by redallen**
**What**: Closes #5717

**Additional issues**:

### CODE REVIEW

**Review by KKoukiou — DISMISSED** [review]

**Review by nicolethoen — COMMENTED** [review]
We need to update tests

**Review by nicolethoen — APPROVED** [review]

**Review by dlabrecq — APPROVED** [review]

**Review by tlabaj — CHANGES_REQUESTED** [review]
Can you pleas add to demo app and add integration test.

**Review by kmcfaul — APPROVED** [review]

**Comment by redallen** [comment]
I don't think testing a prop that just adds a class is worth an integration test, but sure!

**Comment by tlabaj** [comment]
Just adding to demo is fine.

**Review by kmcfaul — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]
Looks great!

**Pull request merged**
