### PR TITLE
feat(Popper, misc): remove removeFindDomNode flag and set to default

### LINKED ISSUE #7872: breaking change: Popper - remove findDOMNode by default
The flag `removeFindDomNode` should be removed and Popper should use the wrapping divs with their refs by default (updating the overall DOM of popper). This will also allow us to remove `FindRefWrapper` entirely.

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #7872

Removes the `removeFindDomNode` prop and makes the wrapping divs default. This PR also includes the small fix for the divs being considered for CSS (though that specific change is also in a separate PR to get in for v4).

### CODE REVIEW

**Review by nicolethoen — APPROVED** [review]
this LGTM pending the decision about whether display:contents is an accessibly acceptable solution in your other PR

**Comment by kmcfaul** [comment]
@mcoker Is there anything you can see on the CSS side that having the extra div would impact the layout? I do have the style `display: contents` applying.

**Comment by mcoker** [comment]
@kmcfaul sorry for the delay. I don't see anything on the CSS side that would case this. However I noticed that when you scroll, the position fixes itself, so I'm wondering if there is some kind of calculation popper is triggering on scroll that isn't being triggered when the content is updated?

**Review by thatblindgeye — APPROVED** [review]

**Review by nicolethoen — APPROVED** [review]

**Comment by tlabaj** [comment]
@mcoker we can merge if this looks good to you.

**Review by mcoker — APPROVED** [review]

**Pull request merged**
