### PR TITLE
feat(Login): use children for loginmainfooterlinksitem

### LINKED ISSUE #10100: Login - remove link component in LoginMainFooterLinksItem
Use children directly instead & update examples.

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #10100

Removes inner structure of `LoginMainFooterLinksItem` and updates examples to pass buttons directly.

### CODE REVIEW

**Comment by kmcfaul** [comment]
@mcoker There's a `pf-v5-svg` class that core uses to square up the svg icons that I included here, otherwise the icons are a bit larger and the buttons look rectangular. This class' prefix didn't seem to get updated to `v6` so I'm unsure if we're intentionally using it and if I should just remove it?

**Comment by mcoker** [comment]
@kmcfaul it looks good to me, though there are [react-icons](https://react-staging.patternfly.org/icons) for all of the footer icons - should we use those instead? `GoogleIcon`, `GithubIcon`, `DropboxIcon`, `FacebookSquareIcon`, `GitlabIcon`

**Review by mcoker — APPROVED** [review]
LGTM! Though looks like we can swap the hardcoded SVGs with the react-icons equivalents 👍

**Review by tlabaj — COMMENTED** [review]
Is there a code mod issue for this one?

**Comment by kmcfaul** [comment]
Waiting for alpha release before merging.

**Review by wise-king-sullyman — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]

**Pull request merged**
