### PR TITLE
fix(togglegroup): remove dividers, light variation, add compact

### PR DESCRIPTION
**Pull request by mcoker**
**What**: Closes https://github.com/patternfly/patternfly-react/issues/5761

**Additional issues**: From core issue https://github.com/patternfly/patternfly/pull/4054/files

### CODE REVIEW

**Comment by mcoker** [comment]
@tlabaj updated!

**Review by redallen — APPROVED** [review]
@mcoker knows React? :tada: :1st_place_medal:

**Review by mcarrano — APPROVED** [review]
Looks great from a UX perspective. Thanks @mcoker !

**Review by redallen — APPROVED** [review]
Looks Godlike To Me.

**Pull request merged**
