### PR TITLE
chore(empty, alert, select): clean errors in tests

### PR DESCRIPTION
**Pull request by boaz0**
fixing warning in alert, empty state and select unit tests

closes # #5352

### CODE REVIEW

**Review by kmcfaul — APPROVED** [review]

**Review by jessiehuff — APPROVED** [review]
LGTM!

**Review by kmcfaul — APPROVED** [review]

**Comment by tlabaj** [comment]
@boaz can you please link the associated issue.  thanks

**Comment by boaz0** [comment]
@tlabaj sure no problem.

**Comment by boaz0** [comment]
closes #5352

**Pull request merged**
