### PR TITLE
feat(icons): use absolute import paths

### PR DESCRIPTION
**Pull request by redallen**
**What**: Closes #3448 , towards #3155

**Additional issues**:
Related: #3476

### CODE REVIEW

**Comment by karelhala** [comment]
@redallen I don't think this issue fixes https://github.com/patternfly/patternfly-react/pull/3449 am I right?

**Comment by redallen** [comment]
You're right @karelhala , I meant #3448 .

**Comment by redallen** [comment]
@dlabrecq I talked to you offline about this, but the plan is to add a linting rule soon to catch ESM imports to `@patternfly/react-icons`.

**Comment by redallen** [comment]
I fixed the merge conflicts and would love reapproval from @evwilkin @kmcfaul and @dlabrecq !

**Pull request merged**
