### PR TITLE
SerialConsole: Use xterm v4

### LINKED ISSUE #2912: Update to xterm v4 in console
[Currently](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-3/react-console/package.json#L41) version 3.3.0 is used, which is a year old release and since then there has been some interesting improvements and fixes.

Now is also available version 4.0.0 which changes quiet a few things around.
One of them is the fact, that addons are now separate packages, so [fit](https://www.npmjs.com/package/xterm-addon-fit) package cannot be loaded as [is now](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-3/react-console/src/SerialConsole/XTerm.js#L5).

This block [cockpit](https://github.com/cockpit-project/cockpit) team from upgrading to xterm-4.0.0 since patternfly react console needs xterm < 3.14

### PR DESCRIPTION
**Pull request by marusak**
**What**: Use xterm v4 in SerialConsole. Fixes #2912

### CODE REVIEW

**Comment by marusak** [comment]
Can I get a review on this? (not really sure who to ping, maybe @mareklibra as he has some commits in serial console)

**Comment by jeff-phillips-18** [comment]
code changes look ok to me but I don't really know this package all that well. If @mareklibra is OK with it then I am.

**Comment by marusak** [comment]
yes, users needs to move xterm to 4.0.0. But otherwise there should be no other visible change nor they do not need to adjust their code in any way.

**Comment by dlabrecq** [comment]
As long as it's not considered a breaking change, I believe it would be ok.

**Comment by martinpitt** [comment]
Sorry for nagging, but is there anything else to be done on our (@marusak 's) side? This seems approved and all tests passed. Thanks!

**Comment by jeff-phillips-18** [comment]
Should this be a breaking change? Regardless, the commit message needs to be updated for semantic release. If breaking, then please use `major` otherwise `feat` would do.

**Comment by marusak** [comment]
> Should this be a breaking change?

I answered this in a previous comment

> Regardless, the commit message needs to be updated for semantic release. If breaking, then please use major otherwise feat would do.

Can this be done on squashing? If it can, then I don't need to push force and then tests don't need to re-run. Otherwise I can edit the commit message (`feat(SerialConsole): Use xterm v4` would work, I guess?)

**Comment by jeff-phillips-18** [comment]
Sorry, I guess my question is, if adopters are forced to move to xterm 4.0.0 then wouldn't this be a breaking change?

**Comment by marusak** [comment]
> Sorry, I guess my question is, if adopters are forced to move to xterm 4.0.0 then wouldn't this be a breaking change?

I don't know what is defined as breaking change. It requires users to update xterm to `4.0.0`, but otherwise they should not notice any difference and they do not need to update their code (unless they use xterm on other places as well).

**Comment by jeff-phillips-18** [comment]
I'm going to flag this for a major release as it would break consumers if they pull this change and do nothing else.

**Pull request merged**
