### PR TITLE
fix(emptyState): add small/large modifiers

### LINKED ISSUE #1677: Add small/large props to empty state
https://github.com/patternfly/patternfly-next/pull/1475

not sure if you would want someone to be able to set a custom `width` or `max-width`, too?

### PR DESCRIPTION
**Pull request by boaz0**
**What**:

closes #1677 

//cc @dlabaj @mcoker 

**Additional issues**:

Don't merge this yet till:
- [x] `@patternfly/patternfly@^2.0.0` is updated

### CODE REVIEW

**Comment by boaz0** [comment]
Thanks @tlabaj I will rebase soon and let you know when it is ready for your review again.

**Comment by boaz0** [comment]
Hi @tlabaj / @dlabaj 

Change is ready for review

Thanks.

**Comment by christiemolloy** [comment]
The body text isn't wrapping within its parent in the React demo (for all 3 examples).. see Core vs React:

Screen Shot 2019-04-10 at 1 45 46 PM
Screen Shot 2019-04-10 at 1 45 53 PM

**Comment by redallen** [comment]
That's likely not an issue with this PR, but with the new docs. You can compare it against the preview that has the first doc change [here](https://1659-pr-patternfly-react-patternfly.surge.sh/patternfly-4/components/emptystate/). I'll add it to #1724 which is tracking the broken doc site styles.

**Comment by boaz0** [comment]
Thanks a bunch @redallen @christiemolloy, @dlabaj and @tlabaj  :bowing_man: :clap:

**Pull request merged**
