### PR TITLE
feat(Text): Added support for visited link styling

### LINKED ISSUE #5857: Visted style for links
re: https://github.com/patternfly/patternfly/pull/4067

In the content component, you can apply `.pf-m-visited` to either a `.pf-c-content` block (to style all links in the block), or an `<a>` element in a `.pf-c-content` (to style an individual link), and visited styling will be applied when a link has been visited.

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #5857

**Additional issues**:

### CODE REVIEW

**Review by nicolethoen — COMMENTED** [review]
I could be wrong, but I imagined that the flag would mean 
'if this link has been visited, it will be styled with the visited styles' 
rather than 'style this link as though it has been visited' 
is that true?

**Review by mcoker — CHANGES_REQUESTED** [review]
This looks great to me when defining a link, but we also support `.pf-m-visited` on `.pf-c-content`. The use case is when you have a lot of links in a content block that you want to have visited styling. Can you add support for this on `<TextContent>`, too?

**Comment by mcoker** [comment]
@nicolethoen yep that's true. If the prop is set and the browser has determined that you've visited the link, you get the visited styling (purple text)

**Comment by nicolethoen** [comment]
> @nicolethoen yep that's true. If the prop is set and the browser has determined that you've visited the link, you get the visited styling (purple text)

Sweet - I think the distinction should be made clear in the comment/docs

**Review by mcoker — APPROVED** [review]
Nice!!

**Review by nicolethoen — APPROVED** [review]

**Review by kmcfaul — APPROVED** [review]

**Review by dlabrecq — COMMENTED** [review]
LGTM

**Pull request merged**
