### PR TITLE
fix(FilterSidePanelCategoryItem): fix typings

### LINKED ISSUE #5139: FilterSidePanelCategoryItem has wrong type
**Describe the issue. What is the expected and unexpected behavior?**
Reference:
https://github.com/patternfly/patternfly-react/blob/master/packages/react-catalog-view-extension/src/components/FilterSidePanel/FilterSidePanelCategoryItem.tsx#L7

Trying to use FilterSidePanelCategoryItem in `tsx`, getting the following tserror:

`Type 'X' is missing the following properties from type 'FilterSidePanelCategoryItemProps': context, setState, forceUpdate, render, and 3 more.`

Looking at the typings
`export interface FilterSidePanelCategoryItemProps extends React.Component<Checkbox>`

looks wrong. AFAIK it should be `React.HTMLProps<HTMLDivElement>`

### PR DESCRIPTION
**Pull request by glekner**
**What**: Closes #5139

### CODE REVIEW

**Review by redallen — CHANGES_REQUESTED** [review]
This may cause breakage in [Openshift](https://github.com/openshift/console/blob/master/frontend/public/components/utils/tile-view-page.jsx#L809) since the `title` prop on `<Checkbox>` gets passed to an `<input>` which I think makes more since than passing it to an outer `<div>`.

If you could add a title prop that gets passed to the `<Checkbox>` still this could be non-breaking for Openshift which is the only other known consumer of react-catalog-view-extension.

**Comment by glekner** [comment]
done @redallen

**Review by redallen — APPROVED** [review]
LGTM!

**Review by kmcfaul — APPROVED** [review]
lgtm!

**Pull request merged**
