### PR TITLE
Docs(storybook): update to storybook 3.4

### LINKED ISSUE #221: Update to Storybook 3.3
Ensure all `@storybook` dependencies can be updated to 3.3.

I noted the following problems w/ constants as propTypes when attempting this in the past (however it appears there is a workaround).
https://github.com/patternfly/patternfly-react/pull/147#issuecomment-355323113

It would be nice if someone can follow up on this on react-docgen notation.

### PR DESCRIPTION
**Pull request by priley86**
**What**:
So I saw this announcement yesterday.... and I just had to try it out...
https://medium.com/storybookjs/storybook-3-4-early-access-964dee3d978e

It looks like our previous issues w/ 3.3 have already been resolved by react-docgen/SB 3.4. There is a few other deprecations living around it would be nice to address in this PR once SB 3.4 releases (soon).

I'm loving the new StorySource and Viewport Addons. Thoughts on adding these in once we upgrade?

**Link to Storybook**:
Running 3.4 "rc" demo:
https://rawgit.com/priley86/patternfly-react/storybook-3-4-storybook/index.html

**Additional issues**:

closes #221 

~Allen Edit~
~[yah can find the latest of this deployed here ](https://AllenBW.github.io/patternfly-react/)~ no more storybook for you, its needed elsewhere

### CODE REVIEW

**Comment by AllenBW** [comment]
AWESOME!! In support of future upgrade(ability?) might be a good idea to [get ahead of the impending `.addWithInfo` deprecation  ](https://github.com/storybooks/storybook/tree/master/addons/info#deprecated-usage)... use `withInfo()` from the same package instead

**Comment by priley86** [comment]
was thinking this exact same thing...@AllenBW... somehow you read my mind... telapathic skills you have ... 
image

do you want to shepherd this PR for us (and watch out for the release and do any additional upgrade prep)? Happy to hand this one over :)

**Comment by AllenBW** [comment]
@priley86 musta been cuz we met that max threshold for meeting mind meld 😆  (LOVE DA PIC)

oh heck yeah, am an expert replace all'er 😏 will tack that work to this one outstanding

**Comment by priley86** [comment]
whoaaa another big win i just saw after reverting my branch to current 3.2... 3.4 loads **noticeably** faster!! ⭐️

**Comment by AllenBW** [comment]
gosh the *PRESSURE* OK OK OK  its almost done, just gotta... do the things... almost there... should have this branch repushed by eod

😆 😋 🍭 💃

**Comment by Rohoover** [comment]
@AllenBW You're hilarious :) Enjoying this convo here.

**Comment by AllenBW** [comment]
@priley86 I'd update the storybook... but since #254 is out there... and using the storybook... 😭

**Comment by AllenBW** [comment]
Hmm if this one is gonna sit, will hold off on resolving conflicts till its ready to move 👍

**Comment by priley86** [comment]
they released `3.4.0-rc3` a few days ago... should be any day now for `3.4.0`...
https://github.com/storybooks/storybook/releases

**Comment by AllenBW** [comment]
OH yeah yeah yeah hah, of course, official release 🤦‍♂️ apologies 😏

**Comment by AllenBW** [comment]
> they released 3.4.0-rc3 a few days ago... should be any day now for 3.4.0...

😏 😆 

Updated original pr note to include this storybook version deployed...

Also resolved commit conflicts, updated `"@storybook/addon-storysource": "^v3.4.0-rc.4",`

**Comment by priley86** [comment]
looks great 👍 

i'm OK to merge this early if others are... it looks like the only thing remaining is an [issues w/ storyshots](https://github.com/storybooks/storybook/milestone/10) which we don't currently use.

**Comment by priley86** [comment]
I can't approve this since it's technically my PR still ;) ... but i'm good to merge when others are...

**Comment by AllenBW** [comment]
@priley86 yer in luck, they updated to 3.4!  pr has been updated to reflect that change

**Comment by priley86** [comment]
looks good!

**Pull request merged**
