### PR TITLE
feat(Card): add full-height and plain variation

### LINKED ISSUE #5582: Card - add plain variation
This is where you want the card padding and structure, but no border, shadow, or background color.

Just adds `.pf-m-plain` to the `.pf-c-card` element.

This work was done as part of creating card demos - https://github.com/patternfly/patternfly/pull/3848/

cc @mcarrano

### LINKED ISSUE #5584: Card - add full-height variation
We added a variation to the card that makes it fill the height of the container it's in via `height: 100%`. The variation name is `.pf-m-full-height`. Note - percentage based heights require the parent element have an explicit or implicit height defined.

This was done as part of a tabs demo https://github.com/patternfly/patternfly/pull/3914/

cc @mcarrano

### PR DESCRIPTION
**Pull request by KKoukiou**
Closes #5584
Closes #5582

### CODE REVIEW

**Review by mcarrano — COMMENTED** [review]
This looks good to me, but I'll defer to @mcoker on this one.

**Review by mcoker — DISMISSED** [review]
Looks great! Thanks!!

**Review by jessiehuff — DISMISSED** [review]
LGTM!

**Review by tlabaj — CHANGES_REQUESTED** [review]
can you add the new props to integration app.

**Comment by KKoukiou** [comment]
> can you add the new props to integration app.

Done

**Review by jessiehuff — DISMISSED** [review]

**Comment by kmcfaul** [comment]
It's a bit hard to tell that the `isFullHeight` checkbox in the example is working (I had to modify the example to test it). Could we wrap the `Card` in a `div` styled with a height so when `isFullHeight` is checked, there is a noticeable increase to show the height growing to the container?

**Review by mcarrano — APPROVED** [review]
Looks good to me

**Review by jessiehuff — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]
Looks great!

**Pull request merged**
