### PR TITLE
fix(switch): support defaultChecked props in uncontrolled switch

### LINKED ISSUE #2791: Uncontrolled switch is not working
The uncontrolled examples of switch don't work correctly.
Clicking the switch doesn't check or uncheck it.

### PR DESCRIPTION
**Pull request by boaz0**
**What**:

fixes #2791

### CODE REVIEW

**Comment by dlabaj** [comment]
@boaz0 Thanks for the update.  Looks like there's a conflict in Switch.tsx.

**Comment by boaz0** [comment]
@dlabaj done :+1:

**Comment by redallen** [comment]
Conflicts with #2749 . Thoughts @boaz0 ?

**Comment by boaz0** [comment]
@redallen - thanks for :warning: - I  will close this and review yours.

**Pull request closed without merging**
