### PR TITLE
chore(CI): Fix GH action to set stale issues status to needs triage

### PR DESCRIPTION
**Pull request by wise-king-sullyman**
**What**: Towards #10525 

**Additional issues**:

### CODE REVIEW

**Comment by wise-king-sullyman** [comment]
I also added a quick change to correct the comments that the stalebot will leave

**Comment by tlabaj** [comment]
@wise-king-sullyman  can you make changes on v6 branch as well please.

**Comment by wise-king-sullyman** [comment]
@tlabaj I'm still not _entirely_ sure this will work, do you mind if I just make the changes on v6 once I definitively know what the workflow will look like?

**Review by tlabaj — APPROVED** [review]

**Comment by tlabaj** [comment]
> @tlabaj I'm still not _entirely_ sure this will work, do you mind if I just make the changes on v6 once I definitively know what the workflow will look like?

Sounds good @wise-king-sullyman

**Review by gitdallas — APPROVED** [review]

**Pull request merged**
