### PR TITLE
Begin deprecate table

### PR DESCRIPTION
**Pull request by nicolethoen**
**What**: Closes https://github.com/patternfly/patternfly-react/issues/8005

in order to build this PR, I had to temporarily remove the building of Props tables and CSS variables tables on the component docs (they were built using the now deprecated table). Once this merges, I can reimplement them using the recommended Table and they will return.

I'm curious if people are averse to the idea of reverting the name change of the TableComposable. If we keep it's old name, this PR will be smaller, it will be easier to write codemods, and it will be easier to process which table a consumer is trying to use. I might propose keeping the name TableComposable until the day comes when we are ready to remove the deprecated Table from the code base entirely. @tlabaj WDYT?

### CODE REVIEW

**Review by jenny-s51 — APPROVED** [review]
This is looking awesome @nicolethoen! 🤩 🎉

**Comment by tlabaj** [comment]
> I'm curious if people are averse to the idea of reverting the name change of the TableComposable. If we keep it's old name, this PR will be smaller, it will be easier to write codemods, and it will be easier to process which table a consumer is trying to use. I might propose keeping the name TableComposable until the day comes when we are ready to remove the deprecated Table from the code base entirely. @tlabaj WDYT?

I think is preferable to rename now while we are in the major release rather that accumulating tech debt.

**Review by thatblindgeye — COMMENTED** [review]
I'm noticing the following Table demos seem to not be working as expected anymore:

- Bulk Select (the actual table body doesn't have any content rendered inside of it)
- Expand/collpase all (`TypeError: Cannot read properties of null (reading 'length')` when opening the demo, plus the same error for `reading 'header'` in console)

Those could be fixed by the followup that updates usage of deprecated table, though... Other than that this is looking good, though

**Comment by tlabaj** [comment]
> **What**: Closes #8005
> 
> in order to build this PR, I had to temporarily remove the building of Props tables and CSS variables tables on the component docs (they were built using the now deprecated table). Once this merges, I can reimplement them using the recommended Table and they will return.
> 

@nicole which issue will cover this?

**Comment by nicolethoen** [comment]
> @nicole which issue will cover this?

https://github.com/patternfly/patternfly-org/issues/3469

**Comment by nicolethoen** [comment]
@thatblindgeye I opened a follow up issue to fix those demos since - when looking at them, it's not super obvious what's wrong and it'd be better to get this PR in quick as we can to simplify merge conflicts in the future.
https://github.com/patternfly/patternfly-react/issues/8921

**Review by thatblindgeye — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]
Thank you Nicole and Jenny! Lgtm

**Pull request merged**
