### PR TITLE
fix(Table) Table tooltips not triggered via keyboard

### LINKED ISSUE #8158: Bug - Table - TableText tooltips not triggered via keyboard
When using keyboard to navigate tables, truncated text cannot receive keyboard focus. This results in the keyboard user being unable to trigger the tooltip to open and display the truncated text. In most cases, the truncated text is getting a tooltip dynamically by login in the `TableText` component.

Truncated `TableText` needs to be focusable when it is not in an interactable element. such as the truncated cells in the [controlling text example](https://www.patternfly.org/v4/components/table#composable-controlling-text).

In examples such as the [sortable and wrapping headers example](https://www.patternfly.org/v4/components/table#composable-controlling-text), the truncated `TableText` is actually placed within a button (used to control the sorting). In such cases, the tooltip likely needs to be built around the button, or attached to a different interactable element like a `(?)` icon, for example so that we avoid nesting interactable elements.

Oct-04-2022 21-21-14

### PR DESCRIPTION
**Pull request by Dominik-Petrik**
**What:** Closes #8158

 **Additional issues:** Implements changes from this [PR](https://github.com/patternfly/patternfly-react/pull/8671). Thanks @kmcfaul for this!

### CODE REVIEW

**Review by nicolethoen — CHANGES_REQUESTED** [review]
I'm noticing that this example: [modifiers with table text](https://patternfly-react-pr-8758.surge.sh/components/table#modifiers-with-table-text) still doesn't receive keyboard focus to trigger the tooltip. 

I could update the example to be the following and it would work:
```
export const TableTextModifiers: React.FunctionComponent = () => {
  const [focused, setFocused] = React.useState(false);
  
  return (
    <TableComposable aria-label="Table text">
    <Thead>
      <Tr>
        <Th width={30}>{columnNames.truncate}</Th>
        <Th>{columnNames.wrap}</Th>
      </Tr>
    </Thead>
    <Tbody>
      <Tr>
        <Td
          onFocus={() => setFocused(true)}
          onBlur={() => setFocused(false)}
          tabindex={0}
           dataLabel={columnNames.truncate}>
          <TableText focused={focused} wrapModifier="truncate">This text will truncate instead of wrap.</TableText>
        </Td>
        <Td 
          dataLabel={columnNames.wrap}
          >
          <TableText wrapModifier="nowrap">
            <a href="#">This is a link that needs to be on one line and fully readable.</a>
          </TableText>
        </Td>
      </Tr>
    </Tbody>
  </TableComposable>
  );
}
```

i'm not sure if there's a way we could update the API to make it a little simpler in the case of the TableText directly in a Td or Th with no sortable wrapper.

P.S. I was able to get the tests passing by rebasing and force pushing. You'll want to pull to update your branch before making subsequent commits.

**Review by thatblindgeye — COMMENTED** [review]
For the most part it looks like the tooltips are working with keyboard. I am noticing that when using VoiceOver and navigating a table with it, the tooltip doesn't render when truncated text receives VO focus (using the [Modifiers with table text](https://patternfly-react-pr-8758.surge.sh/components/table#modifiers-with-table-text) example). Compare that to our [tooltip react ref example](https://patternfly-react-pr-8758.surge.sh/components/tooltip#tooltip-react-ref) which does get the tooltip rendered on VO focus (even if the button in the example is replaced with a span). While the actual `td` or `th` element may receive keyboard focus when tabbing, VO (possibly other screen readers? would need to check) places focus on the content of the `td` or `th` instead it seems.

Adding the `pf-c-table__button` class to a button and placing TableText inside of it sort of worked for me, after removing the tabindex from the `td` in the example. @nicolethoen WDYT of something like that? It may be more beneficial to use buttons when using tooltips in general, even in cases of truncation, just because of possible issues assistive tech may face when tooltips are place on static elements like a span or div.

**Comment by nicolethoen** [comment]
@thatblindgeye 
I am not as worried about the tooltip getting triggered for screen reader users on truncated cells, because screen readers read the entire truncated text anyway. In the [Modifiers with table text](https://patternfly-react-pr-8758.surge.sh/components/table#modifiers-with-table-text) example, the screen reader reads the full cell text even though the tooltip is not triggered.

**Review by thatblindgeye — COMMENTED** [review]
@nicolethoen good point about the tooltip, screenreader focus may only really matter if a custom tooltip is passed in, but I believe there's still that (unrelated to this PR) issue where custom tooltips aren't rendering correctly. And that may also depend on whether using an info button would make more sense instead of a tooltip on the cell itself in that case.

**Review by thatblindgeye — APPROVED** [review]

**Review by nicolethoen — APPROVED** [review]

**Pull request merged**
