### PR TITLE
test(ListView): Fix linting errors in ListView

### PR DESCRIPTION
**Pull request by sharvit**
**What**:
Fix linting errors in ListView/index.js

**Why**:
Because `npm run lint` is failing.

### CODE REVIEW

**Comment by priley86** [comment]
@sharvit I just did a fresh `npm install` and I do not see these errors (and they passed the previous Travis build, so my guess this is on your side). Please make sure you have node 8/npm5 before npm installing.

```
| => node -v
v8.1.3
```

```
| => npm -v
5.4.2
```

**Comment by sharvit** [comment]
@priley86 - when I used the latest stable node-8 the `package-lock.json` got updated.

```bash
$ node -v
v8.9.1
$ npm -v
5.5.1
```

```diff
@@ -2,6 +2,7 @@
   "name": "patternfly-react",
   "version": "0.0.0-semantically-released",
   "lockfileVersion": 1,
+  "requires": true,
   "dependencies": {
     "@hypnosphi/fuse.js": {
       "version": "3.0.9",
@@ -13,13 +14,21 @@
       "version": "2.0.0",
       "resolved": "https://registry.npmjs.org/@semantic-release/commit-analyzer/-/commit-analyzer-2.0.0.tgz",
       "integrity": "sha1-kk0eLDAWfGpHK+2fZu6Pjgd0ibI=",
-      "dev": true
+      "dev": true,
+      "requires": {
+        "conventional-changelog": "0.0.17"
+      }
     },
     "@semantic-release/condition-travis": {
       "version": "5.0.2",
       "resolved": "https://registry.npmjs.org/@semantic-release/condition-travis/-/condition-travis-5.0.2.tgz",
       "integrity": "sha1-9Lt3emxttVZdcHVKm2KSM71KZZc=",
-      "dev": true
+      "dev": true,
+      "requires": {
+        "@semantic-release/error": "1.0.0",
+        "semver": "5.3.0",
+        "travis-deploy-once": "1.0.0-node-0.10-support"
+      }
     },
```

**Comment by priley86** [comment]
@sharvit ok - I see the same now. Let's update it. Do you mind updating this PR? Are you still seeing format changes after?

**Comment by sharvit** [comment]
@priley86 - I don't see the errors after switching to node-8 so I guess it's fine.

Thanks!

**Pull request closed without merging**
