### PR TITLE
chore(Table): Update keyboard interactions

### LINKED ISSUE #5596: Table: Tree table - use roving tabindex to update keyboard accessibility
as described here: https://github.com/patternfly/patternfly-react/issues/5016#issuecomment-782338541
to follow these guidelines: https://www.w3.org/TR/wai-aria-practices/examples/treegrid/treegrid-1.html

### PR DESCRIPTION
**Pull request by nicolethoen**
**What**: Closes #5596

### CODE REVIEW

**Comment by CooperRedhat** [comment]
I don't have much context on the code for a full review, but I played around with keyboard interactions in the `Table` and seemed to work as expected!

**Review by kmcfaul — APPROVED** [review]
lgtm!

**Review by tlabaj — COMMENTED** [review]
Looks good.  I will defer to @jessiehuff for approval.

**Review by jessiehuff — APPROVED** [review]
LGTM! Follows the [WAI ARIA example for role treegrid](https://www.w3.org/TR/wai-aria-practices-1.1/examples/treegrid/treegrid-1.html) and seems to work in a quick test with VO. Great job as usual! 😄

**Comment by nicolethoen** [comment]
Note: @jessiehuff should double check that the other table examples all work with a keyboard as well as this change applies this keybaord handling to all tables

**Review by CooperRedhat — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]

**Review by jessiehuff — APPROVED** [review]

**Pull request merged**
