### PR TITLE
feat(chart-stack): add monthly example

### PR DESCRIPTION
**Pull request by priley86**
**What**:
Refactors downstream monthly stack chart view in Subscriptions based on current discussions. This needs more review and iteration, but we'd like to tackle this problem in PatternFly!

Note: will need to test whatever solution we come up w/ here downstream before merge...

Current screenshots...

https://patternfly-react-pr-2625.surge.sh/patternfly-4/charts/chartstack/

Desktop:
Screen Shot 2019-08-01 at 10 27 03 AM

Tablet:
Screen Shot 2019-08-01 at 10 27 54 AM

Mobile:
Screen Shot 2019-08-01 at 10 28 11 AM

**Additional issues**:

### CODE REVIEW

**Comment by priley86** [comment]
after further testing downstream, this appears to broken on IPhone X:

Screen Shot 2019-08-02 at 1 44 30 PM


Seeing the same thing downstream in Insights, but this is much closer to the design in place here now:
https://github.com/RedHatInsights/curiosity-frontend/pull/70

**Comment by dlabrecq** [comment]
There's a `fixLabelOverlap` prop you can try. That reduces the number of tick labels to fit the length of the axis.

**Comment by priley86** [comment]
Works for me...

Screen Shot 2019-08-02 at 2 53 07 PM

**Comment by bclarhk** [comment]
The spacing on the desktop view looks pretty awkward. Can the column widths be adjusted as well?

**Comment by dlabrecq** [comment]
Spacing is typically related to the overall container width. The wider the SVG, the more spacing between bars. However, the spacing between bars can also be adjusted via properties such as `barRatio`, `barWidth`, and `domainPadding`, etc.

If you prfefer to see bars grouped by moth or year (e.g., https://www.patternfly.org/v3/pattern-library/data-visualization/bar-chart/), then the data needs change. Currently, the chart is showing daily data.

**Comment by priley86** [comment]
cc: @cdcabrera ^^

**Comment by mcarrano** [comment]
@mceledonia can you take a look and let me know if you see any issues? Thanks.

**Comment by mceledonia** [comment]
This looks good to me, we should recommend avoiding the bars not having any space (min 1px) between them though! Fix label overlap looks good to me though.

**Pull request merged**
