### PR TITLE
feat(topology): Pipelines support for badges/icons variable task node width

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
**What**: 
Closes https://github.com/patternfly/patternfly-react/issues/7696
Adds badges and icon support to pipeline task nodes
Makes task nodes variable width.

**Additional issues**: None

/cc @karthikjeeyar

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
This looks amazing Jeff 🎉  

I observed the spacing in right side of the node label is not 16px and the nodes that has truncated labels that has little more space on the right than the nodes with untruncated labels.

image

image

**Comment by jeff-phillips-18** [comment]
@karthikjeeyar @andrew-ronaldson The spec is a bit inconsistent. Most places it shows 8px right padding but in a couple it shows 16x. I've standardized on 8px padding between everything making it all more consistent.

Funny, I'm not seeing the extra space when text is truncated:

image

**Comment by andrew-ronaldson** [comment]
Hey @jeff-phillips-18. I added the extra padding on the right because the 24px icon seems to have its own small padding. I wanted to compensate for the imbalance because the rounded corners makes it feel tight to the edge.

**Review by nicolethoen — APPROVED** [review]

**Comment by jeff-phillips-18** [comment]
@karthikjeeyar Updated the task nodes to have a 12px start and end padding as discussed with @andrew-ronaldson. 

Andrew, the spec should be updated as discussed.

**Comment by jeff-phillips-18** [comment]
image

**Comment by andrew-ronaldson** [comment]
LGTM I will make the changes to design spec and let the HAC team know.

**Review by karthikjeeyar — COMMENTED** [review]
Thanks Jeff, LGTM

**Comment by jeff-phillips-18** [comment]
https://topology-pipeline-badges.surge.sh/

**Review by nicolethoen — APPROVED** [review]

**Review by jenny-s51 — APPROVED** [review]
LGTM @jeff-phillips-18! Matches designs and all behavior working as expected.

**Pull request merged**
