### PR TITLE
feat(card): adds card is-hoverable modifier prop

### PR DESCRIPTION
**Pull request by dgutride**
Closes: #1803

### CODE REVIEW

**Comment by mcarrano** [comment]
@mceledonia can you review this one to make sure correct drop shadow is applied and tag as 'UX approved' if you are good with it. Thanks!

**Comment by mceledonia** [comment]
I'm not sure I'm seeing the right thing here, is the react preview link above the correct source? I'm just getting a barebones pf4 layout with a couple small cards and no hovers on FF. @mcarrano

**Comment by mcarrano** [comment]
@mceledonia You should be looking at the preview of the Card component here: https://1812-pr-patternfly-react-patternfly.surge.sh/patternfly-4/components/card/  If you scroll down the page you will see an example called Card Hover Example.

**Comment by mceledonia** [comment]
Thanks Matt, this looks correct in terms of what was designed.

**Pull request merged**
