### PR TITLE
feat(Tag): create a tag like a CompoundLabel of key-value pair

### PR DESCRIPTION
**Pull request by aljesusg**
affects: patternfly-react

based in : 
41593083-280e2154-73bf-11e8-992e-1204e8d0028a

**widgets/tag**
storybook: [here](https://rawgit.com/aljesusg/patternfly-react/tag_label_sortybook/index.html)

@serenamarie125 @jgiardino @jeff-phillips-18 I called the component tag because the CompoundLabel of issue https://github.com/patternfly/patternfly-react/issues/401 is different

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
@patternfly/patternfly-react-ux Can some one please self-assign and review?

**Comment by jeff-phillips-18** [comment]
@aljesusg Might be better to call this a TagLabel and group it with the other labels. Thoughts?

**Comment by terezanovotna** [comment]
How is it different from this [compound label](https://panspagetka.github.io/patternfly-react/?selectedKind=patternfly-react%2FWidgets%2FLabel&selectedStory=Compound%20Label&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) @aljesusg? from the color perspective, the light blues do not have enough contrast to be accessible

**Comment by aljesusg** [comment]
You can't put a label and value in the actual compoundlabel @terezanovotna , we are using this kind of label in Kiali and Openshift. If we can't do this in patternfly there is no problem, I'll close the PR. Thanks

**Pull request closed without merging**
