### PR TITLE
fix(Nav): updated drilldown navigation heights

### LINKED ISSUE #9183: Bug - Navigation - Drill down navigation is broken
**Describe the problem**
If you click on the drill down item in the navigation menu, next level menus do not display. you get this:

Screenshot 2023-05-25 at 9 49 23 AM

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Closes #9183

**Additional issues**:

### CODE REVIEW

**Review by mcarrano — CHANGES_REQUESTED** [review]
The component example is working, but I still see a problem in the demo here: https://patternfly-react-pr-9255.surge.sh/components/navigation/react-demos/drilldown-nav/

**Comment by thatblindgeye** [comment]
>Only question I have is that on the demo the top nav item in a drilled in menu is permanently highlighted, which I understand because its the active submenu (or should it not highlight?). But the hover highlight is the same color so it looks a bit weird trying to select another item.

Good point. It does match the behavior seen in our [Menu drilldown example](https://patternfly-react-pr-9255.surge.sh/components/menus/menu#with-drilldown), and having it highlight also can help convey what item in the new menu has focus for users as well. But yeah the style matching the hover style can be confusing. @mcarrano what do you think?

**Review by nicolethoen — APPROVED** [review]
LGTM - pending @mcarrano's opinion about styles

**Comment by mcarrano** [comment]
> Only question I have is that on the demo the top nav item in a drilled in menu is permanently highlighted, which I understand because its the active submenu (or should it not highlight?). But the hover highlight is the same color so it looks a bit weird trying to select another item.

I have to admit this looks a bit off. If I compare it to [this demo](https://patternfly-react-pr-9255.surge.sh/components/navigation/react-demos/grouped-nav/), for example, the hover and selected styles are slightly different. This may have been an oversight with the original implementation, and unless the styling changed for v5 or there is a simple fix, I say merge this and perhaps open a follow-up design issue.

@mcoker @mceledonia can you take a quick look and see if this styling matches your expectation? It's this demo: https://patternfly-react-pr-9255.surge.sh/components/navigation/react-demos/drilldown-nav

**Comment by mceledonia** [comment]
Yeah, I don't think the background change is necessary here, it seems pretty clear you're in a new navigation context without it.

**Comment by tlabaj** [comment]
@mcarrano if you are ok with it, let's open a follow up issue.

**Comment by mcarrano** [comment]
@tlabaj yes, I am OK with that. I can approve this and open a new design issue.

**Review by mcarrano — APPROVED** [review]

**Comment by mcarrano** [comment]
Opened this follow-up issue: https://github.com/patternfly/patternfly-design/issues/1263

**Pull request merged**
