### PR TITLE
[WIP] feat(TreeView2): Create TreeView2 Pattern and ManagedPattern

### PR DESCRIPTION
**Pull request by sharvit**
**What**:
I have been thinking about the Patterns approach/convention and tried to draw my thoughts:
[Patterns.pdf](https://github.com/patternfly/patternfly-react/files/1778684/Patterns.pdf)

Then, I reimplemented the TreeView (as TreeView2) as a Pattern and ManagedPattern.

**Link to Storybook**:
https://rawgit.com/sharvit/patternfly-react/storybook/feature/tree-view-managed-pattern/index.html?knob-highlightSelected=true&knob-highlightOnHover=true&selectedKind=TreeView2&selectedStory=Managed%20TreeView2%20Pattern%20demo&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

Any thoughts?
@priley86 @jeff-phillips-18 @mturley

### CODE REVIEW

**Comment by priley86** [comment]
@sharvit - I started to respond to this a few times... but had to re-think my opinion a few times now....  😸 

First - terrific job w/ this! You put a lot of thought into the architecture, the accessibility, and the TreeView implementation...

Here is some initial thoughts after seeing the proposal (and these are personal opinions before discussing further w/ others):

* This is becoming a pretty important next step w/ this repo and I think it is definitely worth discussing it further w/ design at this point. It does seem to be the right approach for scaling the patterns, just want to confirm this w/ everyone. Maybe you can clearly spell this out w/ this TreeView pattern or the Empty State pattern in a future PF React Community Meeting or PF React Meeting.
* I do believe based on what I have seen in product vs what I have seen in PatternFly today that a lot of variation actually does exist when we talk about opinionated wrappers (patterns of those building blocks). However, we should be able to consolidate those patterns (variations) into the ones we want to actually support in the future into this repository.
* I guess I kind of prefer to include the word "Pattern" in the pattern exports so that I will know they are different downstream than components/managers, i.e. "TreeViewPattern2" vs "TreeView2". I also think we should take these patterns up a level in the Storybook hierarchy (Storybook now supports it multiple levels):
-> Treeview
---> *Managers* (simple Storybook mock state managers / abstract Redux containers/ HOCs/Context)
------> TreeViewPatternManager1
---------> Stories
------> TreeViewPatternManager2
---------> Stories
---> *Patterns* (stateless wrappers, sometimes using Context API/controlled/getDerviedState patterns for simple UI state)
------> TreeViewPattern1
---------> Stories
------> TreeViewPattern2
---------> Stories
------> TreeViewPatternManager2
---------> Stories
---> *Components* (stateless)
------> TreeviewNode
---------> Stories
------> TreeviewNode2 (only if necessary)
---------> Stories
------> TreeviewNodeContainer
---------> Stories
------> TreeviewNodeContainer (only if necessary)
---------> Stories

* It seems like we should continue to do our utmost to share the building block level components under `src/components` and only diverge those into `src/patterns/[ComponentName]/components` when it is absolutely necessary (but this does give us the fallback option). The more we consolidate the components, the less we have to maintain, and the more we can benefit from each other's contributions.

* The `TreeView2Managed`/`Manager` is where things start getting more and more opinionated (and I hope they don't become blockers as we contribute in this repo to those inner most stateless components we are quickly iterating on and sharing). I kind of see them more as examples we can copy/paste right now, but long term I agree that we can begin to share those HOCs / state managers/ containers directly as we build less opinionated & abstracted patterns for those. This was all really clear in my mind as of last week w/ Redux containers, but since Dan Abramov spoke about the future of React last week (w/ Suspense and Context API cache), this is getting a little more blurred. It also being blurred by lots of different Redux middlewares / future facing Node.js architectures like [Apollo link-state](https://github.com/apollographql/apollo-link-state/tree/master/examples/todo) middlewares (and I think that link-state may prove the easiest full stack wise).  

The Dan's talk:
https://www.youtube.com/watch?v=v6iR3Zk4oDY
https://twitter.com/dan_abramov/status/970766490457837568

React 16.3 API improvements:
https://medium.com/@baphemot/whats-new-in-react-16-3-d2c9b7b6193b

My guess is this will lead to some core enhancements to Redux itself down the road (for simplifying the Redux API w/ Context), and you will end up w/ something that very closely resembles this in the end...
https://twitter.com/dan_abramov/status/970727207919341568

However, this does 100% replace the need for Redux in all areas...

So for now - I think the best bet (and strategy) is to continue making the Components and Patterns as stateless as possible and to long term start to settle on the middleware/manager pieces as they may, but for now I do not think we can go wrong w/ using Redux middlewares / simple state managers and using those as the basis for future API enhancements/simplifications...

**Comment by mturley** [comment]
@sharvit I did something similar in my PR #268 with a `WizardPattern` and `StatefulWizardPattern`. Maybe I should call mine `Managed` instead of `Stateful`, or vice versa?

**Comment by priley86** [comment]
@sharvit + any others ... would definitely appreciate feedback on @mturley's work in #268 (we are finishing it up soon).  We would like to consume this pattern and use it as a model example for future abstractions/higher level stateful patterns in the future. I like the names chosen there but was curious if you have any more thoughts? We discussed that `ControlledWizardPattern` is probably more confusing for designers than `StatefulWizardPattern`... so we are trying to find some common terminology there. 

cheers! 🍺

**Comment by priley86** [comment]
it would be really nice to incorporate your a11y enhancements in the existing TreeView components here... i am still not sure about the pattern for TreeView specifically, but will try to look as I have time. I think we can start looking to `getDerivedStateFromProps` to handle all state though if we want components to be more flexible.

**Comment by jeff-phillips-18** [comment]
@sharvit Do you plan to continue with this PR or shall we close it out?

**Comment by dgutride** [comment]
Spoke with @sharvit - closing until time exists to revisit this.

**Pull request closed without merging**
