### PR TITLE
fix(Badge): remove margin between badges to match core

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: update badge examples to match core.

References #966

**Additional issues**:

### CODE REVIEW

**Comment by christiemolloy** [comment]
@kmcfaul so the spaces in Core are determined by `display: inline-block`, which adds a literal space to either side of the badges. Since React is minifying the HTML this apparently removes those spaces and thats why those badges are now pressed together. Are you able to investigate how to bring those back?

**Comment by kmcfaul** [comment]
Fixed the white space issue but the code in the examples is a bit less readable for it. I also swapped the order of the examples after noticing they were backwards compared to core.

**Comment by jschuler** [comment]
How about instead of inlining the spans, add `{' '}` after the Badges
e.g.
```
<Badge isRead>7</Badge>{' '}
<Badge isRead>24</Badge>{' '}
<Badge isRead>240</Badge>{' '}
<Badge isRead>999+</Badge>
```
This way it is more readable and it will be obvious that we;ve inserted spaces

**Comment by kmcfaul** [comment]
I can do that but when I save the file it auto-reformats into the inline version. Is there a way to disable that on VSCode for the file?

**Pull request merged**
