### PR TITLE
fix(Dropdown): Apply `pf-m-plain` modifier to dropdown toggle element instead of wrapper

### PR DESCRIPTION
**Pull request by TheRealJon**
Fixes https://github.com/patternfly/patternfly-react/issues/953.

### CODE REVIEW

**Comment by TheRealJon** [comment]
@jschuler Will do. Also, this is my first PR to pf-react. I seem to have missed a step to update the test snapshots. What is the process for that?

**Comment by jschuler** [comment]
@TheRealJon `yarn test packages/patternfly-4/react-core/src -u`

**Comment by TheRealJon** [comment]
@jschuler Fixed the snapshots and the type declarations.

**Comment by TheRealJon** [comment]
@jschuler Just rebased and updated snapshots. Should be good to go once CI finishes.

**Comment by TheRealJon** [comment]
@jschuler Who else should I ping to get approval on this?

**Pull request merged**
