### PR TITLE
feat(DataList): add expand/collapse all

### LINKED ISSUE #4942: Add expand/collapse all capability to Data list component
Want to introduce ability to expand or collapse all rows in an expandable data list. This feature will be controlled from the toolbar as per the designs here: https://docs.google.com/document/d/1zEtmy0z4DfTDwZNei-Wgd-04ox8H3NQxA8z18-109QU/edit#. There should also be a demo to illustrate this functionality incorporating a toolbar as per the design.

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #4942

### CODE REVIEW

**Review by redallen — APPROVED** [review]

**Comment by mcoker** [comment]
@kmcfaul we just merged a PR that adds an expand all item of the toolbar that has a toolbar element for the arrow icon. The expand all item has an expanded class that rotates and animates the arrow rotation. Would you have time to update this PR with that? https://github.com/patternfly/patternfly/pull/3601

**Review by mcarrano — APPROVED** [review]
This looks great @kmcfaul !

**Comment by kmcfaul** [comment]
@mcoker I should be able to, when the .59 core bump gets merged. Working on it now, adding the new variant and a small wrapper class for the `span` (since the button/tooltip itself gets passed to the toolbar item).

**Comment by kmcfaul** [comment]
@mcoker Actually, what do you mean by the class controlling the animation? Right now, the example passes in either the angle right or angle down icon itself.

**Comment by mcoker** [comment]
@kmcfaul this creates a new item of the toolbar (similar to the bulk-select item) that is `.pf-c-toolbar__item.pf-m-expand-all` with a plain button inside with an element `<span class="pf-c-toolbar__expand-all-icon">` that holds the right-arrow icon.

You can apply `.pf-m-expanded` to `.pf-c-toolbar__item.pf-m-expand-all` and that will rotate/animate the icon. The button should also have an `aria-label="Expand all"` when collapsed, and `"Collapse all"` when expanded.

**Comment by kmcfaul** [comment]
I see. The design has a tooltip as well though, not just a plain button.

**Comment by kmcfaul** [comment]
Maybe this would be better as a separate issue #, if we want to create a new controlled expand/collapse component for Toolbar? I don't modify anything in Toolbar right now.

**Comment by mcoker** [comment]
@kmcfaul that's fine with me. There is also an expand all table demo that @jschuler worked on https://github.com/patternfly/patternfly-react/pull/5030. Both would get this update.

I guess my question is what the value of creating the demo now is assuming we're going to update it next sprint?

**Comment by kmcfaul** [comment]
I'm fine with adding it now, I just can't decide whether to add just a wrapper class for the span only, or make it a whole component itself (since the ToolbarItem ends up controlling whether the icon looks expanded or collapsed).

Right now, I have it looking like this in the demo-side of the code:
```
           <ToolbarItem variant="expand-all" isExpanded={this.state.allExpanded}>
              <Tooltip
                position="right"
                content={
                  <div>
                    {this.state.allExpanded && 'Collapse all rows'}
                    {!this.state.allExpanded && 'Expand all rows'}
                  </div>
                }
              >
                <Button
                  onClick={this.onToggleAll}
                  variant="plain"
                  aria-label={this.state.allExpanded ? 'Collapse all rows' : 'Expand all rows'}
                >
                  <ToolbarExpandIconWrapper>
                    <AngleRightIcon />
                  </ToolbarExpandIconWrapper>
                </Button>
              </Tooltip>
            </ToolbarItem>
```
Assuming I'm correct that you only have to pass in the `angle-right` icon (which then gets transformed by the expanded modifier). 

But another way to add this would be to put the whole tooltip + button into its own component, or even make it a part of ToolbarItem. Something like:
```
<ToolbarItem variant='expand-all' isExpanded={this.state.allExpanded}>
  <ToolbarExpandAll onClick={this.onToggleAll} tooltipProps={...} buttonProps={...} />
</ToolbarItem>

**Comment by kmcfaul** [comment]
If the top method is fine, I can add it now.

**Comment by mcoker** [comment]
> Assuming I'm correct that you only have to pass in the angle-right icon (which then gets transformed by the expanded modifier).

Correct! I'm not sure about the way it's built though, I would probably vote for whatever's most consistent with the other items.

**Comment by kmcfaul** [comment]
Yeah I was waiting for the merge, and testing it now it behaves correctly still. I'm not sure what's most consistent. 

The first may be more consistent with the other variants of ToolbarItem, but the control of the icon sitting in ToolbarItem instead of the child is what throws the structure into question for me.

@tlabaj Any opinions?

**Comment by mcoker** [comment]
Can we also update the table expand all demo once this is complete? I can file a separate issue if we don't want to do it in this PR.

**Comment by kmcfaul** [comment]
I've got the Table demo updated with the first implementation in my working branch, just waiting on if there are objections to the first implementation.

**Comment by kmcfaul** [comment]
Titani approved the first method, so updated the PR with the Toolbar changes, and also updates to the Table demo!

**Review by nicolethoen — APPROVED** [review]

**Comment by mcoker** [comment]
Can you wrap the toolbar children in `<ToolbarContent>` in both of these demos?

**Review by mcoker — APPROVED** [review]
LGTM! Thanks for the last minute updates!

**Review by nicolethoen — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]
LGTM

**Review by dlabrecq — APPROVED** [review]

**Review by mcarrano — APPROVED** [review]
Looks great, Thanks @kmcfaul !

**Pull request merged**
