### PR TITLE
fix(react-table): Fix error Unknown event handler property `onCollapse`.

### PR DESCRIPTION
**Pull request by kunyan**
**What**:

Remove `rows` and `onCollapse` from `..props`

The recently collapse changes added some unknown props of table
Just remove it from `..props`

**Additional issues**:

### CODE REVIEW

**Comment by priley86** [comment]
@kunyan thanks - i knew about this and was going to submit a fix today. Looks like you beat me to it ;)

**Comment by priley86** [comment]
@kunyan do you mind updating snapshots `yarn test:pf4 -u` ?

**Comment by kunyan** [comment]
Snapshots updated, but looks CI not updated

**Comment by redallen** [comment]
Travis isn't reporting it's status, but the build passed: https://travis-ci.org/patternfly/patternfly-react/builds/543763403

**Pull request merged**
