### PR TITLE
fix(primary-detail-demo): enable static drawer open on mobile view

### LINKED ISSUE #4807: Drawer - static variant doesn't open panel on click
[Primary detail simple list in card](https://www.patternfly.org/v4/documentation/react/demos/primarydetail/primary--detail-simple-list-in-card)

Screen Recording 2020-09-11 at 11 48 14 AM

[Primary detail data list in card](https://www.patternfly.org/v4/documentation/react/demos/primarydetail/primary--detail-data-list-in-card)
Screen Recording 2020-09-11 at 12 01 10 PM

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
**What**: Closes #4807 .
Fixed this issue in both [Primary detail simple list in card](https://www.patternfly.org/v4/demos/primary-detail/react-demos/primary-detail-simple-list-in-card) and [Primary detail data list in card](https://www.patternfly.org/v4/demos/primary-detail/react-demos/primary-detail-data-list-in-card), where we use static drawer. When on mobile view, we could use `isExpand` to control the panel. Also I add the `DrawerCloseButton`, which will only be shown on mobile view to close the panel.

### CODE REVIEW

**Comment by mattnolting** [comment]
This looks great, thanks @DaoDaoNoCode! Approve.

**Comment by mattnolting** [comment]
On second thought, we need to update the example as well.

**Comment by DaoDaoNoCode** [comment]
@mattnolting Updating the example is more complex because we need to hide the toggle button on large screen and show it on small screen, do you think we should add a toggle button?

**Comment by mattnolting** [comment]
> Updating the example is more complex because we need to hide the toggle button on large screen and show it on small screen, do you think we should add a toggle button?

@DaoDaoNoCode For the example button, you could [hide it manually](https://codesandbox.io/s/elegant-khorana-wmzgi) by adding `.pf-c-button.pf-u-hidden-on-md`.

**Comment by DaoDaoNoCode** [comment]
@mattnolting I have updated the static drawer example, could you review it again?

**Review by mattnolting — COMMENTED** [review]
Fantastic work, @DaoDaoNoCode. This looks great. 

Can you add a note on [line 946](https://github.com/patternfly/patternfly-react/pull/5311/files#diff-6fdbc2b096076c61dbc77d015c4c74863309f76b555f7717f46de6fc6ff931e2R946) after the example title that reads: 

"Note: For mobile viewports, all drawer variants behave the same way. At the `md` breakpoint, or where `.pf-m-static{-on-[lg, xl, 2xl]}` is applied, the `static drawer` variant’s `close button` is automatically hidden because the drawer panel doesn’t close by design."

**Review by redallen — APPROVED** [review]
LGTM, please rereview @mattnolting !

**Review by mattnolting — APPROVED** [review]
LPTM! Great work, @DaoDaoNoCode!

**Pull request merged**
