### PR TITLE
fix(FileUpload): allow user to override onClick

### LINKED ISSUE #5417: File upload: Component override onClick prop
Fileupload component is overring the prop of onClick.

This event is very helpful and cannot be used because of the override.

in file [Fileupload.tsx](https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/components/FileUpload/FileUpload.tsx) around line 131 is the override:
```javascript
<FileUploadField
          {...getRootProps({
            ...props,
            refKey: 'containerRef',
            onClick: event => event.preventDefault() // Prevents clicking TextArea from opening file dialog
          })}
          tabIndex={null}
.....
```

I'm suggesting to change it to something like that:

```javascript
onClick: event => { 
    event.preventDefault();
    props?.onClick(event); 
}
```

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #5417

### CODE REVIEW

**Review by tlabaj — COMMENTED** [review]
Looks good.  Can you just add this to the demo-app please.

**Comment by kmcfaul** [comment]
Added a FileUpload demo to integration @tlabaj 

Upon testing, it looks like the `onClick` passed to the FileUploadField actually does nothing because it gets set on the div (and wasn't triggering). I adjusted the `onClick` to pass to FileUploadField's text area directly as a callback, and added a property to FileUploadField as well. @metalice Is this the behavior of the onClick you were looking for?

**Comment by tlabaj** [comment]
@kmcfaul I see you have not received a response to your question.  Maybe make a comment on the issue.

**Review by nicolethoen — DISMISSED** [review]

**Comment by tlabaj** [comment]
@kmcfaul, if you rebase this we can merge it .  I think the fix should be ok. if not another issue can be opened.

**Review by tlabaj — APPROVED** [review]
LGTM

**Review by nicolethoen — APPROVED** [review]

**Pull request merged**
