### PR TITLE
feat(TreeView): onCollapse callback

### LINKED ISSUE #9361: TreeView - add onCollapse function
**Is this a new component or an extension of an existing one?**
What is the existing component, if any?
TreeView

**Describe the feature**
A clear and concise description of the new feature. What is the expected behavior?
Add the ability to add an `onCollapse` listener to the TreeView. I would like to load the children of the node dynamically this listener would be needed to inform me of when the user opened the tree node.

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #9361

Adds `onCollapse` callback to `TreeView`. This callback is triggered when a node that has children is clicked.

Does `onCollapse` make the most sense for the name, or would `onToggle` be a better fit?

### CODE REVIEW

**Review by thatblindgeye — COMMENTED** [review]
Since it's being called when the tree view collapses and expands `onToggle` sounds like a better fit. Another option might be also adding an `onExpand` callback and calling it and onCollapse when applicable.

**Comment by kmcfaul** [comment]
Opted to divide the callbacks into onExpand and onCollapse because the opened state of the folder is internal.

**Review by tlabaj — COMMENTED** [review]
I think `onCollapse` make sense.

Can you add some unit test for these please?

**Comment by kmcfaul** [comment]
@tlabaj Just `onCollapse` or `onCollapse` + `onExpand`?

Will add some tests.

**Review by tlabaj — APPROVED** [review]
lgtm

**Pull request merged**
