### PR TITLE
style(consistency): Make the code consistence, easy to read and follow.

### PR DESCRIPTION
**Pull request by sharvit**
**What**:
Make the code consistence, easier to read and follow

**How**:
1. Move all components to `src/components`
2. Remove the none-semicolons linting rule
3. Naming changes at the [package.json scripts](https://github.com/patternfly/patternfly-react/compare/master...sharvit:feature/consistency?expand=1#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)
4. Rules added to [CONTRIBUTING.md](https://github.com/patternfly/patternfly-react/compare/master...sharvit:feature/consistency?expand=1#diff-6a3371457528722a734f3c51d9238c13)
5. Change the [src/common/helpers.js](https://github.com/patternfly/patternfly-react/compare/master...sharvit:feature/consistency?expand=1#diff-6d029458f6215790b0dcdb4b6585f3c5) to use named import.
6. Remove the `src/common/constants.js` and create a `constants.js` file for each component who need constants. Example: [Alert/constant.js](https://github.com/patternfly/patternfly-react/compare/master...sharvit:feature/consistency?expand=1#diff-9b91eb2aca88c619f2e527d63ab4b720)
7. [src/index.js](https://github.com/patternfly/patternfly-react/compare/master...sharvit:feature/consistency?expand=1#diff-1fdf421c05c1140f6d71444ea2b27638) is more focused
8. `index.js` file added to **each** component. Example: [Alert/index.js](https://github.com/patternfly/patternfly-react/compare/master...sharvit:feature/consistency?expand=1#diff-305d802182bb1bee3b0d867dda3b71c7)

### CODE REVIEW

**Comment by priley86** [comment]
@sharvit great job pulling this together so fast. You are like the Ronaldo of patternfly-react 😆 

I think the new conventions proposed here are good and should lead to better consistency overall. The only minor issue I've noted on first glance is renaming the `storybook:build` script. We wanted to do this initially but noted that there was an issue upstream w/ Storybook Deployer hardcoding the name `build-storybook`. See it here:
https://github.com/storybooks/storybook-deployer/blob/master/bin/storybook_to_ghpages#L37

So for that reason, I would hold on this for now...

I am happy to follow up on this in the upstream Storybook community (I'm already a member there and have contributed to it in the past). I can open up a PR there to accept a parameter w/ yargs and then open up a subsequent PR here to match this convention here.

Other than this - it seems great! I'm hopeful to merge this early this upcoming week after others have had a chance weigh in.

**Comment by sharvit** [comment]
@priley86 Thanks! Appreciate your feedback :stuck_out_tongue_winking_eye: I just hope you are talking about the fat Ronaldo :1st_place_medal: 

I guess we can keep them both (`storybook:build` and `build-storybook`) until they accept the pr.
And let's keep it documented as `storybook:build`, I like to keep things "contextual".

Pushed with both of them.

**Comment by priley86** [comment]
This works for me! I will open a PR in storybook-deployer later and circle back.

**Comment by sharvit** [comment]
👍

**Comment by ohadlevy** [comment]
thanks @sharvit :) I would be in favor of merging this PR sooner than later as its hard to maintain such a big rewrite over long period of time, everyone would need to rebase their pr's but... :)

**Comment by priley86** [comment]
yes - agreed... would like to merge this PR next. I still see a few minor things after pulling this down and testing locally (apologies for not finding this yesterday):

* When running `npm install` the package-lock is still changing? Not sure why the changes in this PR would change package-lock, maybe you have run a different version of Node? I have Node 8.1 and NPM 5.4.2 running locally.
* The storybook deploy command seems to not like setting a npm run script for `build-storybook` (maybe deploy script is checking a response). 

When running deploy command and having `build-storybook` set to `"build-storybook": "npm run storybook:build",`, I see the following:
```
| ~/GitHub/patternfly-react @ priley-OSX (priley)
| => npm run storybook:deploy -- --branch=sharvit-test

> patternfly-react@0.0.0-semantically-released storybook:deploy /Users/priley/GitHub/patternfly-react
> storybook-to-ghpages "--branch=sharvit-test"

=> Getting the git remote URL
   executing: git config --get remote.origin.url
=> Building storybook
   executing: npm run build-storybook -- -o out1889
   executing: git init
   executing: git config user.name "GH Pages Bot"
   executing: git config user.email "hello@ghbot.com"
   executing: git add .
   executing: git commit -m "Deploy Storybook to GitHub Pages"
/Users/priley/GitHub/patternfly-react/node_modules/@storybook/storybook-deployer/src/utils.js:16
  throw new Error(message);
  ^

Error: Exec code(1) on executing: git commit -m "Deploy Storybook to GitHub Pages"
undefined
    at Object.exec (/Users/priley/GitHub/patternfly-react/node_modules/@storybook/storybook-deployer/src/utils.js:16:9)
    at Object.<anonymous> (/Users/priley/GitHub/patternfly-react/node_modules/@storybook/storybook-deployer/bin/storybook_to_ghpages:53:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```
When I set it back to `"build-storybook": "build-storybook -c storybook -o .out",` deploy succeeds. 

I think we can just duplicate it for now and I can circle back in a later PR to address it. I'll open an issue...
```
    "storybook": "npm run storybook:run",
    "storybook:run": "start-storybook -c storybook -p 6006",
    "storybook:build": "build-storybook -c storybook -o .out",
    "storybook:deploy": "storybook-to-ghpages",
    "build-storybook": "build-storybook -c storybook -o .out",
```

**Comment by priley86** [comment]
Opened #94. I'm happy to see this merged if we can just address the two things above...

**Comment by jtomasek** [comment]
Thanks for reorg changes, this is very helpful. I am not a fan of semis and the trailing commas in function parameters are super confusing for me. Just my 2¢...

**Comment by sharvit** [comment]
@priley86 
1. I am not sure why it is updating the `package-lock.json` but it seems it is only removing a bunch of staff from this file.
    ```bash
    $ node -v
    v8.9.1
    $ npm -v
    5.5.1
    ```
2. After i gave a second look into `storybook_to_ghpages`:
    ```js
    if (packageJson.scripts['build-storybook']) {
      publishUtils.exec('npm run build-storybook -- -o ' + OUTPUT_DIR);
    } else {
      publishUtils.exec('node ./node_modules/.bin/build-storybook -o ' + OUTPUT_DIR);
    }
    ```
    * I guess it mean we can get rid of `build-storybook`?
    * The problem is happening because the `OUTPUT_DIR` is not passing from `build-storybook` to `storybook:build`.

**Comment by priley86** [comment]
@sharvit I opened an upstream PR just now:
https://github.com/storybooks/storybook-deployer/pull/28

I think we can either wait for this to merge, or create a fork of storybook-deployer, or just not change that piece yet. I will leave this up to you 😄 .

The Storybook team usually responds pretty quickly, but they are working on 3.3 release so I'm honestly not sure...

**Pull request closed without merging**
