### PR TITLE
feat(templates): toggle props & improvements

### LINKED ISSUE #10409: Templates - select improvements
- [ ] add `toggleProps` that spreads to the toggle (allowing customization of toggle width and other MenuToggle properties)
- [ ] ~~add informational  `isMenuOpen` callback about open state, returning the current menu state~~ - this can be tracked by keeping a local isOpen boolean that flips when onToggle is called, updated when onToggle is called internally
- [ ] ~~add `id` prop / add generated default ID rather than static~~ - this can already be passed by spread props, removed the default ids
- [ ] add spreadable props to other inner components to aid in customization (later going back to expose specific props in the API if we find one always being used)

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #10409

- Adds `toggleProps` (and `toggleWidth` if it was missing) to templates. 
- Extends main prop interface with respective component (SelectProps for Select and DropdownProps for Dropdown).
- Ensures that `onToggle` prop is called on every open state change.
- Removes default ids, ids can be passed manually if necessary already and this way multiple templates on a page won't require ids to avoid a11y issues.
- Adds description to some examples.

Open questions:
Do we want to rename `SelectSimple` ->  `SimpleSelect`, `SelectTypeahead` -> `TypeaheadSelect`, `DropdownSimple` -> `SimpleDropdown` to better align with `CheckboxSelect`?

### CODE REVIEW

**Review by wise-king-sullyman — COMMENTED** [review]
Looks great!

One request, I know that we have a followup issue for adding test suites for the others, but can you update the test suites for DropdownSimple and CheckboxSelect to include those new props since those test suites are otherwise already complete?

Also I would be on board with that name change.

**Comment by tlabaj** [comment]
Name change sounds good

**Review by thatblindgeye — APPROVED** [review]
Also agreed on the name change. Other than Austin's comment about tests lgtm

**Review by nicolethoen — APPROVED** [review]

**Review by nicolethoen — APPROVED** [review]

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
Can you update the test suites for SimpleDropdown and CheckboxSelect to include those new props since those test suites are otherwise already complete? I'd really love those to not regress in test completeness.

**Comment by kmcfaul** [comment]
@wise-king-sullyman Updated the Checkbox/Dropdown test and also added tests for SimpleSelect

**Review by wise-king-sullyman — APPROVED** [review]
🥳

**Pull request merged**
