### PR TITLE
feat(BulletChart): Add Thresholds to Legend

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Provides the ability to add Threshold items to the legend if either text or a function is provided.

### CODE REVIEW

**Comment by dtaylor113** [comment]
I'm a little confused.  Should the bar turn orange and/or red when over Warning or Error thresholds...like the arc does in gauge charts?

**Comment by jeff-phillips-18** [comment]
No, the bar remains the same. The threshold lines are used as indicators. See https://www.patternfly.org/pattern-library/data-visualization/bullet-chart/#design

**Comment by dlabrecq** [comment]
Is there a knob to show the threshold in the legend?

**Comment by jeff-phillips-18** [comment]
That would be up to the application to decide. That text is meant for the range bars.

**Pull request merged**
