### PR TITLE
bug(TableComposable): add dataLabel property

### LINKED ISSUE #5405: bug(TableComposable): missing dataLabel property for <Th> cells in case these are used as part of the row
According to the [spec](https://www.w3.org/TR/REC-html40/struct/tables.html#edef-TH) `<th>` can be used as part of `<tr>` elements. For that we need the dataLabel property exposed to `<th>` exactly how we do for `<td>`.

This property also needs to be mandatory when `<Th>` is direct child of `<Tr>` so that the mobile mode works as expected.

### PR DESCRIPTION
**Pull request by KKoukiou**
Closes #5405

### CODE REVIEW

**Review by redallen — DISMISSED** [review]

**Comment by tlabaj** [comment]
Can you please add the new prop to the demo app.

**Comment by KKoukiou** [comment]
I can do it - it's fine.

**Review by kmcfaul — APPROVED** [review]

**Review by evwilkin — APPROVED** [review]
LGTM

**Review by jessiehuff — APPROVED** [review]
LGTM!

**Review by dlabrecq — APPROVED** [review]

**Pull request merged**
