### PR TITLE
refactor(demo-masthead): use QuestionCircleIcon instead of HelpIcon in Masthead

### LINKED ISSUE #6926: Update masthead help icon used in all full page demos
For consistency with design guidance and current product usage, our full page demos should be using the filled question-circle `QuestionCircleIcon` in the masthead.

Result should look like this:
masthead

### PR DESCRIPTION
**Pull request by MariaAga**
**What**: Closes #6926

**Additional issues**:

### CODE REVIEW

**Review by thatblindgeye — CHANGES_REQUESTED** [review]
There are a few examples in the Nav file that are throwing an error when I try opening the demos:

- Manual nav
- Horizontal nav with horizontal subnav
- Horizontal nav
 
I'm wondering if it's due to the QuestionCircleIcon not being imported at the top of the Markdown file like some of the other demos, and instead only imported within each example (all three also don't seem to use the DashboardHeader).

**Review by nicolethoen — APPROVED** [review]

**Review by mcarrano — COMMENTED** [review]
I'm seeing the same error as @thatblindgeye . Also, it's not clear how many demos have been updated. Does this just apply to demos on the navigation page or all full page demos?

**Comment by kmcfaul** [comment]
It looks like the change should apply to the docs as well as the full page demos (as DashboardHeader received the update).

I think @thatblindgeye has the right of it about the error, should be resolved by importing the icon at the top of the md file.

**Comment by MariaAga** [comment]
Thanks all! Added the needed import

**Comment by MariaAga** [comment]
Not sure if the test failures are related, I couldn't find where do they fail

**Review by thatblindgeye — APPROVED** [review]

**Review by mcarrano — APPROVED** [review]
Looks good. Thanks @MariaAga !

**Review by nicolethoen — APPROVED** [review]

**Pull request merged**
