### PR TITLE
Upgrade 'react-dropzone' to latest version

### PR DESCRIPTION
**Pull request by jonkoops**
Upgrades `react-dropzone` to the latest version. This is needed as older versions cause compilation errors in our application.

### CODE REVIEW

**Comment by tlabaj** [comment]
@jonkoops unfortunately upgrading the the latest version is a breaking change.  We tried that in the past and had to revert it.

**Comment by jonkoops** [comment]
@tlabaj Yeah, I am aware. I've read through #6610 as well and there is indeed not really a way to avoid a breaking change if this is merged.

On the flip side, we are currently also running into issues bundling this dependency on an older version. We will probably have to work around using any components that use this dependency.

Whether this should be merged now, or later that is up to your team. If it cannot be merged directly perhaps it can be added to the next major milestone?

**Comment by jschuler** [comment]
@jonkoops Can you bump the devDependency for `@patternfly/documentation-framework` to the latest (1.2.19 as of now)
It's under packages/react-docs/package.json

Thanks!

**Comment by jonkoops** [comment]
@jschuler Done! Thanks for the assist!

**Comment by tlabaj** [comment]
I have created a v5 branch please set that as the base of this PR.

**Comment by jonkoops** [comment]
@tlabaj I've changed the base and rebased the PR on top of it.

**Comment by mturley** [comment]
If merged, this will resolve https://github.com/patternfly/patternfly-react/issues/6611. Linking that issue here.

**Comment by mturley** [comment]
I also wonder if we should consider addressing https://github.com/patternfly/patternfly-react/issues/3966 at the same time. Back when we were adding the FileUpload component and exposed `dropzoneProps` directly to the consumer, Zack had expressed the opinion that we should keep react-dropzone abstracted away and not allow arbitrary props to be passed to it as part of the API we commit to supporting. I agree, we just never got around to it before the component was taken out of beta.

**Comment by jonkoops** [comment]
@mturley It could probably be a two-parter, I don't like making too many changes in a single go. But indeed, these kind of 3rd-party interfaces are better left unexposed.

**Review by mturley — APPROVED** [review]

**Comment by tlabaj** [comment]
@jonkoops can you resolve conflicts so we can merge please

**Comment by jonkoops** [comment]
@tlabaj Done :+1: I've also cleaned up the implementation a bit.

**Review by mturley — APPROVED** [review]

**Pull request merged**
