### PR TITLE
fix(LoginPage): remove password's caps lock warning

### PR DESCRIPTION
**Pull request by Laviro**
Continued to the design refactoring [discussion](https://github.com/patternfly/patternfly-design/issues/671#issuecomment-457323229l)
where we decided to remove the inputs warning,

this is the first step - removing the caps lock warning.

### CODE REVIEW

**Comment by rebeccaalpert** [comment]
Looks good to me.

**Comment by jeff-phillips-18** [comment]
I disagree with making this change at this point. Applications may be using this already and taking it away would break them.

**Comment by Laviro** [comment]
@jeff-phillips-18 this is the results of the discussion mentioned above https://github.com/patternfly/patternfly-design/issues/671#issuecomment-457323229l
where we decided to remove the input errors and use only the top form error,
part of the discussion was to remove the `CAPS-LOCK` warning as it is not secure and maybe the user would like to use it and don't want anyone else to be aware of it,
any other thoughts about this are more than welcome, we can continue on the [discussion](https://github.com/patternfly/patternfly-design/issues/671#issuecomment-457323229l)

**Comment by jeff-phillips-18** [comment]
I don't disagree with the discussion nor the decision. However, applications already using this component may disagree and expect the warning. We could make it an option to show it but the default would have to be to show it so as to not break existing uses. Next major release we can remove the option.

**Comment by Laviro** [comment]
Thanks @jeff-phillips-18 I agree :)

**Comment by Laviro** [comment]
Closing this one as it would be implemented in https://github.com/patternfly/patternfly-react/pull/1278

**Pull request closed without merging**
