### PR TITLE
fix(Toolbar): Collapse expandable content when crossing breakpoint

### PR DESCRIPTION
**Pull request by nicolethoen**
**What**: Towards #5682 

**Additional issues**:

### CODE REVIEW

**Comment by nicolethoen** [comment]
@evwilkin I tested it on my phone (android) and I think it fixes the closing keyboard issue.

**Comment by evwilkin** [comment]
@christiemolloy this is the proposed fix for the first issue here https://github.com/patternfly/patternfly-react/issues/5682

**Comment by evwilkin** [comment]
@nicolethoen this looks to fix the issue on Android, but it does look to break the responsive behavior that you mentioned is the reason for the resize observer existing.

**Comment by christiemolloy** [comment]
Thanks Nicole and Evan! I tested on BrowserStack Android and the keyboard issue has been solved. What was the responsive behavior that is breaking now @evwilkin ?

**Comment by evwilkin** [comment]
@christiemolloy on the docs site, if you shrink the screen down to mobile & open the filters, then expand back to desktop size the view will revert back to desktop styling:
image

In this example, with the expandable content not closing on resize, the mobile view remains if the browser is sized back up to desktop:
image

**Comment by nicolethoen** [comment]
I updated it with a simpler fix which should get it all working for summit. But i did open an issue to fix some technical debt to make this resize event handler work by taking into account breakpoints - as it really should.

**Review by evwilkin — APPROVED** [review]
LGTM

**Comment by evwilkin** [comment]
@christiemolloy mind taking a second look?  Updated to address existing responsive functionality, but the Android fix should still work as expected

**Review by tlabaj — COMMENTED** [review]
You can add this to tech debt issue; we should test that the tool bar works when `windowWidth` is set by consumer.

**Review by christiemolloy — APPROVED** [review]
Confirmed on Android keyboard is working, thank you Nicole and Evan!

**Review by tlabaj — APPROVED** [review]

**Pull request merged**
