### PR TITLE
feat(Drawer): add gray and white panel background variants

### LINKED ISSUE #5423: Add option for white or gray background in Drawer
Adds support for `.pf-c-drawer__section`, `.pf-c-drawer__content`, and `.pf-c-drawer__panel` to have a grey background via the class `.pf-m-light-200`

https://github.com/patternfly/patternfly/pull/3819

### PR DESCRIPTION
**Pull request by nicolethoen**
Closes #5423

### CODE REVIEW

**Review by mcarrano — COMMENTED** [review]
Looks good to me @nicolethoen . I assume this prop can be applied to either an inline or overlay variant of the drawer, correct?

**Comment by nicolethoen** [comment]
> Looks good to me @nicolethoen . I assume this prop can be applied to either an inline or overlay variant of the drawer, correct?

@mcarrano yep! the color can be applied to any drawer panel

**Comment by mcoker** [comment]
@nicolethoen does this also apply to the content and section, or just the panel?

**Comment by nicolethoen** [comment]
@mcarrano @mcoker  ah I see what I misunderstood. I'll apply it in all places. Should only take one moment.

**Review by mcarrano — APPROVED** [review]
Looks good!

**Review by tlabaj — APPROVED** [review]
LGTM

**Review by redallen — APPROVED** [review]

**Review by mcoker — APPROVED** [review]
L🍕TM!

**Review by dlabrecq — COMMENTED** [review]
LGTM

**Pull request merged**
