### PR TITLE
chore(About modal): Update logos in about modal examples

### LINKED ISSUE #9844: Consume core updates: Modal and About Modal (Follow up to issue)
Follow up to core PR: https://github.com/patternfly/patternfly/issues/5707

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #9844 
About modal convenience  link https://patternfly-react-pr-9957.surge.sh/components/about-modal

Please also verify the Penta Modal is correct https://patternfly-react-pr-9957.surge.sh/components/modal

### CODE REVIEW

**Review by wise-king-sullyman — APPROVED** [review]

**Comment by lboehling** [comment]
lgtm!

**Review by andrew-ronaldson — COMMENTED** [review]
Screenshot 2024-01-12 at 12 34 37 PM
When the modal opens the x Close button has the hover state applied.

**Review by thatblindgeye — APPROVED** [review]

**Review by andrew-ronaldson — APPROVED** [review]
LGTM! Thanks

**Review by srambach — APPROVED** [review]
LGTM 🎉

**Review by gitdallas — APPROVED** [review]

**Pull request merged**
