### PR TITLE
feat(PageSidebar): added SidebarBody component

### LINKED ISSUE #8386: Support for page sidebar custom content
Placeholder for the core work in https://github.com/patternfly/patternfly/issues/4982

This will add content/body elements and potentially variants to allow for custom page sidebar content.

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Closes #8386 

This may require the `sideNavLayout` in org to be updated again since that is also using PageSidebar (right now the sidebar in the app won't have any content rendered despite being able to open/close it).

Links to where updates should apply (will need to manually update the URL in the address bar to get to any other page):
[Page component](https://patternfly-react-pr-8942.surge.sh/components/page/)
[Nav component](https://patternfly-react-pr-8942.surge.sh/components/navigation/)
[Notification drawer component](https://patternfly-react-pr-8942.surge.sh/components/notification-drawer/)
[Wizard component](https://patternfly-react-pr-8942.surge.sh/components/wizard/)
[Masthead demos](https://patternfly-react-pr-8942.surge.sh/components/masthead/react-demos)

**Additional issues**:

### CODE REVIEW

**Review by tlabaj — APPROVED** [review]
Looks good to me other than the Org work that needs ti be don to update the nav.  Could you please open an issue for that if it does not already exist.

**Review by nicolethoen — APPROVED** [review]

**Review by srambach — APPROVED** [review]
CSS looks good afaict!

**Review by mcoker — APPROVED** [review]
LGTM. I noticed there are some [docs around `isFilled` on `<PageSection>`s](https://patternfly-react-pr-8942.surge.sh/components/page/#filled-page-sections) mentioning that the last page section is filled by default, which is a (the?) use case for `isFilled={false}`. `<PageSidebarBody>` behaves the same way - not sure if it's worth mentioning?

**Comment by thatblindgeye** [comment]
@mcoker good callout, added some short verbiage regarding that to the "Multiple sidebar body" example

**Pull request merged**
