### PR TITLE
fix(loginpage): update the header image

### LINKED ISSUE #3347: Login component header image is incorrect
**Describe the issue. What is the expected and unexpected behavior?**

On https://www.patternfly.org/v4/documentation/react/components/loginpage/basic the image is incorrect.

The image we should be using is on this page - https://www.patternfly.org/v4/documentation/core/components/login/basic

### PR DESCRIPTION
**Pull request by boaz0**
**What**: 

closes #3347 

I just updated the header image file. 
Let me know if I am missing anything.

//cc @mcoker

### CODE REVIEW

**Comment by mcoker** [comment]
Hmm... it looks like what's currently in the dev workspace is correct - https://patternfly-react.surge.sh/patternfly-4/documentation/react/components/loginpage

But the image on pf.org is incorrect - https://www.patternfly.org/v4/documentation/react/components/loginpage/basic

And as @dlabrecq commented, the image in this PR appears to be the incorrect one. Do you know if we have updated this component recently to use the correct image, so it will show up on pf.org with the next release?

**Comment by tlabaj** [comment]
Why did you update the brand image file but you are setting  the image source directly to the website?

**Comment by boaz0** [comment]
@tlabaj still trying to figure out why https://www.patternfly.org/v4/documentation/react/components/loginpage/basic got the wrong image...

**Comment by tlabaj** [comment]
@boaz0 any updates on this one?

**Comment by boaz0** [comment]
sorry for the late response @tlabaj 
I spoke with Zack and he believes this is going to be fixed once he bumps react in patternfly-org.
He'll keep an eye on it and in case it won't be fixed a ticket will be opened in the patternfly-org repository.

I'm closing this. Thanks :)

**Pull request closed without merging**
