### PR TITLE
fix(DashboardWrapper): updated passing of onPageResize

### LINKED ISSUE #9052: Bug - DashboardWrapper - demos throwing error
**Describe the problem**
Demos are throwing an error due to the `onPageResize` prop being passed to Page in theDashboardWrapper code.

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Closes #9052 

**Additional issues**:

### CODE REVIEW

**Review by gitdallas — APPROVED** [review]

**Review by Dominik-Petrik — APPROVED** [review]

**Review by nicolethoen — APPROVED** [review]

**Review by nicolethoen — COMMENTED** [review]
Actually, when i tested this [bulk select demo](https://patternfly-react-pr-9053.surge.sh/components/table/react-demos#bulk-select) by opening it in a codesandbox, I still see the same error?

**Review by tlabaj — APPROVED** [review]
LGTM.  I see an unrelated minified React errors in the console. We should open an issue and investigate. 

Bulk select works for me.

**Comment by nicolethoen** [comment]
It works in the workspace, but I don't know why the codesandbox is displaying the error still...

**Comment by thatblindgeye** [comment]
@nicolethoen Yeah I'm not too sure either... I tried updating locally places where it seemed like might be causing it, making sure onPageResize was a function, but still getting that error

**Review by kmcfaul — APPROVED** [review]

**Comment by nicolethoen** [comment]
I opened a follow up issue for the codesandbox issue, just to get some of the other work unblocked
https://github.com/patternfly/patternfly-react/issues/9086

**Pull request merged**
