### PR TITLE
feat(searchInput): add support to passing a ref

### LINKED ISSUE #5168: SearchInput component doesn't support refs
**Describe the issue. What is the expected and unexpected behavior?**
`SearchInput` component doesn't support refs.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
This is a bug. I am using SearchInput component in a catalog with searching capabilities. As soon as the catalog loads up i want to focus the search input. TextInput supports ref but SearchInput doesn't.

**What is your product and what release version are you targeting?**
OCP 4.7

### PR DESCRIPTION
**Pull request by boaz0**
**What**: Closes #5168 

//cc @rohitkrai03

### CODE REVIEW

**Comment by boaz0** [comment]
I had to delete the unit test because:
1) shallow won't render the second level which has the input box.
2) using mount although the input box is rendered the event structure is different
3) this test is already covered in the demo app so I assumed it's not necessary to test it in the unit tests.

**Review by nicolethoen — APPROVED** [review]
LGTM since the value and onChange props are tested in they cypress tests.

**Review by tlabaj — COMMENTED** [review]
Could you also add this to demo app.

**Comment by boaz0** [comment]
Sure, I will update this soon.
Thanks.

**Review by tlabaj — APPROVED** [review]
LGTM

**Review by nicolethoen — APPROVED** [review]

**Pull request merged**
