### PR TITLE
fix(LoginPage): Add attributes to the submit button

### PR DESCRIPTION
**Pull request by laviro**
**What**: 
Added the ability to pass additional attributes to the login page submit button

### CODE REVIEW

**Comment by tlabaj** [comment]
Hi.  Is there an issue associated with this PR?

**Comment by laviro** [comment]
@tlabaj no, but we need to add this ability in our project.
@redallen why did you close it?

**Comment by redallen** [comment]
Apologies, I cleaned up all the extraneous branches off the repo this morning.

**Comment by kmcfaul** [comment]
lgtm as well, will approve when unit test goes in

**Comment by laviro** [comment]
Updated with a unit test

**Comment by ares** [comment]
awesome, thanks!

**Pull request merged**
