### PR TITLE
chore(Badge/MenuToggle): updated implementation of badge toggle

### LINKED ISSUE #10060: Remove isToggle prop for Badge
**Describe the enhancement or change**
Followup to comment chain https://github.com/patternfly/patternfly-react/pull/10051#discussion_r1471978692

Per design ([core issue for removing toggle on badge](https://github.com/patternfly/patternfly/issues/6407)) the plan is to remove the isToggle prop from Badge, and instead update examples to use MenuToggle's `badge` prop and the plainText variant.

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Closes #10060 

There's a custom menu demo, `ComposableDropdwnVariants`, that doesn't seem like we're rendering. Do we want to add this to the demo page for "custom menu" or remove this file? 

**Additional issues**:

### CODE REVIEW

**Review by kmcfaul — APPROVED** [review]
LGTM.

For the `ComposableDropdwnVariants`, we don't expose any of the direct `Popper` demos anymore so it can probably be removed. Especially since that demo is directly covered by `Dropdown`.

**Review by wise-king-sullyman — APPROVED** [review]
🎉

**Review by mcoker — APPROVED** [review]
🚀

**Review by andrew-ronaldson — APPROVED** [review]
Approved!

**Pull request merged**
