### PR TITLE
chore(Select): Clean up some typeahead behaviors

### LINKED ISSUE #4744: No option to programmatically set `No results found` option in Select
**Describe the issue. What is the expected and unexpected behavior?**
If consumer passes empty array it would be really good if PF would show `No results found` option instead of empty dropdown menu. I would gate this behind prop `showNoResults` in a way, that if this prop is not set the component would have show current bahavior, but if consumer set this up it would show the `No results found`.

So 2 criterias needs to be met:
* empty children
* `showNoResults` prop is set to `true`

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
http://patternfly-react.surge.sh/documentation/react/components/select#typeahead and change the chilren of Select to empty array.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
We are showing different option when there are no results, but our UX would like to use PF's option, so I would frame this as a bug?

**What is your product and what release version are you targeting?**
cloud.redhat.com the sooner, the better

### LINKED ISSUE #4745: Typeahead has no affordance to type when clicking on arrow
When using the typeahead control, if the user clicks on the arrow to open, there is no affordance that they are also able to type. This is causing a usability problem in c.rh.c tagging.

image

### PR DESCRIPTION
**Pull request by nicolethoen**
Closes #4744
Closes #4745 

Put focus on typeahead input even when the user click the 'open menu' button on the toggle.
focus on click

Add 'no results' message to empty typeahead menu if empty options array passed to typeahead select.
empty options

### CODE REVIEW

**Review by mcarrano — APPROVED** [review]
Looks great @nicolethoen !

**Review by karelhala — APPROVED** [review]
Looking really good!

**Review by jessiehuff — APPROVED** [review]
Great job as always, Nicole! 😄

**Review by tlabaj — APPROVED** [review]
LGTM

**Pull request merged**
