### PR TITLE
Add icon only variant for progress button

### LINKED ISSUE #6782: Add "Icon only" variant for progress button
Want to support the ability to change an icon button to a spinner to show progress. See core PR: https://github.com/patternfly/patternfly/pull/4594

### PR DESCRIPTION
**Pull request by boaz0**
**What**: Closes #6782

### CODE REVIEW

**Comment by kmcfaul** [comment]
Could the logic for `isIconOnly` be executed instead by checking whether `children` was null and so not require a new flag? `children` currently shouldn't be rendering when not passed in.

**Comment by boaz0** [comment]
@kmcfaul sure! updated the PR. Thanks.

**Comment by boaz0** [comment]
Seems like the CI failure isn't related to the change.

**Review by mcarrano — COMMENTED** [review]
Just a couple of comments...
* It might be my imagination, but it feels like the spinner and the icon for the button do not exactly have the same x-y position. It feels like the spinner appears offset from the left of the icon.
* Also, I'm wondering if this should be broken into a separate example. If I just looked at this page, I doubt that I would understand that the spinner is really a plain button.

**Review by mcoker — CHANGES_REQUESTED** [review]
For this variant, we leave the button's icon in the button when it's in progress, but we hide it using `opacity`, which hides it visually but leaves its layout in the page. That will retain the button's original shape when the spinner is shown. Looks like we're removing the icon when the icon's in progress in this PR.

**Comment by boaz0** [comment]
@mcoker & @mcarrano thanks for your review. I see what you were talking about and am going to update the PR.

**Comment by boaz0** [comment]
DONE :+1:

**Review by mcarrano — APPROVED** [review]
Looks great. Thanks @boaz0 !

**Review by tlabaj — APPROVED** [review]

**Review by mmenestr — APPROVED** [review]
LGTM!

**Pull request merged**
