### PR TITLE
fix(hasCheckbox): updated reference to hasCheck to hasCheckbox

### PR DESCRIPTION
**Pull request by bonjo7**
Issue [8126](https://github.com/patternfly/patternfly-react/issues/8126)

**What**
Updated the reference to `hasCheck` to `hasCheckbox`

### CODE REVIEW

**Comment by bonjo7** [comment]
> This is a breaking change. Can you please set the base branch of your PR to the V5 branch. To do so click "edit" button for the title of the PR. You will see an option to change the base branch.

No problem @tlabaj 👍

**Comment by tlabaj** [comment]
Thank you for your PR.  So I believe the intention of the issue was to update the props in the appropriate  components to be `hasCheckbox` rather than `hasCheck`.  THe impacted components would be `MenuItem`, `TreeView` and `TreeViewListItem`.

 @kmcfaul Can you correct me if I am wrong?

**Comment by tlabaj** [comment]
@bonjo7 are you still interested in finishing this PR?

**Comment by bonjo7** [comment]
> @bonjo7 are you still interested in finishing this PR?

Hi, what is outstanding to finish it? Based on @kmcfaul comment, I felt it was finished

**Comment by tlabaj** [comment]
We wanted to update the prop names for this issue in `MenuItem`, `TreeView` and `TreeViewListItem`.

**Comment by bonjo7** [comment]
> We wanted to update the prop names for this issue in `MenuItem`, `TreeView` and `TreeViewListItem`.

This PR already has updated `hasCheck` to `hasCheckbox` for , `TreeView` and `TreeViewListItem`,  the `MenuItem` component does not have any reference to `hasChecked` prop.

**Comment by tlabaj** [comment]
Yes, TreeView and TreeViewListItem have been updated in your PR. The `MenuItem` has this prop https://github.com/patternfly/patternfly-react/blob/47c6127c70191349261aec122b56e6ca61fa0c99/packages/react-core/src/components/Menu/MenuItem.tsx#L28

**Comment by bonjo7** [comment]
Ah sorry @tlabaj my bad, I had not pulled the latest changes, I am going to close this PR and create a new PR[1] as I kind of made a mess of my git history with it

Sorry for the confusion, the latest PR[1] should now contain all the relevant changes 😄 

[1]https://github.com/patternfly/patternfly-react/pull/8403

**Pull request closed without merging**
