### PR TITLE
feat(Dropdown): add support for disabled dropdown menus

### LINKED ISSUE #1501: Add support for disabled dropdown menus
from https://github.com/patternfly/patternfly-next/pull/1512

### PR DESCRIPTION
**Pull request by boaz0**
**What**:

closes #1501 

- [x] add the `isDisabled` prop
- [x] add an example of disabled dropdown
- [x] update `@patternfly/patternfly` to 1.0.219

//cc @mcoker

### CODE REVIEW

**Comment by mcoker** [comment]
@boaz0 looks like the preview link failed?

**Comment by boaz0** [comment]
@mcoker - I guess it's because `circleci` failed. 
I looked at the logs there and I am not sure how to fix the error. 
Maybe adding more resources to the machine or setting a longer timeout for the build.

@redallen - anything I can do to help the build pass? :pray: 

Thanks. :handshake:

**Comment by redallen** [comment]
Rebase on latest master to fix CircleCI errors and get a deploy preview.

**Comment by boaz0** [comment]
sweet! thanks a bunch @redallen :bowing_man:

**Comment by mcoker** [comment]
This looks pretty good. Can you update core to `1.0.219` as part of this change to pull in the disabled style changes? Also, while it doesn't hurt anything, if the `.pf-c-dropdown__toggle` is a `button`, it only needs the `disabled` attr, and doesn't need `.pf-m-disabled`. The modifier class is only used when `.pf-c-dropdown__toggle` is a `div` or non-form element that doesn't support `disabled`

**Pull request merged**
