### PR TITLE
feat(Select): Add flag to accept input values even if not in menu

### LINKED ISSUE #5502: Type-Ahead Select: Add option to retain keyboard-entered value in text field when tabbing away
Add a prop to retain the value entered by a user from the keyboard if the user tabs out of the field without explicitly selecting the new value. Currently the field value is not retained when tabbing away which is a potential usability issue when including type-ahead select components in the context of a form.

See the related design discussion here: https://github.com/patternfly/patternfly-design/issues/1003

### PR DESCRIPTION
**Pull request by nicolethoen**
**What**: Closes #5502

Added checkbox to toggle using the new prop in Select's Typeahead example

### CODE REVIEW

**Review by mcarrano — COMMENTED** [review]
This looks fine @nicolethoen . Not sure if there's something specific I should do to test this.

**Review by kmcfaul — APPROVED** [review]
LGTM functionality wise. The 'accepted' in `isInputValueAccepted` seems a bit confusing to me though, would something like 'isInputValuePersisted' make more sense maybe?

**Comment by nicolethoen** [comment]
> LGTM functionality wise. The 'accepted' in `isInputValueAccepted` seems a bit confusing to me though, would something like 'isInputValuePersisted' make more sense maybe?

yeah - naming is like one of my least favorite things... I'll rename! :)

**Review by kmcfaul — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]
Looks great!

**Review by dlabrecq — APPROVED** [review]

**Pull request merged**
