### PR TITLE
docs(Pagination): Export interfaces in md file so prop descriptions are documented

### LINKED ISSUE #1882: Pagination - add prop for page size menu toggle label
The consumer should be able to specify the text string for the toggle that displays the page size menu.

We should also include a default string that clearly describes the button. 

NOTE: these updates are expected to be completed after or as part of the update to refactor the Pagination component to use the OptionsMenu component. As part of this update, `button.pf-c-options-menu__toggle` would not be expected to have the attribute `aria-labelledby`.

**Updates for this issue:**
- Include a prop named `ariaLabelPageSize` that, when specified, provides the text string for a value for `aria-label` on `button.pf-c-options-menu__toggle-button`
- ~Define a default string "Items per page" to use when this prop is not specified by the user.~ This was completed in https://github.com/patternfly/patternfly-react/pull/2904

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #1882

Added the interfaces to the md file so that the props are documented for the user.  Updated a few prop descriptions @jessiehuff @jgiardino  the `titles.optionsToggle` is what sets the toggles aria label.

### CODE REVIEW

**Review by nicolethoen — APPROVED** [review]

**Comment by jgiardino** [comment]
When I tested the following prop and changed the `optionsToggle` to "Testing", I didn't see that reflected in the html. This is the prop that I added to the first example:

`titles={ items: '', page: '', itemsPerPage: 'Items per page', perPageSuffix: 'per page', toFirstPage: 'Go to first page', toPreviousPage: 'Go to previous page', toLastPage: 'Go to last page', toNextPage: 'Go to next page', optionsToggle: 'Testing', currPage: 'Current page', paginationTitle: 'Pagination', ofWord: 'of' }`

It's very possible I'm applying this prop incorrectly, though, because I'm not seeing any values I define in the `titles` prop display in the component.

**Review by kmcfaul — APPROVED** [review]

**Review by jessiehuff — COMMENTED** [review]
I agree with @jgiardino here. I can't seem to get the `optionsToggle` prop to reflect as an `aria-label` on the pagination toggle. Is there a way to do this that we're missing?

**Comment by tlabaj** [comment]
@jessiehuff @jgiardino I thin you have the syntax wrong.  You need to pass the `titles` prop an object.  try adding this to the example to see the toggle aria label updated `titles={{optionsToggle: "Items per page aria-label test"}}`

**Comment by jgiardino** [comment]
Thanks for pointing that out, @tlabaj! I was missing the extra `{}` when I tested it earlier. I tested again and it works! 🎉

**Review by jessiehuff — APPROVED** [review]
Ah ok, I also had a syntax issue. Cool! 😄  Do you think we need to add this to one of the examples or do you think it's already clear?

**Review by redallen — APPROVED** [review]

**Pull request merged**
