### PR TITLE
fix(Select): check for updates in grouped select options

### LINKED ISSUE #7134: Bug - Select - Typeahead does not update immediatly when using SelectGroup
**Describe the problem**
Select component when using variant typeahead and typeaheadmulti does not get updated immediatly. You have to click something else or open/close the select multiple types to see the new content

**How do you reproduce the problem?**
- Use a select with groups
- Dynamically disable a field when the select is open
https://codesandbox.io/s/eager-turing-pdbn8v?file=/index.js

**Expected behavior**
New state of the select should be updated immediatly

**Is this issue blocking you?**
No - I was going to switch to the checkbox mode, which updates immediatly, but came across this.

**Screenshots**
Peek 2022-03-29 07-41

**What is your environment?**
 - OS: Fedora
 - Browser Chrome
 - Version Version 99.0.4844.51 (Official Build) (64-bit)

Sidenote: I also saw something else when reproducing, on a previous version the selection was working OK - but now it only shows 1 selection even when using `typeaheadMulti`

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #7134

Adds logic to Select update function to account for select option groups.

### CODE REVIEW

**Review by tlabaj — CHANGES_REQUESTED** [review]
Given the propensity for select to break, can you please add an integration test or a unit test to verify this behaviour?

**Review by nicolethoen — APPROVED** [review]
LGTM!

**Review by thatblindgeye — APPROVED** [review]
Looks good! Tested the preview build using the code from the codesandbox in the original issue, and the bug that was previously seen no longer occurs.

**Review by tlabaj — APPROVED** [review]
LGTM

**Pull request merged**
