### PR TITLE
chore(Drag and drop): Updated example for multi list to use flex 

### LINKED ISSUE #9749: Bug - Droppable - Empty Droppables do not receive Draggables
**Describe the problem**
When a "Droppable", as found in the "Multilist Example", is empty, it does not receive a Draggable.

https://www.patternfly.org/components/drag-and-drop/react/multiple-lists

**How do you reproduce the problem?**
Open the above link, move all items from right hand list to left hand list, and then attempt to move an item back.

**Expected behavior**
A empty destination Droppable, if given a min-height, should receive a Draggable, but doesn't.

**Is this issue blocking you?**
I've implemented an ugly workaround by adding a placeholder if a list is empty, and stripping it if it is not.

**Screenshots**
image

**What is your environment?**
 - OS: recent fedora (F38)
 - Browser: chrome
 - Version: google-chrome-stable-117.0.5938.149-1.x86_64

**What is your product and what release date are you targeting?**

**Any other information?**

### PR DESCRIPTION
**Pull request by tlabaj**
Updated example for multi list to use flex so that target list will maintain size when empty

**What**: Closes #9749 

**Additional issues**:

### CODE REVIEW

**Review by mcoker — APPROVED** [review]
🚀

**Review by wise-king-sullyman — COMMENTED** [review]
I might just be testing it wrong somehow, but when I got to the preview link and move all of the items from the second list over to the first it still isn't letting me move them back?


https://github.com/patternfly/patternfly-react/assets/7115053/2d72427f-293b-4e58-ac9a-ca6feac75cad

**Comment by tlabaj** [comment]
> I might just be testing it wrong somehow, but when I got to the preview link and move all of the items from the second list over to the first it still isn't letting me move them back?
> 

@wise-king-sullyman you are right.  It only worked with the first item i dragged.  I am investigating.

**Comment by kmcfaul** [comment]
@tlabaj I'm seeing the same issue as @wise-king-sullyman but that's possibly because the build had failed, so I don't think the surge is updated yet.

**Review by kmcfaul — APPROVED** [review]
There does seem to be an inconsistent issue after emptying one drop zone and starting to refill it, sometimes an item isn't shoved properly and overlaps with another item. There is also maybe an issue where if you drop an item on the bottom of the drop zone it will append to the beginning of the list instead of the end. 

That said, this PR does fix the overall issue of the non-interactable empty dropzone and it is a deprecated component, so I'd probably be fine opening a follow up for these problems.

**Review by wise-king-sullyman — APPROVED** [review]

**Pull request merged**
