### PR TITLE
feat(Panel): consumed Penta updates

### LINKED ISSUE #9910: Consume core Penta updates: Panel
folllow up to core https://github.com/patternfly/patternfly/pull/6160

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Closes #9910

**Additional issues**:

### CODE REVIEW

**Comment by lboehling** [comment]
lgtm!

**Review by tlabaj — COMMENTED** [review]
Can you please open code mod issue for this?

**Comment by thatblindgeye** [comment]
@tlabaj since we're only adding a new variant, would we need a codemod for that?

**Comment by tlabaj** [comment]
You are correct.  No code mode needed in that case.

**Review by kmcfaul — APPROVED** [review]

**Review by wise-king-sullyman — APPROVED** [review]

**Review by andrew-ronaldson — APPROVED** [review]
Awesome. thanks

**Review by srambach — APPROVED** [review]
LGTM! 🎺

**Pull request merged**
