### PR TITLE
chore(Wizard) convert demos to TS

### LINKED ISSUE #9449: Convert wizard react demos to TS

### PR DESCRIPTION
**Pull request by Dominik-Petrik**
**What**: Closes #9449

### CODE REVIEW

**Comment by wise-king-sullyman** [comment]
Looks like this is failing a few of the CI checks

**Comment by wise-king-sullyman** [comment]
Looks like this is blocked by #9553, is that correct?

**Review by wise-king-sullyman — APPROVED** [review]

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
Missed one thing, the drawer close button is off in the last demo
image

Looks like there's a missing `DrawerActions` in the file, but I'm not 100% sure that's the cause.

**Review by jenny-s51 — COMMENTED** [review]
Thank you for your review/feedback @wise-king-sullyman ! Good catch, I noticed that as well, along with some additional spacing/styling issues that should now be fixed with the latest commit 🙂

**Review by wise-king-sullyman — APPROVED** [review]
🥳

**Review by tlabaj — APPROVED** [review]
LGTM

**Pull request merged**
