### PR TITLE
docs(Modal): Added example of modal with form

### LINKED ISSUE #2019: PF4: Convert Switch to TypeScript
Convert the Switch component to Typescript

### LINKED ISSUE #3397: Accessibility: No way to wrap PF4 modal content and footer in a single HTML form element
**Describe the issue. What is the expected and unexpected behavior?**

In OpenShift, we have many modals that are forms. We need to be able to wrap the form inputs from the modal body and the buttons from the footer in a single HTML `form` element with a submit handler for accessibility. Not being able to do this breaks features like pressing enter inside an input to submit the form. It doesn't appear to be possible with the PF4 modal, however.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug, no clear workaround. Maybe it's possible to put the buttons in the modal body.

**What is your product and what release version are you targeting?**

OpenShift 4.4

cc @rebeccaalpert @janwright73 @rhamilto

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #3397 

**Additional issues**:

### CODE REVIEW

**Review by mcarrano — COMMENTED** [review]
Looks good to me @tlabaj . But can't remember exactly what issue this addresses. The issue you linked does not look right.

**Comment by tlabaj** [comment]
@mcarrano I put wrong issue number.  it is #3397

**Review by mcoker — APPROVED** [review]
lgtm! @mcarrano it's just an example of how to link a form in the modal body with a submit button that is outside of the body (in the modal footer). No code changes or anything with this, just example HTML that shows how to associate the form and button with one another.

**Review by mcarrano — APPROVED** [review]
Looks good to me. Thanks @tlabaj !

**Comment by nicolethoen** [comment]
I'm doing some digging about screen reader usage of a modal - I may open a follow up issue

**Review by kmcfaul — APPROVED** [review]
lgtm!

**Review by nicolethoen — APPROVED** [review]
LGTM - i will keep looking to determine if there are modal a11y issues that are outside of the scope of this

**Pull request merged**
