### PR TITLE
chore(deps): upgrade and align `@dnd-kit/` dependencies

### PR DESCRIPTION
**Pull request by jonkoops**
Upgrades the `@dnd-kit/` dependencies to their latest versions. This also adds the missing `@dnd-kit/utilities` dependency and removes the unused `@dnd-kit/modifiers` dependency.

### CODE REVIEW

**Review by nicolethoen — COMMENTED** [review]
This change seems to break the styles in the drag drop demos which use them
https://patternfly-react-pr-10590.surge.sh/components/drag-and-drop/react-next-demos

This is what is used to look like:
Screenshot 2024-06-11 at 8 42 04 AM

This is what it looks link in this PR:
Screenshot 2024-06-11 at 8 41 41 AM

**Comment by jonkoops** [comment]
@nicolethoen looks like this might have to be reworked before it can be upgrade then. I don't have time to work on this specific area, is there someone on the team that might be able to take this over? Perhaps this is something breaking that should come along in v6?

**Comment by nicolethoen** [comment]
yeah I agree. Do you want to close this and open an issue instead?

**Comment by jonkoops** [comment]
Created #10600, I'll close this PR for now.

**Pull request closed without merging**
