### PR TITLE
feat(Navigation): Penta updates for nav

### LINKED ISSUE #9943: (Navigation): Add Penta tokens
follow up to core https://github.com/patternfly/patternfly/issues/6000

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #9943 
Also made updates to the Page component.  There were references to tertiary nav.  Updated them to refer to horizontal subnav.

### CODE REVIEW

**Review by wise-king-sullyman — APPROVED** [review]
The horizontal subnav scroll buttons seem to be showing when they shouldn't, but other than that everything looks great to me!

**Review by andrew-ronaldson — APPROVED** [review]
Looks great

**Comment by tlabaj** [comment]
@wise-king-sullyman open this follow up issue. #9977

**Review by mattnolting — COMMENTED** [review]
Looks like you have an extra divider in the expandable example, other than that, great work!

Screenshot 2024-01-16 at 12 40 32 PM

**Review by kmcfaul — APPROVED** [review]
LGTM. 

The flyout menu still uses the old styling but I think that's a part of Menu's css and not Nav's, through the `pf-m-nav` modifier on the Menu right? @mcoker / @mattnolting

**Pull request merged**
