### PR TITLE
chore(tests) fixate time format

### LINKED ISSUE #8690: Bug - Tests - Timestamp tests keeps failing because of wrong format
**Describe the problem**
When running yarn test Timestamp tests keep failing for some non-US located contributors, since date time format is not fixed.

**Is this issue blocking you?**
If this is blocking you adding LC_ALL=en_US.UTF8 argument to test script in package.json solves the problem

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Dominik-Petrik**
**What**: Closes #8690

### CODE REVIEW

**Comment by adamviktora** [comment]
Nice work! Test passes, approving

**Review by adamviktora — APPROVED** [review]
Solves the issue. Good job

**Review by gitdallas — APPROVED** [review]
looking good in the US

**Review by adamviktora — CHANGES_REQUESTED** [review]
I ran the test again (previously I tried from different machine and it worked fine) and I still have the same issue in tests:
Screenshot 2023-02-15 at 21 24 37
Screenshot 2023-02-15 at 21 24 09

**Comment by wise-king-sullyman** [comment]
Is it just me or is the diff in that snapshot showing the same thing on each line?

**Comment by gitdallas** [comment]
yea.. i can't see a difference.. maybe a different type of space character or something? i'd be curious in you copying the line in question and converting to ascii.. then updating the snapshot and doing the same, see if something changed.

**Comment by adamviktora** [comment]
Yes, you are both right. It is a problem with the space just before "AM" (or PM in the next test).

This is the snapshot: 1/1/2022%2C%2012%3A00%3A00**%20**AM ([Space](https://www.fileformat.info/info/unicode/char/0020/index.htm))
And this is actually received: 1/1/2022%2C%2012%3A00%3A00**%u202F**AM ([Narrow no-break space](https://www.fileformat.info/info/unicode/char/202f/index.htm))

**Comment by adamviktora** [comment]
It seems, that `new Date().toLocaleString()` creates 'NARROW NO-BREAK SPACE' character before AM / PM in my localization.

Here is a suggestion, how it could be repaired: [timestamp test repair commit](https://github.com/patternfly/patternfly-react/commit/183a8d1192a249ab6bf8353ea786e1e5f8077372)

I have edited the tests, so they replace the 'NARROW NO-BREAK SPACE' with classic space before calling the `screen.getByText(...)` method.

I did not find an easy way to modify `asFragment` so it uses classic space, because it consists of a whole component using the `.toLocaleString()` internally. So I have modified the snapshot to use the 'NARROW NO-BREAK SPACE' -- but this is probably not a good way, because now it will break these localizations, which are using classic space. I don't know how to extend this `expect(asFragment()).toMatchSnapshot();` condition, so we can compare fragment and snapshot as strings -- so the conversion of the narrow nbsp to space could be appliable.

Anyway, overall I don't think this is a great solution, it seems to me like only "hiding a problem" by this conversion of nbsp to space character -- and it could create some other troubles in the future.

**Comment by adamviktora** [comment]
It actually might be a [Node version issue](https://github.com/nodejs/node/issues/45171). 

To reproduce the bug: I am using node v18.14.0, yarn 1.22.19

**Comment by Dominik-Petrik** [comment]
Slightly better solution than explicitly replacing spaces in the tested string would be to use [normalisation](https://testing-library.com/docs/queries/about#normalization). Tested strings are getting normalised, which seems to mess up the spaces. We can configure the normalisation like this:
Screenshot 2023-02-16 at 13 19 49
I am not sure how to handle the snapshot failing, because there seems to be no way to configure normalisation on snapshot.

**Comment by gitdallas** [comment]
screenshot is based on what the app produces, so if you normalize it in the app (timestamp component?) it will update the screenshot that way.

**Comment by Dominik-Petrik** [comment]
> screenshot is based on what the app produces, so if you normalize it in the app (timestamp component?) it will update the screenshot that way.

Yeah, but the matchers are getting normalized and not what gets rendered. And since snapshots are not getting matched, we can't use normalization on them.

**Comment by wise-king-sullyman** [comment]
If it's a Node version issue would it potentially be resolved as part of #8303?

**Review by wise-king-sullyman — APPROVED** [review]

**Pull request merged**
