### PR TITLE
fix(TreeView): expand/collapse on filtering

### LINKED ISSUE #5351: Treeview: Using search with treeview should reveal leaf nodes matching the search criteria
**Describe the issue. What is the expected and unexpected behavior?**
When using treeview to search a string in the tree, the branch nodes are correctly filtered, however the leaf nodes aren't expanded when there is a match. The user would have to expand manually to see the matched string.
**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug
**What is your product and what release version are you targeting?**
Openshift, unscheduled

cc: @evwilkin

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #5351

### CODE REVIEW

**Review by mcarrano — APPROVED** [review]
Looks good @kmcfaul !

@jcaianirh is this also what you were expecting?

**Review by jcaianirh — COMMENTED** [review]
@kmcfaul this is great, and yes this @mcarrano this is exactly what we were looking for. One bug i'm experiencing is that when i search for current, and start typing c all leaf nodes are expanded even though they don't contain the letter c. This doesn't, however, happen when i start typing settings as only the settings nodes are expanded

**Review by nicolethoen — APPROVED** [review]
very cool!

**Comment by kmcfaul** [comment]
Re: the search with `c` everything gets expanded because the filter is matching the string anywhere in the text, so all folders/leaves have `c` in them somewhere (like "Application 1" gets matched so the whole folder expands). Filtering behavior can be updated in the `filterItems` function of the example.

**Review by tlabaj — APPROVED** [review]

**Review by dlabrecq — COMMENTED** [review]
LGTM

**Pull request merged**
