### PR TITLE
fix(nav):  Reverts PR #10644 that caused regression

### LINKED ISSUE #10897: Bug - [NavList] - [Scroll buttons no longer show up when resizing]
**Describe the problem**

In our automated pixel test we no longer see the left/right scroll buttons to browse through a navlist when the display is too small to see all nav items. When we refresh the page the buttons show up again.

This problem started in an upgrade to 5.4.0 for us.

**How do you reproduce the problem?**

I can reproduce this with the [NavList Tertiary Demo](https://www.patternfly.org/components/navigation/react-demos#tertiary-nav-deprecated)

**Expected behavior**

Buttons show up.

**Is this issue blocking you?**

For now we work around it in the test.

**Screenshots**

Demo screencast:
[Screencast from 2024-09-03 14-20-53.webm](https://github.com/user-attachments/assets/9fa338bb-7419-46d7-894b-708f02159f00)

**What is your environment?**
 - OS: Red Hat Linux
 - Browser Firefox
 - Version latest

**What is your product and what release date are you targeting?**

Cockpit, none.

**Any other information?**

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #10897 

cc @dlabaj we will want to promote a patch release for this

### CODE REVIEW

**Review by kmcfaul — APPROVED** [review]

**Review by dlabaj — APPROVED** [review]

**Comment by martinpitt** [comment]
@dlabaj Thanks for fixing this! As this causes us quite some trouble, asking here: The [5.4.2 release](https://github.com/patternfly/patternfly-react/releases/tag/v5.4.2) happened 4 days ago already, but https://www.npmjs.com/package/@patternfly/react-core is still stuck with 5.4.1. Did something in the release go wrong?

**Comment by martinpitt** [comment]
@dlabaj ah, 5.4.2 (and 5.4.8) are in the v5-prerelease channel, not "latest". This is confusing. Sorry for the noise!

**Comment by dlabaj** [comment]
@martinpitt Thanks for catching this will fix the release to npm now.

**Comment by dlabaj** [comment]
@martinpitt It's all set on npm now.  Thanks for catching this again.

**Pull request merged**
