### PR TITLE
feat(catalog item header): add CatalogItemHeader component

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
affects: patternfly-react-extensions

**What**:
The CatalogItemHeader component can be used as the header data shown for catalog item details views and for catalog item ordering views.

**Link to Storybook**:
https://rawgit.com/jeff-phillips-18/patternfly-react/catalog-item-header-storybook/index.html?selectedKind=patternfly-react-extensions%2FCatalog%20Components%2FCatalog%20Item%20Header&selectedStory=Catalog%20Item%20Header&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

related to #632 

@serenamarie125  @tlwu2013

### CODE REVIEW

**Comment by dtaylor113** [comment]
Is there a follow up PR for applying CatalogItemHeader to CatalogTile?

**Comment by jeff-phillips-18** [comment]
They are different. The tile header is smaller and the layout is different

**Comment by jeff-phillips-18** [comment]
Updated the `.catalog-item-header-pf-icon` to have a fixed width of 60px and a max-height of 60px per @tlwu2013

**Comment by serenamarie125** [comment]
Looks great @jeff-phillips-18 !

**Comment by tlwu2013** [comment]
Looks good to me, thanks!

**Pull request merged**
