### PR TITLE
feat(Label): adjust editable keyboard behavior

### LINKED ISSUE #7547: LabelGroup - review editable label keyboard interaction
Some issues from #7515:
- When editing a label and hitting enter to confirm the edit, focus isn't shown immediately.
- When using keyboard to navigate the editable label group (modal variant) example, focus from the menu is returned to the close button rather than menu toggle.

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #7547

Should now make keyboard focus the editable label after finishing an edit. Also fixes some minor focus issues with the add label modal demo.

### CODE REVIEW

**Review by thatblindgeye — COMMENTED** [review]
I'm noticing the focus bug remains for the "Editable labels with add button" example and the demos, but only when changing the label text (hitting "Escape", or hitting "Enter" without changing the text, places focus correctly).

Otherwise the "Editable labels" example and the modal demo's menu toggle focus looks good

**Comment by kmcfaul** [comment]
Was able to fix that changing the key in those demos to not reference the changing name (which I think was causing the button to remount + lose focus).

**Review by thatblindgeye — APPROVED** [review]
🎉

**Review by tlabaj — COMMENTED** [review]
Looks good.  I just realized though that the whole Label Group component is beta.  I know it is out of scope for the PR, but can you please  remove the beta tags from the examples and props.

**Review by tlabaj — APPROVED** [review]
LGTM

**Pull request merged**
