### PR TITLE
feat(Wizard): implement success status on steps / nav items

### PR DESCRIPTION
**Pull request by nicolethoen**
Closes https://github.com/patternfly/patternfly-react/issues/10691

updated Step status example in wizard docs: https://patternfly-react-pr-10714.surge.sh/components/wizard#step-status

### CODE REVIEW

**Review by andrew-ronaldson — APPROVED** [review]
implementation looks good

**Review by kmcfaul — APPROVED** [review]

**Review by mcoker — COMMENTED** [review]
Looks like we lost the step number in the toggle for all steps that don't have a status

https://patternfly-react-pr-10714.surge.sh/components/wizard/react/basic/

Screenshot 2024-07-16 at 11 59 46 AM

**Review by thatblindgeye — APPROVED** [review]
Other than the above lgtm, looks like it's just to do with isActiveStepStatus not having any default value within WizardToggle

**Review by mcoker — APPROVED** [review]
🧙‍♂️

**Review by wise-king-sullyman — APPROVED** [review]

**Pull request merged**
