### PR TITLE
docs(Expandable section, file upload, modal, pagination): add compone…

### LINKED ISSUE #7978: Expandable section, file upload, modal, pagination - add subcomponent descriptions
**Is this a new component or an extension of an existing one?**
Builds towards #7010

### PR DESCRIPTION
**Pull request by thatblindgeye**
…nt descriptions

**What**: Closes #7978 

I also reordered props alphabetically to make it easier to parse (most files updated involve just this), and did some minor tidying of prop descriptions.

Currently only some of the Modal sub-components are exposed on the Modal page. I'm wondering whether any others should be as well, or if any should be removed from the Modal page.

**Additional issues**:

### CODE REVIEW

**Review by nicolethoen — CHANGES_REQUESTED** [review]
By reading these descriptions of ModalBoxXX components, It's feeling like we shouldn't be exporting the ModalBoxXX components? they are used by the ModalContent component. That component likely shouldn't be exported either, since its imported by the Modal component and not used in our examples? 

Ceasing to export these sub-components would definitely be a breaking change, but we may not need to reference them in the docs if they are meant to be internal components only? Either that, or we should open an issue to build an example demonstrating how consumers can use these exported components. @tlabaj do you have more insights or a preference here?

**Review by tlabaj — CHANGES_REQUESTED** [review]
I would not make any changes to Modal is was not design to be composable.  If anything I would hide the sub componets form docs.  They are nit used in any of the examples.

**Comment by thatblindgeye** [comment]
@tlabaj @nicolethoen The latest update removes descriptions to the Modal components, and also removes all but Modal from the prop docs.

**Review by nicolethoen — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]
LGTM

**Pull request merged**
