### PR TITLE
Catalog view extension - organize docs

### LINKED ISSUE #7693: CatlogView Extension - Organize Docs
Part of [effort](https://github.com/patternfly/patternfly-org/issues/2903) to add/organize extension documentation.

### PR DESCRIPTION
**Pull request by CooperRedhat**
**What**: Closes #7693

**Additional issues**:
https://github.com/patternfly/patternfly-org/issues/2903
https://github.com/patternfly/patternfly-org/issues/2910

### CODE REVIEW

**Review by jschuler — CHANGES_REQUESTED** [review]
Hm, there shouldn't be a react-docs/src folder, generated files should be under react-docs/patternfly-docs/generated

**Review by jschuler — APPROVED** [review]

**Comment by jschuler** [comment]
Nice, cleans up the side nav (in local workspaces we see it listed under Extensions). Of course visibility in pf.org will be a wider discussion, but that is not what this PR affects.

**Review by mcarrano — APPROVED** [review]
This looks good as an interim step.

**Review by gitdallas — APPROVED** [review]

**Comment by evwilkin** [comment]
Planning to pull Catalog View out into its own repo after similar work for Log viewer is completed in https://github.com/patternfly/patternfly-org/pull/3188, we will hold off on this work until the repo has been split out

**Pull request closed without merging**
