### PR TITLE
#5027 - custom Chip render props in the multi Typehead select .

### PR DESCRIPTION
**Pull request by anujsingla**
**What**: Closes # https://github.com/patternfly/patternfly-react/issues/5027

**Additional issues**: It is improvement and added new props.

### CODE REVIEW

**Review by redallen — CHANGES_REQUESTED** [review]
If you could make the API take a React.ReactNode that'd match other component and would be more flexible!

**Comment by anujsingla** [comment]
@redallen Thanks for the review, I have made changes as per your suggestion. Please review.

**Review by redallen — APPROVED** [review]
Thanks, LGTM!

**Review by nicolethoen — APPROVED** [review]
LGTM

**Pull request merged**
