### PR TITLE
chore(CI): updated node version used for gh actions

### LINKED ISSUE #8303: Upgrade node engine to v18

### PR DESCRIPTION
**Pull request by wise-king-sullyman**
**What**: Closes #8303 

**Additional issues**:

### CODE REVIEW

**Comment by wise-king-sullyman** [comment]
Adding do not merge as I think I might have found an issue when doing a test merge of this in my fork

**Comment by wise-king-sullyman** [comment]
Should be good to merge now that I've pulled in the changes I made in the latest docs-framework alpha and enabled that new behavior using the legacySSL flag.

**Comment by wise-king-sullyman** [comment]
The docs build failure that's showing is because the actions are currently still running as node v14.

We can either merge it with the failing check, or I can remove the legacySSL flag from this PR and add it back in a followup PR. Going that route will mean that this PR will fail to build when it's merged though.

**Review by nicolethoen — APPROVED** [review]

**Comment by wise-king-sullyman** [comment]
I think this should be good to merge now, but _just in case_ it starts causing gh actions related issues we may want to make it the last thing we merge before we go into code freeze.

**Comment by nicolethoen** [comment]
Looks like the build is complaining about openssl
`/opt/hostedtoolcache/node/14.21.3/x64/bin/node: bad option: --openssl-legacy-provider`

**Comment by wise-king-sullyman** [comment]
@nicolethoen yeah it will complain since that option wasn't added until node v17. Once it gets merged and the GH actions actually start running using node 18 it won't complain, and if we don't have that flag the build will fail with 18.

I can remove the flag for now and add it back in a followup if we want to go that way. It will just mean that the release CI will definitely fail once it merges.

**Comment by nicolethoen** [comment]
I get it. I think it's fine. I think we can merge this on Monday and if anything extra pops up from this, I can dig into it while people are catching up on code mods

**Review by thatblindgeye — APPROVED** [review]

**Review by gitdallas — APPROVED** [review]

**Pull request merged**
