### PR TITLE
fix(descriptionList): change autoMinFitModifier to autoFitMinModifier

### LINKED ISSUE #5226: Change autoMinFitModifier to autoFitMinModifier in DescriptionList
**Describe the issue. What is the expected and unexpected behavior?**
the DescriptionList component has the `autoMinFitModifier` but it is supposed to be `autoFitMinModifier` as asked [here](https://github.com/patternfly/patternfly-react/pull/5113#discussion_r534395075)

I by mistake misspelled it and put the `Min` before `Fit`.

//cc @mattnolting

### PR DESCRIPTION
**Pull request by boaz0**
**What**: Closes #5226 

~~I hope this will be merged before we will release this.~~ 
**Edit**: I just realized it is too late because this mistake was already released. So my question is what should we do now?
Thanks

//cc @mattnolting

### CODE REVIEW

**Comment by mattnolting** [comment]
Perfect! Approved 👍

**Review by jschuler — APPROVED** [review]
previous change was released to the pre-release version and is not yet included in the official release so this change should be fine

**Review by evwilkin — APPROVED** [review]
LGTM

**Comment by boaz0** [comment]
Thank you for the fast response and feedback @mattnolting @jschuler and @evwilkin

**Pull request merged**
