### PR TITLE
feat(Button): add text wrapper, update icon usage

### LINKED ISSUE #10626: Button - update to support wrappers for icon and text
Placeholder issue, follow up to core work in https://github.com/patternfly/patternfly/issues/5944 and https://github.com/patternfly/patternfly/issues/6245

Discussed with @tlabaj the docs/API change could be:
* Children is always treated as the text. We'll wrap children in the text wrapper.
* Icons are always passed via the `icon` prop. Any positioning continues to happen via `iconPosition`, though we may or may not need to apply a class for the position anymore. 
* ^ applies to all buttons, including plain.

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #10626

- Updates Button such that all children will be wrapped by `pf-v6-c-button__text`, and whenever an `icon` is passed in that icon will be wrapped by `pf-v6-c-button__icon` (was previously for non-plain buttons, now applies to all button icons).
- Updates usages of our Buttons to passing the `icon` prop instead of an icon child.
- Updates `DualListSelectorControl` to have an `icon` prop that is passed through to the internal Button.
- Updates snapshots.

This PR will be failing until https://github.com/patternfly/patternfly-react/pull/10661 is merged due to the core bump.

### CODE REVIEW

**Review by nicolethoen — APPROVED** [review]
Can't wait to see the codemod for plain buttons to pass their children to icon prop

**Review by thatblindgeye — APPROVED** [review]
Looks good. Codemod issue: https://github.com/patternfly/pf-codemods/issues/680

**Review by tlabaj — APPROVED** [review]

**Comment by mcoker** [comment]
FYI ran visual regression tests before/after this update and there were no differences other than demos that dynamically generate content on page render

Link to the backstop report - [backstop-react-7.2.24.pdf](https://github.com/user-attachments/files/16074019/backstop-react-7.2.24.pdf)

**Review by mcoker — APPROVED** [review]
LGTM!!!

**Pull request merged**
