### PR TITLE
fix: PF4 Fix HelperText definition in LoginForm

### LINKED ISSUE #1550: [PF4][Bug] Login form helperText definition is wrong
In LoginForm.d.ts  helperText is string when in the js is a node.

### PR DESCRIPTION
**Pull request by aljesusg**
HelperText need to be ReactNode

Fix #1550

### CODE REVIEW

**Comment by aljesusg** [comment]
please @dlabaj can you review this?

**Comment by aljesusg** [comment]
@serenamarie125 @priley86 there is a typo here

**Comment by aljesusg** [comment]
Thanks @dlabaj @tlabaj , maybe we should think about make some test for this...it's not the first time that there is a problem with the definitions

**Comment by serenamarie125** [comment]
thanks for your contribution here @aljesusg !

**Pull request merged**
