### PR TITLE
chore: add linting for package publication

### PR DESCRIPTION
**Pull request by jonkoops**
Adds a linting task called `lint:publication` which integrates [`publint`](https://publint.dev/) so that it is ran on every package in the workspace that is published to NPM. This allows [common errors](https://publint.dev/rules) to be caught, especially in relation to publishing dependencies that have mixed CommonJS and ES modules.

### CODE REVIEW

**Comment by jonkoops** [comment]
Not that I haven't added this script to run on CI, as it currently fails. There are several issues in the packages that will need to be resolved before this can be enabled.

**Comment by nicolethoen** [comment]
> Note that I haven't added this script to run on CI, as it currently fails. There are several issues in the packages that will need to be resolved before this can be enabled.

Is there a way we can document those issues? in a follow up issue maybe?

**Comment by jonkoops** [comment]
> Is there a way we can document those issues? in a follow up issue maybe?

That would work, I can log some follow up tasks with a tracker if you like.

**Comment by jonkoops** [comment]
I'll mark this one as ready to review, and log some follow up issues.

**Review by nicolethoen — APPROVED** [review]

**Comment by jonkoops** [comment]
Since `main` is now in freeze I went ahead and re-directed this PR to the `v6` branch.

**Review by tlabaj — APPROVED** [review]

**Pull request merged**
