### PR TITLE
chore(primary-detail): fixed card shadow on hover

### PR DESCRIPTION
**Pull request by mcoker**
**What**: Closes https://github.com/patternfly/patternfly-react/issues/5742

https://patternfly-react-pr-5790.surge.sh/demos/primary-detail/react-demos/primary-detail-card-view/

### CODE REVIEW

**Review by evwilkin — APPROVED** [review]
LGTM - thanks!

**Review by nicolethoen — DISMISSED** [review]

**Review by mattnolting — COMMENTED** [review]
What do you think about adding `pf-u-ml-md` to `pf-c-drawer__panel` instead of adjusting padding?

**Review by kmcfaul — APPROVED** [review]

**Review by mcarrano — COMMENTED** [review]
Not sure exact;ly what I'm looking for here. @gdoyle can you verify that this fixes your original issue?

**Comment by mcoker** [comment]
@mcarrano I put this on hold for the time being, @mattnolting pointed out an issue and I'd like to review the design before fixing it.

**Comment by mcoker** [comment]
@mcarrano @gdoyle I added the on hold label because @mattnolting pointed out an issue we'll need to resolve. Looks like the demos between core and react are different.

react - https://patternfly-react.surge.sh/demos/primary-detail/react-demos/primary-detail-card-view/
core - https://pf4.patternfly.org/demos/primary-detail/html-demos/primary-detail-card-view-expanded/

Particularly I'm curious about the spacing and placement of the toolbar. In core, the toolbar is a section outside of the card view section with the grey background. In react, the toolbar is in the card view section with the grey background. Should those be the same? If core is correct, I can update that in this PR and that will fix the issue @mattnolting pointed out.

**Comment by mcarrano** [comment]
Yeah, the core demo is correct @mcoker . Not sure where the React version came from. We never layout a toolbar that way.

**Review by mattnolting — APPROVED** [review]
LPTM 🔥

**Review by jessiehuff — APPROVED** [review]
LGTM!

**Review by tlabaj — APPROVED** [review]

**Pull request merged**
