### PR TITLE
fix(masthead): add styling and example for horizontal masthead menu items

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
affects: patternfly-react

**Link to Storybook**:
https://rawgit.com/jeff-phillips-18/patternfly-react/masthead-storybook/index.html?selectedKind=patternfly-react%2FApplication%20Framework%2FMasthead&selectedStory=Horizontal%20Menu

### CODE REVIEW

**Comment by dabeng** [comment]
Does it make sense to let dropdown toggle button to be a full-width button ?

screen shot 2018-07-03 at 11 20 55 am


screen shot 2018-07-03 at 11 20 27 am

FYI, https://getbootstrap.com/docs/3.3/javascript/#within-a-navbar

**Comment by jeff-phillips-18** [comment]
Updated to use the `componentClass` of Dropdown so as to mimic the Patternfly Core HTML structure. Removed the masthead less/sass overrides (thanks @priley86).

@dabeng This is the styling inherited from PF Core. If there is an issue, please file it in [patternfly/patternfly](https://github.com/patternfly/patternfly).

**Comment by priley86** [comment]
looks great to me now! thanks @jeff-phillips-18

**Comment by jeff-phillips-18** [comment]
Coverage drop is due to one line that cannot be tested:
```
  const dropdownComponentClass = dropdownProps => (
--->    <li className={dropdownProps.className}>{dropdownProps.children}</li>
  );
 ```

**Comment by priley86** [comment]
going ahead w/ merge... not a big issue.

**Pull request merged**
