### PR TITLE
chore(DashboardWrapper + DashboardHeader) convert to TS

### LINKED ISSUE #9553: Convert DashboardHeader to TS

### LINKED ISSUE #9617: Convert DashboardWrapper to TS

### PR DESCRIPTION
**Pull request by Dominik-Petrik**
**What**: 

- Closes #9617
- Closes #9553 

When yarn start is run there are a few module resolution changes I am not able to solve.

### CODE REVIEW

**Review by jenny-s51 — COMMENTED** [review]
Fixed all module resolution errors and this is working and building as expected locally - currently investigating rollup issue in `build:umd` step. 

I've moved the `DashboardWrapper` and `DashboardHeader` components into `react-core` since it makes more sense to import them into files with the other react-core imports. This is going to need some build/infra related updates.

**Review by jenny-s51 — COMMENTED** [review]
Update: Added `rollup/plugin-svg` which was missing from configs and causing svg imports to break the build. This was breaking jest tests as well which needed their own svg transformer `jest-transform-stub`. 

These updates to the build here should close https://github.com/patternfly/patternfly-org/issues/3757 in org.

**Note: merging this should unblock a lot of the remaining work/PRs in the [demo conversion epic ](https://github.com/patternfly/patternfly-react/issues/9367), several of which depended on the Dashboard components getting converted to TS**

**Review by thatblindgeye — COMMENTED** [review]
Looks like there's a few Table demos still importing the old DashboardWrapper from the `demos/examples` directory (Empty, Loading, and Error in the "Empty states" section of examples). Otherwise looks good. Only thing is if we'd want to have the Dashboard components able to be imported by consumers; there'd probably be not much use-case for them to import it in the first place, but just wondering if the files should remain in the demos directory, or just not exported in our index file.

**Review by jenny-s51 — COMMENTED** [review]
Thank you @thatblindgeye - good point. At the moment our build-configs don't seem to support TSX exports from `src/demos`, so I'm investigating how we can make the necessary build updates to move these Dashboard components back to the `demos` folder.

**Review by thatblindgeye — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]
LGTM

**Pull request merged**
