### PR TITLE
fix(Input group): Removed variant prop from input group text

### LINKED ISSUE #9146: Bug - Input group - PR 9074 review follow up
**Describe the problem**
A clear and concise description of the problem. Which components are affected?
This is to track changes needed from core review of #9074z
This will remove the variant prop that is no longer needed.

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #9146

### CODE REVIEW

**Review by mcoker — APPROVED** [review]
🎃👍

**Comment by wise-king-sullyman** [comment]
I'm guessing that the docs CI errors are coming from the variant still being used in an example and an integration demo:
image

**Comment by nicolethoen** [comment]
I think this will need a codemod, too.

**Comment by wise-king-sullyman** [comment]
@nicolethoen I already have one up 🙂 https://github.com/patternfly/pf-codemods/pull/480

**Review by thatblindgeye — APPROVED** [review]

**Review by wise-king-sullyman — APPROVED** [review]

**Pull request merged**
