### PR TITLE
chore(wizard): updated button order

### LINKED ISSUE #8166: Wizard - update footer button order
Placeholder for core work in https://github.com/patternfly/patternfly/issues/5110.

### PR DESCRIPTION
**Pull request by jenny-s51**
**What**: Closes #8166 

Also fixes some bugs in the button functionality within the demos.

### CODE REVIEW

**Review by thatblindgeye — COMMENTED** [review]
This looks great! One thing I'm wondering is for the "Validate on button press" example on "Final Step", whether both of those buttons should be the primary variant, and whether "Go to beginning" should be first like the "Back" buttons. cc @mcarrano

**Review by mcarrano — COMMENTED** [review]
> One thing I'm wondering is for the "Validate on button press" example on "Final Step", whether both of those buttons should be the primary variant, and whether "Go to beginning" should be first like the "Back" buttons.

I agree with that. The way it is now feels odd. We would never to two primary buttons together like that. Otherwise this looks good.

Just want to make sure this is not intended to be merged into the v4 branch. This is an update for v5, only.

**Review by thatblindgeye — APPROVED** [review]

**Review by jenny-s51 — COMMENTED** [review]
That was a nice catch @thatblindgeye! I've updated the order and styling based on your and @mcarrano 's comments. This will indeed be merged to v5!

**Review by mcarrano — APPROVED** [review]
Looks great. Thanks @jenny-s51 !

**Review by mcoker — COMMENTED** [review]
Nice! Only thing I spotted was this async footer in the [wizard next kitchen sink example](https://patternfly-react-pr-8409.surge.sh/components/wizard/react-next#kitchen-sink) - should this be updated, too?

Screenshot 2022-12-05 at 11 18 04 AM

**Review by kmcfaul — APPROVED** [review]

**Review by mcoker — APPROVED** [review]
🥳

**Pull request merged**
