### PR TITLE
feat(BackgroundImage): update background image for penta

### LINKED ISSUE #9914: Consume core Penta updates: Background image
Follow up to core issue https://github.com/patternfly/patternfly/issues/6145

### PR DESCRIPTION
**Pull request by wise-king-sullyman**
**What**: Closes #9914

**Additional issues**:

Convenience link: https://patternfly-react-pr-9964.surge.sh/components/background-image/react/basic/

### CODE REVIEW

**Review by thatblindgeye — APPROVED** [review]

**Review by andrew-ronaldson — APPROVED** [review]
Sweet, thanks!

**Review by srambach — APPROVED** [review]
🤩 LGTM!

**Review by kmcfaul — APPROVED** [review]

**Review by lboehling — APPROVED** [review]
perfect!

**Review by tlabaj — APPROVED** [review]
LGTM

**Pull request merged**
