### PR TITLE
fix(DatePicker) clear validation error from outside

### LINKED ISSUE #7818: Bug - [DatePicker] - Cannot clear validation error from outside
Trying to control the value of the DatePicker from outside the component. Once the datepicker becomes invalid (in this case by typing a date less than 2020-03-17), I can no longer clear the error from outside.

I have the case where a user can enter an invalid date (outside the allowable date range).
When they use another control to try and reset the date, it doesn't work.

Codesandbox: https://codesandbox.io/s/misty-lake-r73ehn

To reproduce:
- Manually enter a value less than 2020-03-17
- Observe validation error triggered, input has error icon
- Click the button which updates the value of the datepicker
- Error icon is still there

I'd expect the error to be cleared

Reproducible example:
```
export const DatePickerTest: React.FunctionComponent = () => {
  const rangeValidator = (date: Date) => {
    // when you open the picker, dates less than will be grayed out
    // but you can still manually enter a lesser date
    if (date < new Date("2020-03-17")) {
      return "error";
    }
    return "";
  };
  const [value, setValue] = React.useState("2020-03-17");
  const onChange = (dateStr, date) => {
    setValue(dateStr);
  };
  return (
    <>
      <div>value: {value}</div>
      <div>
        <DatePicker
          value={value}
          onChange={onChange}
          validators={[rangeValidator]}
        />
      </div>
      <div>
        <button onClick={() => setValue("2020-03-18")}>Date 2020-03-18</button>
      </div>
    </>
  );
};
```

### PR DESCRIPTION
**Pull request by Dominik-Petrik**
**What**: Closes #7818

### CODE REVIEW

**Review by thatblindgeye — APPROVED** [review]
Looks good! Tested using the code provided in the original issue and was able to clear the error from the outside 🎉

**Review by jenny-s51 — APPROVED** [review]
LGTM @Dominik-Petrik ! Works and tests great 🚀

**Review by tlabaj — CHANGES_REQUESTED** [review]
Can you please add a cypress integration test to verify the fix?

**Comment by Dominik-Petrik** [comment]
> Can you please add a cypress integration test to verify the fix?

Sure thing!

**Review by tlabaj — APPROVED** [review]
LGTM!

**Pull request merged**
