### PR TITLE
feat(page layout demos): Add PF4 page layout demos

### PR DESCRIPTION
**Pull request by jschuler**
Closes: #549, #745

**What**:
Adds the page layout demos to PF4
Also rolled in a fix and small improvements to docs

### CODE REVIEW

**Comment by jschuler** [comment]
@dlabrecq This PR should fix the full page URLs but I noticed that the background image example cannot find the images since the code is looking for them at the root when it really is under `/patternfly-4/`. So depending on dev/prod build and path-prefixes the assets location can change which the example is not aware of as of yet.

**Comment by dlabrecq** [comment]
Not sure what @dgutride did to support surge, but perhaps we can use that post build process to modify the image paths to include `/patternfly-4?

**Comment by priley86** [comment]
nice work! the expandable navigation demo is particularly appealing to me:
https://749-pr-patternfly-react-patternfly.surge.sh/patternfly-4/demos/pagelayout/examples/page-layout-expandable-nav/

should the expandable nav which is not active have a `ChevronRightIcon`?

**Comment by jschuler** [comment]
Hi @priley86 , yes that is actually a core css bug. I opened an issue for it here
https://github.com/patternfly/patternfly-next/issues/779

**Pull request merged**
