### PR TITLE
Added OUIA compatibility for Dropdown

### PR DESCRIPTION
**Pull request by quarckster**
Part of #2423

What: Added OUIA props to Dropdown as per #2423

### CODE REVIEW

**Comment by quarckster** [comment]
@redallen please help with type matching. Tests failed due to this issue.

**Comment by karelhala** [comment]
@quarckster looks like the problem was with incorrect `onSelect` type. This should do the trick.
```diff
diff --git a/packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.tsx b/packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.tsx
index 4cc061c65..86ee33ed3 100644
--- a/packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.tsx
+++ b/packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.tsx
@@ -23,7 +23,7 @@ export interface DropdownProps extends React.HTMLProps<HTMLDivElement> {
   /** Toggle for the dropdown, examples: <DropdownToggle> or <DropdownToggleCheckbox> */
   toggle: React.ReactElement<any>;
   /** Function callback called when user selects item */
-  onSelect?(event: React.SyntheticEvent<HTMLDivElement>): void;
+  onSelect?(event?: React.SyntheticEvent<HTMLDivElement>): void;
   /** Flag to indicate if the first dropdown item should gain initial focus, set false when adding
    * a specific auto-focus item (like a current selection) otherwise leave as true
    */
diff --git a/packages/patternfly-4/react-core/src/components/Dropdown/DropdownWithContext.tsx b/packages/patternfly-4/react-core/src/components/Dropdown/DropdownWithContext.tsx
index fe1ea2218..307e825e8 100644
--- a/packages/patternfly-4/react-core/src/components/Dropdown/DropdownWithContext.tsx
+++ b/packages/patternfly-4/react-core/src/components/Dropdown/DropdownWithContext.tsx
@@ -21,7 +21,7 @@ class DropdownWithContext extends React.Component<DropdownProps & InjectedOuiaPr
     isGrouped: false,
     position: DropdownPosition.left,
     direction: DropdownDirection.down,
-    onSelect: Function.prototype,
+    onSelect: (): void => undefined,
     autoFocus: true,
     ouiaComponentType: 'Dropdown'
   };

```

Also don't forget to run `node_modules/.bin/jest -u packages/patternfly-4/react-core/src/components/` in order to update your snapshots.

**Comment by redallen** [comment]
@quarckster I believe @karelhala is correct. This mismatching type for `onSelect` is `Function` vs `(event: SyntheticEvent<HTMLDivElement, Event>) => void`.

**Comment by karelhala** [comment]
Looks like the table snapshots were not updated @quarckster can you run `node_modules/.bin/jest -u packages/patternfly-4/` to fix the failing tests as well?

**Pull request merged**
