### PR TITLE
feat(Select): add toggle ref

### LINKED ISSUE #8478: Bug - [Modal/Single typeahead Select] - [Focus from select component inside modal is removed when a value is selected from it ]
**Describe the problem**
When using a select component with the variant single inside a modal, selecting a value from that select component resets the focus to the first element on the page instead of staying at the component that the user just clicked.

**How do you reproduce the problem?**
Create a select component with variant single inside a modal. Select a value from that component.
The expected behaviour is to have the focus stay on that component, instead it resets to the first element in the modal, i.e the close button
[Link](https://codesandbox.io/s/sharp-kepler-p8pl1e?file=/index.js:0-2915) to sandbox environment which reproduces the issue

**Expected behavior**
The focus should stay on the select compnent

**What is your environment?**
 - OS: Linux
 - Browser Chrome
 - PF version:4.267.6

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #8478

It looks like the single select variant didn't have support for re-focusing the toggle upon selection. I added the ability to pass in a toggle reference so a user can control when the toggle is focused (typically in the onSelect handler) & updated the related examples. 

Adding the refocus to the Toggle internally is also probably an option but it would be trickier to ensure it fired only the in the right circumstances (currently the toggle handles Tab/Escape because that always closes the menu but with selection, some selects should stay open and not refocus). I can take a crack at making the handling internal if we would rather have that than the external ref though.

### CODE REVIEW

**Review by nicolethoen — APPROVED** [review]
LGTM!

**Review by thatblindgeye — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]
LGTM

**Comment by kmcfaul** [comment]
The current tests effectively check that the ref is created when it is not passed (since that was the previous implementation), and I will add a test checking that a passed ref works as well.

**Review by tlabaj — COMMENTED** [review]
LGTM!

**Review by tlabaj — APPROVED** [review]

**Pull request merged**
