### PR TITLE
fix(NotificationDrawerWrapper): support empty notification action

### PR DESCRIPTION
**Pull request by TristanCacqueray**
**What**: Fix the NotificationDrawerWrapper to support actionless notification.

### CODE REVIEW

**Comment by dgutride** [comment]
@TristanCacqueray  - thanks for the contribution - once the build is passing, we can take this in.

**Comment by TristanCacqueray** [comment]
Pull-request updated, HEAD is now 4ab561a2be67861b0da88555a1bac516d8dbfae7

**Comment by TristanCacqueray** [comment]
Pull-request updated, HEAD is now 4ab561a2be67861b0da88555a1bac516d8dbfae7

**Comment by TristanCacqueray** [comment]
Pull-request updated, HEAD is now 0fad2d0d6afe2381946c21a0fca0febdf6a362f3

**Comment by TristanCacqueray** [comment]
I can't reproduce the eslint error locally, the new patch tries another syntaxt...

**Pull request merged**
