### PR TITLE
fix(DataToolbar): move and wrap chips in expandable content

### PR DESCRIPTION
**Pull request by nicolethoen**
Fixes [#3198 ](https://github.com/patternfly/patternfly-react/issues/3198)

follow up to Core issue [#2397](https://github.com/patternfly/patternfly-next/pull/2397)

### CODE REVIEW

**Comment by nicolethoen** [comment]
> There's an extra `__group` in `__expandable-content`

yes, that is a container that lets me cheat react and 'prepend' the components to display in the expandable content BEFORE the chip-container...

**Comment by nicolethoen** [comment]
@tlabaj ah sure. I'll update that

**Comment by mattnolting** [comment]
> @mattnolting yes, that is a container that lets me cheat react and 'prepend' the components to display in the expandable content BEFORE the chip-container...

Ok, I'll need to make one small CSS update to remove margin values. Not a blocker.

**Comment by mattnolting** [comment]
PERFECT🥇

**Pull request merged**
